notaphplover/one-game

.github/ISSUE_TEMPLATE/bug.yml, .gitignore, .npmrc, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, package.json, pnpm-workspace.yaml, turbo.json
- Added root npm package.
- Added license.
- Added several repo related docs.
- Added `turborepo` dependency.
=> Turborepo integration

packages/backend-prettier-config/.gitignore, packages/backend-prettier-config/LICENSE, packages/backend-prettier-config/index.js, packages/backend-prettier-config/package.json
- Added backend prettier config package.
=> Add backend-prettier-config package

packages/backend-typescript-config/.gitignore, packages/backend-typescript-config/package.json, packages/backend-typescript-config/prettier.config.js, packages/backend-typescript-config/tsconfig.base.composite.json, packages/backend-typescript-config/tsconfig.base.json
- Added backend typescript config package.
=> Add backend-typescript-config package

packages/backend-eslint-config/.gitignore, packages/backend-eslint-config/LICENSE, packages/backend-eslint-config/index.js, packages/backend-eslint-config/package.json
- Added backend eslint config package.
=> Add backend-eslint-config package

packages/backend-jest-config/.gitignore, packages/backend-jest-config/LICENSE, packages/backend-jest-config/jest.config.base.mjs, packages/backend-jest-config/jest.config.mjs, packages/backend-jest-config/jest.js.config.mjs, packages/backend-jest-config/package.json
- Added backend jest config package.
=> Add backend-jest-config package

packages/backend-typescript-config/tsconfig.base.composite.json
- Removed composite `typescript` config.
=> Remove composite ts config

.husky/pre-commit, package.json
- Added `husky` dependency.
- Added `pre-commit` hook.
=> Add husky integration

packages/json-schema-utils/src/json-schema/models/JsonSchema202012.ts, packages/json-schema-utils/src/traverse-json-schema/functions/traverseJsonSchema.ts
- Update `traverseJsonSchema` with better performance.
=> Update traverseJsonSchema to iterate only through existing properties

packages/backend-api-models/src/jsonSchema/application/models/apiSchemaHost.ts, packages/backend-api-models/src/jsonSchema/application/queries/ResolveApiSchemaHttpReferenceQuery.ts, packages/backend-api-models/src/jsonSchema/application/useCases/ResolveApiSchemaHttpReferenceUseCase.spec.ts, packages/backend-api-models/src/jsonSchema/application/useCases/ResolveApiSchemaHttpReferenceUseCase.ts, packages/backend-api-models/src/jsonSchema/infrastructure/bchernyJsonSchemaRefParser/SchemasRefParserOptionsBuilder.spec.ts, packages/backend-api-models/src/jsonSchema/infrastructure/bchernyJsonSchemaRefParser/SchemasRefParserOptionsBuilder.ts
- Updated `ResolveApiSchemaHttpReferenceQuery` with `referenceHostToSchemasRootDirectoryMap`
=> Update ResolveApiSchemaHttpReferenceQuery with referenceHostToSchemasRootDirectoryMap

.github/workflows/build.yml, package.json, packages/backend-scripts/.gitignore, packages/backend-scripts/.lintstagedrc.json, packages/backend-scripts/bin/getAffectedProjects.js, packages/backend-scripts/package.json, packages/backend-scripts/prettier.config.cjs, packages/backend-scripts/src/promisifiedExec.js
=> Add ci workflow

packages/backend-api-models/package.json, packages/backend-api-models/src/scripts/generateRelativeSchemas.ts, turbo.json
- (backend-api-models): updated build with relative Json schema generation.
=> Update build with relative schema generation

packages/backend-api-models/.gitignore, packages/backend-api-models/CHANGELOG.md, packages/backend-api-models/schemas/src/api/v1/cards/normal-card.json, packages/backend-api-models/schemas/src/api/v1/types.json, packages/backend-api-models/schemas/src/api/v1/users/user-create-query.json, packages/backend-api-models/schemas/src/api/v1/users/user-id-token-create-query.json, packages/backend-api-models/schemas/src/api/v1/users/user-id-update-query.json, packages/backend-api-models/schemas/src/api/v1/users/user.json, packages/backend-api-models/src/jsonSchema/application/useCases/ResolveApiSchemaHttpReferenceUseCase.spec.ts, packages/backend-api-models/src/jsonSchema/application/useCases/ResolveApiSchemaHttpReferenceUseCase.ts, packages/backend-api-models/src/models/api/types.ts, packages/backend-api-models/src/scripts/generateTsModels.ts, packages/json-schema-utils/.gitignore
- Added `UserCreateQueryV1`.
- Added `UserIdTokenCreateQueryV1`.
- Added `UserIdUpdateQueryV1`.
- Added `UserV1`.
=> Add user models

packages/backend-api-models/schemas/openapi/one-game.yaml
=> Add OpenApi spec

packages/url-utils/CHANGELOG.md, packages/url-utils/src/index.ts, packages/url-utils/src/relativeUrl.spec.ts, packages/url-utils/src/relativeUrl.ts
- Added `relativeUrl` function.
=> Add relative url function

packages/backend-api-models/package.json, packages/backend-api-models/schemas/openapi/one-game.yaml, packages/backend-api-models/src/scripts/bundleOpenApiSpec.ts, packages/backend-api-models/src/scripts/generateRelativeSchemas.ts, packages/json-schema-utils/CHANGELOG.md, packages/json-schema-utils/src/index.ts, packages/json-schema-utils/src/json-schema/functions/traverseJsonSchema.spec.ts, packages/json-schema-utils/src/json-schema/functions/traverseJsonSchema.ts, packages/json-schema-utils/src/json-schema/models/TraverseJsonSchemaCallbackParams.ts, packages/json-schema-utils/src/json-schema/models/TraverseJsonSchemaParams.ts
- Update `traverseJsonSchema` with TraverseJsonSchemaParams.
=> Update traverse json schemas with params

packages/backend-common/src/common/application/modules/Port.ts
- Renamed Port.adapt to `call`.
=> Rename Port.adapt to call

.github/workflows/build.yml, packages/backend-scripts/bin/getAffectedProjects.js
- Updated build workflow to avoid reporting code coverage.
=> Update build workflow to avoid reporting code coverage

packages/backend-common/CHANGELOG.md, packages/backend-common/src/common/application/modules/Port.ts, packages/backend-common/src/common/application/modules/PortAsync.ts, packages/backend-common/src/index.ts
- Added `PortAsync`.
- Updated `Port` to not to be asyncronous.
=> Add PortAsync

.github/renovate.json, packages/api-json-schemas-provider/package.json, packages/api-openapi-schema/package.json, packages/backend-api-models/package.json, packages/backend-api-validators/package.json, packages/backend-jest-config/package.json, packages/json-schema-utils/package.json, packages/openapi-utils/package.json, packages/url-utils/package.json
- Updated renovatebot to exclude `eslint-plugin-import`.
=> Update renovatebot to exclude eslint-plugin-import

packages/backend-http/CHANGELOG.md, packages/backend-http/src/http/models/application/Request.ts, packages/backend-http/src/http/models/application/RequestWithBody.ts, packages/backend-http/src/http/models/application/Response.ts, packages/backend-http/src/http/models/application/ResponseWithBody.ts, packages/backend-http/src/index.ts
- Added `Request`
- Added `RequestWithBody`
- Added `Response`
- Added `ResponseWithBody`
=> Add Request and Response models

packages/backend-http/CHANGELOG.md, packages/backend-http/src/http/controllers/application/HttpController.spec.ts, packages/backend-http/src/http/controllers/application/HttpController.ts, packages/backend-http/src/index.ts
=> Add HttpController

packages/backend-http/src/http/builders/application/ResponseBuilder.ts, packages/backend-http/src/http/builders/application/SingleEntityGetResponseBuilder.ts, packages/backend-http/src/http/builders/application/SingleEntityPostResponseBuilder.spec.ts, packages/backend-http/src/http/builders/application/SingleEntityPostResponseBuilder.ts
- Added `SingleEntityPostResponseBuilder`.
- Added `ResponseBuilder`.
- Updated `SingleEntityGetResponseBuilder` to extend `ResponseBuilder`.
=> Add SingleEntityPostResponseBuilder

packages/backend-http/CHANGELOG.md, packages/backend-http/src/index.ts
- Added `SingleEntityGetResponseBuilder`.
- Added `SingleEntityPostResponseBuilder`.
=> Expose response builders

packages/backend-env/.gitignore, packages/backend-env/CHANGELOG.md, packages/backend-env/package.json, packages/backend-env/src/env/services/DotEnvLoader.int.spec.ts, packages/backend-env/src/env/services/DotEnvLoader.ts, packages/backend-env/src/index.ts
=> Add DotEnvLoader

packages/backend-env/src/env/services/DotEnvLoader.ts, packages/backend-service-user/docker-compose.yml, packages/backend-service-user/package.json, packages/backend-service-user/src/app/modules/adapter/nest/AppModule.ts, packages/backend-service-user/src/foundation/db/modules/adapter/nest/DbModule.ts, packages/backend-service-user/src/foundation/env/models/application/Environment.ts, packages/backend-service-user/src/foundation/env/models/application/EnvironmentRaw.ts, packages/backend-service-user/src/foundation/env/services/EnvironmentLoader.ts
- Added `DbModule`.
- Fixed `EnvModule` to correctly parse env variables.
=> Add db module

packages/api-json-schemas/CHANGELOG.md, packages/api-json-schemas/schemas/v1/errors/error.json, packages/backend-api-models/src/index.ts, packages/backend-api-models/src/models/types.ts, packages/backend-service-user/package.json, packages/backend-service-user/src/foundation/jsonSchema/adapter/nest/modules/JsonSchemaModule.ts, packages/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts, packages/backend-service-user/src/user/application/handlers/PostUserV1RequestParamHandler.spec.ts, packages/backend-service-user/src/user/application/handlers/PostUserV1RequestParamHandler.ts
- Added `PostUserV1RequestParamHandler`
- Added `UserHttpApiModule`
=> Add PostUserV1RequestParamHandler

packages/backend-db/CHANGELOG.md, packages/backend-db/src/index.ts, packages/backend-db/src/persistence/services/typeorm/postgres/InsertTypeOrmPostgresService.ts, packages/backend-service-user/src/user/adapter/typeorm/services/CreateUserTypeOrmService.ts
- Added `InsertTypeOrmPostgresService`.
- Updated `CreateUserTypeOrmService` to extend `InsertTypeOrmPostgresService`.
=> Fix duplicate key 500 http errors

packages/api-openapi-schema/package.json, packages/api-openapi-schema/src/scripts/bundleOpenApiSpec.ts
- Fixed openapi doc `$schema` ref fields to no longer be included.
=> Fix openapi doc $schema ref fields

packages/backend/libraries/backend-http/CHANGELOG.md, packages/backend/libraries/backend-http/src/common/application/calculations/isPromiseLike.spec.ts, packages/backend/libraries/backend-http/src/common/application/calculations/isPromiseLike.ts, packages/backend/libraries/backend-http/src/http/application/modules/Middleware.ts, packages/backend/libraries/backend-http/src/http/application/modules/MiddlewarePipeline.spec.ts, packages/backend/libraries/backend-http/src/http/application/modules/MiddlewarePipeline.ts, packages/backend/libraries/backend-http/src/index.ts
- Added `Middleware`.
- Added `MiddlewarePipeline`.
=> Add middleware pipeline

packages/backend/libraries/backend-http/src/http/adapter/nest/controllers/HttpNestFastifyController.spec.ts, packages/backend/libraries/backend-http/src/http/adapter/nest/controllers/HttpNestFastifyController.ts
- Updated `HttpNestFastifyController` with optional `MiddlewarePipeline`.
=> Update HttpNestFastifyController with optional MiddlewarePipeline

packages/api/libraries/api-json-schemas/schemas/v1/auth/auth-create-query.json, packages/api/libraries/api-json-schemas/schemas/v1/auth/auth.json, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml
=> Add POST /v1/auth docs

packages/backend/services/backend-service-user/src/user/adapter/typeorm/converters/UserDbToUserConverter.spec.ts, packages/backend/services/backend-service-user/src/user/adapter/typeorm/converters/UserDbToUserConverter.ts, packages/backend/services/backend-service-user/src/user/domain/fixtures/UserFixtures.ts, packages/backend/services/backend-service-user/src/user/domain/models/User.ts
- Updated `User` with `passwordHash`.
=> Update User with password hash

packages/backend/services/backend-service-user/src/user/adapter/typeorm/converters/UserFindQueryToUserFindQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-user/src/user/adapter/typeorm/converters/UserFindQueryToUserFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-user/src/user/domain/fixtures/UserFindQueryFixtures.ts, packages/backend/services/backend-service-user/src/user/domain/models/UserFindQuery.ts
- Update `UserFindQuery` with `email`.
=> Update UserFindQuery with email

packages/backend/services/backend-service-user/CHANGELOG.md, packages/backend/services/backend-service-user/src/app/adapter/nest/modules/AppModule.ts, packages/backend/services/backend-service-user/src/auth/adapters/nest/controllers/PostAuthV1HttpRequestNestController.ts, packages/backend/services/backend-service-user/src/auth/adapters/nest/modules/AuthHttpApiModule.ts, packages/backend/services/backend-service-user/src/auth/adapters/nest/modules/AuthModule.ts, packages/backend/services/backend-service-user/src/auth/application/controllers/PostAuthV1HttpRequestController.ts, packages/backend/services/backend-service-user/src/auth/application/handlers/PostAuthV1RequestParamHandler.spec.ts, packages/backend/services/backend-service-user/src/auth/application/handlers/PostAuthV1RequestParamHandler.ts, packages/backend/services/backend-service-user/src/auth/application/ports/input/AuthManagementInputPort.spec.ts, packages/backend/services/backend-service-user/src/auth/application/ports/input/AuthManagementInputPort.ts, packages/backend/services/backend-service-user/src/foundation/jwt/adapter/nest/modules/JwtModule.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserModule.ts
- Added POST `v1/auth` endpoint.
- Added `AuthManagementInputPort`.
- Added `AuthModule`.
- Added `PostAuthV1RequestParamHandler`.
- Added `PostAuthV1HttpRequestController`.
- Added `PostAuthV1HttpRequestNestController`.
- Added `AuthHttpApiModule`.
=> Add post auth v1 http controller

packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.spec.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.ts, packages/backend/services/backend-service-user/src/auth/adapters/nest/modules/AuthModule.ts, packages/backend/services/backend-service-user/src/auth/application/middlewares/AuthMiddleware.ts, packages/backend/services/backend-service-user/src/user/application/models/UserJwtPayload.ts
=> Add AuthMiddleware

packages/backend/services/backend-service-user/CHANGELOG.md, packages/backend/services/backend-service-user/src/foundation/http/adapter/nest/modules/HttpModule.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/controllers/GetUserV1UserIdHttpRequestNestController.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts, packages/backend/services/backend-service-user/src/user/application/controllers/GetUserV1UserIdHttpRequestController.ts, packages/backend/services/backend-service-user/src/user/application/handlers/GetUserV1UserIdRequestParamHandler.spec.ts, packages/backend/services/backend-service-user/src/user/application/handlers/GetUserV1UserIdRequestParamHandler.ts
- Added GET `/v1/users/:userid`
=> Add GET /v1/users/:userid

packages/backend/services/backend-service-game/src/cards/domain/models/BaseCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/BlankCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/Card.ts, packages/backend/services/backend-service-game/src/cards/domain/models/CardColor.ts, packages/backend/services/backend-service-game/src/cards/domain/models/CardKind.ts, packages/backend/services/backend-service-game/src/cards/domain/models/ColoredCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/DrawCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/NormalCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/ReverseCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/SkipCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/WildCard.ts, packages/backend/services/backend-service-game/src/cards/domain/models/WildDraw4Card.ts, packages/backend/services/backend-service-game/src/games/domain/models/ActiveGame.ts, packages/backend/services/backend-service-game/src/games/domain/models/ActiveGameSlot.ts, packages/backend/services/backend-service-game/src/games/domain/models/BaseGame.ts, packages/backend/services/backend-service-game/src/games/domain/models/Game.ts, packages/backend/services/backend-service-game/src/games/domain/models/GameCardSpec.ts, packages/backend/services/backend-service-game/src/games/domain/models/NonStartedGame.ts, packages/backend/services/backend-service-game/src/games/domain/models/NonStartedGameSlot.ts
- Added `card` models.
- Added `game` models.
=> Add game models

packages/backend/services/backend-service-game/src/cards/adapter/typeorm/builders/CardDbBuilder.spec.ts, packages/backend/services/backend-service-game/src/cards/adapter/typeorm/builders/CardDbBuilder.ts, packages/backend/services/backend-service-game/src/cards/adapter/typeorm/models/CardDb.ts, packages/backend/services/backend-service-game/src/cards/adapter/typeorm/models/cardDbMasks.ts
- Added `CardDb`.
- Added `CardDbBuilder.
=> Add CardDbBuilder

packages/backend/services/backend-service-game/src/cards/adapter/typeorm/builders/CardBuilder.ts, packages/backend/services/backend-service-game/src/cards/adapter/typeorm/models/cardDbMasks.ts
=> Add card builder

packages/backend/services/backend-service-game/src/cards/adapter/typeorm/builders/CardColorDbBuilder.spec.ts, packages/backend/services/backend-service-game/src/cards/adapter/typeorm/builders/CardColorDbBuilder.ts, packages/backend/services/backend-service-game/src/cards/adapter/typeorm/models/CardColorDb.ts
=> Add CardColorDbBuilder

packages/backend/services/backend-service-game/.env.example, packages/backend/services/backend-service-game/docker.env, packages/backend/services/backend-service-game/docker.env.example, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-game/src/app/adapter/typeorm/migrations/1679232270610-AddGame.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/models/GameSlotDb.ts, packages/backend/services/backend-service-user/.env.example, packages/backend/services/backend-service-user/docker.env, packages/backend/services/backend-service-user/docker.env.example, packages/backend/services/backend-service-user/package.json
- Added `GameDb`.
- Added `GameSlotDb`.
=> Add game db entities

packages/api/libraries/api-models/src/scripts/generateApiJsonSchemasIdEnum.ts, packages/backend/libraries/backend-prettier-config/index.d.ts
- Updated `generateApiJsonSchemaIdEnum` script to format source code.
=> Update api schema to user formatter

packages/backend/services/backend-service-game/src/games/adapter/typeorm/adapters/GamePersistenceTypeOrmAdapter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/services/CreateGameTypeOrmService.ts, packages/backend/services/backend-service-game/src/games/application/ports/output/GamePersistenceOutputPort.ts
- Added `CreateGameTypeOrmService`.
- Added `GamePersistenceTypeOrmAdapter`.
- Update `GamePersistenceOutputPort.create` argument name.
=> Add game persistence typeorm adapter

packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameCreateQueryToGameCreateQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameCreateQueryToGameCreateQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameCreateQueryToGameSlotCreateQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameCreateQueryFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/query/GameCreateQuery.ts
- Updated `GameCreateQuery` with `spec` property.
=> Update GameCreateQuery with spec

packages/backend/services/backend-service-game/src/cards/application/converters/CardColorFromCardColorV1Builder.spec.ts, packages/backend/services/backend-service-game/src/cards/application/converters/CardColorFromCardColorV1Builder.ts, packages/backend/services/backend-service-game/src/cards/application/converters/CardFromCardV1Builder.spec.ts, packages/backend/services/backend-service-game/src/cards/application/converters/CardFromCardV1Builder.ts, packages/backend/services/backend-service-game/src/cards/application/converters/GameCardSpecFromGameCardSpecV1Builder.spec.ts, packages/backend/services/backend-service-game/src/cards/application/converters/GameCardSpecFromGameCardSpecV1Builder.ts, packages/backend/services/backend-service-game/src/cards/application/fixtures/CardV1Fixtures.ts, packages/backend/services/backend-service-game/src/cards/application/fixtures/GameCardSpecV1Fixtures.ts, packages/backend/services/backend-service-game/src/cards/application/fixtures/GameCreateQueryV1Fixtures.ts, packages/backend/services/backend-service-game/src/cards/application/fixtures/GameSpecV1Fixtures.ts, packages/backend/services/backend-service-game/src/foundation/common/application/models/UuidContext.ts, packages/backend/services/backend-service-game/src/games/application/converters/GameCardSpecsFromGameSpecV1Builder.spec.ts, packages/backend/services/backend-service-game/src/games/application/converters/GameCardSpecsFromGameSpecV1Builder.ts, packages/backend/services/backend-service-game/src/games/application/converters/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/services/backend-service-game/src/games/application/converters/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/services/backend-service-game/src/games/application/models/GameCreateQueryContext.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameCardSpecFixtures.ts
- Added `UuidContext`.
- Added `CardColorFromCardColorV1Builder`.
- Added `CardFromCardV1Builder`.
- Added `GameCardSpecFromGameCardSpecV1Builder`.
- Added `GameCardSpecsFromGameSpecV1Builder`.
- Added `GameCreateQueryFromGameCreateQueryV1Builder`.
=> Add GameCreateQueryFromGameCreateQueryV1Builder

packages/backend/services/backend-service-game/src/games/application/builders/GameDirectionV1FromGameDirectionBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameDirectionV1FromGameDirectionBuilder.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/ActiveGameFixtures.ts
- Added `GameDirectionV1FromGameDirectionBuilder`.
- Added `GameV1FromGameBuilder`.
=> Add GameV1FromGameBuilder

packages/backend/services/backend-service-game/src/games/application/controllers/PostGameV1HttpRequestController.ts, packages/backend/services/backend-service-game/src/games/application/handlers/PostGameV1RequestParamHandler.spec.ts, packages/backend/services/backend-service-game/src/games/application/handlers/PostGameV1RequestParamHandler.ts
- Added `PostGameV1RequestParamHandler`.
- Added `PostGameV1HttpRequestController`.
=> Add post game v1 request controller

packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/PostGameV1HttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameCreateQueryToGameSlotCreateQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameCreateQueryToGameSlotCreateQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/models/GameSlotDb.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/services/CreateGameTypeOrmService.ts
- Added `GameHttpApiModule`.
- Added `PostGameV1HttpRequestNestController`.
- Updated `GameModule` with missing providers.
- Updated `CreateGameTypeOrmService` to create game slots.
- Updated `GameCreateQueryToGameSlotCreateQueryTypeOrmConverter`.
- Updated `GameDb` and `GameSlotDb` with appropiate relation decorators.
=> Add PostGameV1HttpRequestNestController

packages/backend/libraries/backend-http/CHANGELOG.md, packages/backend/libraries/backend-http/src/auth/application/models/Auth.ts, packages/backend/libraries/backend-http/src/auth/application/models/AuthKind.ts, packages/backend/libraries/backend-http/src/auth/application/models/AuthRequestContext.ts, packages/backend/libraries/backend-http/src/auth/application/models/AuthRequestContextHolder.ts, packages/backend/libraries/backend-http/src/auth/application/models/BackendServiceAuth.ts, packages/backend/libraries/backend-http/src/auth/application/models/BaseAuth.ts, packages/backend/libraries/backend-http/src/auth/application/models/UserAuth.ts, packages/backend/libraries/backend-http/src/index.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.spec.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.ts, packages/backend/libraries/backend-http/src/user/application/models/RequestUserContextHolder.ts, packages/backend/libraries/backend-http/src/user/application/models/UserV1RequestContext.ts, packages/backend/services/backend-service-game/.env.example, packages/backend/services/backend-service-game/src/foundation/env/application/models/Environment.ts, packages/backend/services/backend-service-game/src/foundation/env/application/models/EnvironmentRaw.ts, packages/backend/services/backend-service-game/src/foundation/env/application/services/EnvironmentLoader.ts, packages/backend/services/backend-service-user/.env.example, packages/backend/services/backend-service-user/src/auth/adapters/nest/modules/AuthModule.ts, packages/backend/services/backend-service-user/src/auth/application/middlewares/AuthMiddleware.ts, packages/backend/services/backend-service-user/src/foundation/env/application/models/Environment.ts, packages/backend/services/backend-service-user/src/foundation/env/application/models/EnvironmentRaw.ts, packages/backend/services/backend-service-user/src/foundation/env/application/services/EnvironmentLoader.ts
- Added Auth models in favor of old user context ones.
- Added apiBackendServiceSecret env.
- Added apiBaseUrl env.
- Updated AuthMiddleware to handle backend service auth.
=> Add backend service auth

packages/api/libraries/api-http-client/CHANGELOG.md, packages/api/libraries/api-http-client/src/index.ts, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-game/src/user/application/fixtures/models/UserV1Fixtures.ts, packages/backend/services/backend-service-game/src/user/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/user/application/ports/input/UserManagementInputPort.ts
- Added `UserManagementInputPort`.
- Updated `Response` to be exposed.
=> Add UserManagementInputPort

packages/api/libraries/api-http-client/package.json, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-json-schemas/schemas/v1/games/active-game.json, packages/api/libraries/api-json-schemas/schemas/v1/games/game-id-slot-create-query.json, packages/api/libraries/api-json-schemas/schemas/v1/games/non-started-game.json, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-models/CHANGELOG.md, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/application/builders/ActiveGameSlotV1FromActiveGameBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/ActiveGameSlotV1FromActiveGameSlotBuilder.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/services/backend-service-game/src/games/application/builders/NonStartedGameSlotV1FromNonStartedGameSlotBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/NonStartedGameSlotV1FromNonStartedGameSlotBuilder.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/ActiveGameSlotV1Fixtures.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/ActiveGameV1Fixtures.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/NonStartedGameSlotV1Fixtures.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/NonStartedGameV1Fixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/NonStartedGameFixtures.ts
- Replaced game slot update endpoint with game slot create endpoint.
- Replaced game slot endpoint with game slot properties.
=> API breaking changes

packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotCreateQueryToGameSlotCreateQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotCreateQueryToGameSlotCreateQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/services/CreateGameSlotTypeOrmService.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameSlotCreateQueryFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/query/GameSlotCreateQuery.ts
- Added `GameSlotCreateQuery`.
- Added `GameSlotCreateQueryToGameSlotCreateQueryTypeOrmConverter`.
- Added `CreateGameSlotTypeOrmService`.
=> Add GameSlotCreateQuery

packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotDbToGameSlotConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotDbToGameSlotConverter.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/ActiveGameSlotFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/NonStartedGameFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/NonStartedGameSlotFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/models/ActiveGameSlot.ts, packages/backend/services/backend-service-game/src/games/domain/models/BaseGameSlot.ts, packages/backend/services/backend-service-game/src/games/domain/models/NonStartedGameSlot.ts
- Updated `NonStartedGameSlot` and `ActiveGameSlot` to extend a `BaseGameSlot` with a `position` field.
=> Update GameSlot with position

packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/fixtures/GameDbFixtures.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/fixtures/GameSlotDbFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/NonStartedGameSlotFixtures.ts
- Updated `GameDbToGameConverter` to sort game slots.
=> Update GameDbToGameConverter to sort game slots

packages/backend/services/backend-service-game/src/games/adapter/typeorm/adapters/GameSlotPersistenceTypeOrmAdapter.ts, packages/backend/services/backend-service-game/src/games/application/ports/output/GameSlotPersistenceOutputPort.ts
- Added `GameSlotPersistenceOutputPort`.
=> Add GameSlotPersistenceOutputPort

packages/backend/services/backend-service-game/src/games/application/builders/GameSlotCreateQueryFromGameSlotCreateQueryV1Builder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameSlotCreateQueryFromGameSlotCreateQueryV1Builder.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameSlotV1FromGameSlotBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameSlotV1FromGameSlotBuilder.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/GameSlotCreateQueryContextFixtures.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/GameSlotCreateV1Fixtures.ts, packages/backend/services/backend-service-game/src/games/application/models/GameSlotCreateQueryContext.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameManagementInputPort.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.ts
- Added `GameSlotManagementInputPort`.
- Added `GameSlotV1FromGameSlotBuilder`.
- Added `GameSlotCreateQueryFromGameSlotCreateQueryV1Builder`.
- Updated `GameManagementInputPort` without unused method.
=> Add game slot management input port

packages/backend/libraries/backend-db/src/persistence/converters/typeorm/QueryToFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/adapters/GamePersistenceTypeOrmAdapter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/services/FindGameTypeOrmService.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/output/GamePersistenceOutputPort.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameFindQueryFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/query/GameFindQuery.ts
- Added `FindGameTypeOrmService`.
- Added `GameFindQueryToGameFindQueryTypeOrmConverter`.
- Updated `GameModule` with missing providers.
- Updated `GamePersistencePort` with `findOne`.
=> Update game persistence port with find one

packages/backend/libraries/backend-common/src/error/application/models/AppErrorKind.ts, packages/backend/libraries/backend-http/src/http/application/builders/ErrorV1ResponseFromErrorBuilder.ts, packages/backend/services/backend-service-game/src/games/application/middlewares/GameMiddleware.spec.ts, packages/backend/services/backend-service-game/src/games/application/middlewares/GameMiddleware.ts, packages/backend/services/backend-service-game/src/games/application/models/GameRequestContext.ts, packages/backend/services/backend-service-game/src/games/application/models/GameRequestContextHolder.ts
- Added `GameRequestContext`.
- Added `GameMiddleware`.
- Updated `AppErrorKind` with `entityNotFound`.
=> Add game middleware

packages/backend/services/backend-service-game/src/app/adapter/typeorm/migrations/1679232270610-AddGame.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/PostGameIdSlotV1HttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotCreateQueryToGameSlotCreateQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotCreateQueryToGameSlotCreateQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/models/GameSlotDb.ts, packages/backend/services/backend-service-game/src/games/application/controllers/PostGameIdSlotV1HttpRequestController.ts
- Added `PostGameV1HttpRequestController`.
- Added `PostGameIdSlotV1HttpRequestNestController`.
- Updated `GameSlotCreateQueryToGameSlotCreateQueryTypeOrmConverter` with right insert query.
- Updated `GameSlotDb` with missing unique constraint.
=> Add post game slot controller

packages/backend/libraries/backend-common/CHANGELOG.md, packages/backend/libraries/backend-common/src/common/domain/modules/Spec.ts, packages/backend/libraries/backend-common/src/index.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/NonStartedGameFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/specs/GameCanHoldMoreGameSlotsSpec.spec.ts, packages/backend/services/backend-service-game/src/games/domain/specs/GameCanHoldMoreGameSlotsSpec.ts
- Added `Spec`.
- Added `GameCanHoldMoreGameSlotsSpec`.
- Updated `GameSlotManagementInputPort` to rely on `GameCanHoldMoreGameSlotsSpec`.
=> Fix game slot create flow with business spec

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/services/backend-service-user/src/user/adapter/nest/controllers/GetUserV1MeHttpRequestNestController.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts, packages/backend/services/backend-service-user/src/user/application/controllers/GetUserV1MeHttpRequestController.ts, packages/backend/services/backend-service-user/src/user/application/handlers/GetUserV1MeRequestParamHandler.spec.ts, packages/backend/services/backend-service-user/src/user/application/handlers/GetUserV1MeRequestParamHandler.ts
- Added `GetUserV1MeHttpRequestNestController`.
- Added `GetUserV1MeHttpRequestController`.
- Added `GetUserV1MeRequestParamHandler`.
=> Feature: Get /users/me

packages/backend/services/backend-service-game/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameManagementInputPort.ts
- Updated `GameManagementInputPort` with `findOne`.
=> Update GameManagementInputPort with findOne

packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGameV1GameIdHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/services/backend-service-game/src/games/application/controllers/GetGameV1GameIdHttpRequestController.ts, packages/backend/services/backend-service-game/src/games/application/handlers/GetGameV1GameIdRequestParamHandler.ts, packages/backend/services/backend-service-game/src/games/application/handlers/GetUserV1UserIdRequestParamHandler.spec.ts
- Added `GetGameV1GameIdRequestParamHandler`.
- Added `GetGameV1GameIdHttpRequestController`.
- Added `GetGameV1GameIdHttpRequestNestController`.
=> Add get game v1

packages/backend/libraries/backend-jwt/src/jwt/adapter/jsonwebtoken/services/JsonWebTokenService.ts
- Updated `JsonWebTokenService` to handle errors.
=> Update JsonWebTokenService to handle errors

packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.ts
- Added `GameSlotManagementInputPort`.
=> Add GameSlotManagementInputPort

packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameCardSpecFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/NonStartedGameFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/models/GameInitialDraws.ts, packages/backend/services/backend-service-game/src/games/domain/services/GameService.spec.ts, packages/backend/services/backend-service-game/src/games/domain/services/GameService.ts
- Added `GameService`.
- Added `GameInitialDraws`.
=> Add GameInitialDraws

packages/backend/services/backend-service-game/src/games/adapter/typeorm/adapters/GamePersistenceTypeOrmAdapter.ts, packages/backend/services/backend-service-game/src/games/application/middlewares/GameMiddleware.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/output/GamePersistenceOutputPort.ts
- Updated `GamePersistenceOutputPort` with `update`.
=> Update GamePersistenceOutputPort with update

packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotFindQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotSetQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotSetQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/services/UpdateGameSlotTypeOrmService.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameSlotFindQueryFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameSlotUpdateQueryFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/query/GameSlotFindQuery.ts, packages/backend/services/backend-service-game/src/games/domain/query/GameSlotUpdateQuery.ts
- Added `GameSlotUpdateQueryToGameSlotSetQueryTypeOrmConverter`.
- Added `GameSlotUpdateQueryToGameSlotFindQueryTypeOrmConverter`.
- Added `GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter`.
- Added `GameSlotUpdateService`.
=> Add GameSlotUpdateService

packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/NonStartedGameFilledEventFixtures.ts, packages/backend/services/backend-service-game/src/games/application/handlers/NonStartedGameFilledEventHandler.spec.ts, packages/backend/services/backend-service-game/src/games/application/handlers/NonStartedGameFilledEventHandler.ts, packages/backend/services/backend-service-game/src/games/domain/events/NonStartedGameFilledEvent.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameSlotFindQueryFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/query/GameSlotFindQuery.ts, packages/backend/services/backend-service-game/src/games/domain/services/GameService.spec.ts, packages/backend/services/backend-service-game/src/games/domain/services/GameService.ts
- Added `NonStartedGameFilledEventHandler`.
- Updated `GameService` with additional methods.
- Updated `GameSlotFindQuery` with `gameId` and `position`.
=> Add NonStartedGameFilledEventHandler

packages/api/libraries/api-json-schemas/schemas/v1/games/active-game.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/services/backend-service-game/src/app/adapter/typeorm/migrations/1679232270610-AddGame.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameUpdateQueryToGameSetQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/converters/GameUpdateQueryToGameSetQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/fixtures/GameDbFixtures.ts, packages/backend/services/backend-service-game/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/services/backend-service-game/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/services/backend-service-game/src/games/application/fixtures/ActiveGameV1Fixtures.ts, packages/backend/services/backend-service-game/src/games/application/handlers/NonStartedGameFilledEventHandler.spec.ts, packages/backend/services/backend-service-game/src/games/application/handlers/NonStartedGameFilledEventHandler.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/fixtures/GameUpdateQueryFixtures.ts, packages/backend/services/backend-service-game/src/games/domain/models/ActiveGame.ts, packages/backend/services/backend-service-game/src/games/domain/query/GameUpdateQuery.ts, packages/backend/services/backend-service-game/src/games/domain/services/GameService.spec.ts, packages/backend/services/backend-service-game/src/games/domain/services/GameService.ts
- Updated `GameDb` with `drawCounter`.
- Updated `ActiveGame` with `drawCounter`.
- Updated `ActiveGameV1` with `drawCounter`.
=> Update GameDb with drawCounter

packages/api/libraries/api-http-client/tsconfig.json, packages/api/libraries/api-json-schemas-provider/tsconfig.json, packages/api/libraries/api-models/tsconfig.json, packages/api/libraries/api-openapi-schema/tsconfig.json, packages/backend/libraries/backend-api-validators/tsconfig.json, packages/backend/libraries/backend-common/tsconfig.json, packages/backend/libraries/backend-db/tsconfig.json, packages/backend/libraries/backend-env/tsconfig.json, packages/backend/libraries/backend-http/tsconfig.json, packages/backend/libraries/backend-jwt/tsconfig.json, packages/backend/services/backend-service-game/tsconfig.json, packages/backend/services/backend-service-user/tsconfig.json, packages/backend/tools/backend-typescript-config/tsconfig.base.cjs.json, packages/backend/tools/backend-typescript-config/tsconfig.base.esm.json, packages/backend/tools/backend-typescript-config/tsconfig.base.json, packages/tools/json-schema-utils/tsconfig.json, packages/tools/openapi-utils/tsconfig.json
- Added `cjs` base tsc config.
- Added `esm` base tsc config.
- Updated tsc config files to rely on `cjs` base tsc config one.
=> Update tsconfig files with both cjs and esm base configs

packages/api/libraries/api-http-client/package.json, packages/api/libraries/api-http-client/tsconfig.cjs.json, packages/api/libraries/api-http-client/tsconfig.esm.json, packages/backend/libraries/backend-scripts/LICENSE, packages/backend/libraries/backend-scripts/bin/writeCommonJsPackageJson.js, packages/backend/libraries/backend-scripts/bin/writeEsmPackageJson.js, packages/backend/libraries/backend-scripts/package.json, packages/backend/tools/backend-dev-proxy/package.json
- Added package json write scripts
- Updad `api-http-client` to be an hybrid package.
- Updated `backend-dev-proxy` package with missing name.
=> Update http client to be an hybrid package

packages/backend/libraries/backend-common/CHANGELOG.md, packages/backend/libraries/backend-common/src/common/application/models/Writable.ts, packages/backend/libraries/backend-common/src/index.ts
=> Add Writable

packages/backend/apps/user/backend-app-user-db/package.json, packages/backend/apps/user/backend-app-user-db/src/entities.ts, packages/backend/apps/user/backend-app-user-db/src/foundation/db/adapter/nest/models/DbModuleOptions.ts
- Updated `backend-app-user-db` with multiple export aliases.
=> Update backend-app-user-db with multiple export aliases

packages/backend/apps/game/backend-app-game-fixtures/package.json, packages/backend/apps/game/backend-app-game-fixtures/src/cards/application/fixtures/CardV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/cards/application/fixtures/GameCardSpecV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/cards/application/fixtures/GameCreateQueryV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/cards/application/fixtures/GameSpecV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/cards/application/index.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/application/fixtures/ActiveGameSlotV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/application/fixtures/ActiveGameV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/application/fixtures/GameSlotCreateV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/application/fixtures/NonStartedGameSlotV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/application/fixtures/NonStartedGameV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/application/index.ts, packages/backend/apps/game/backend-app-game-fixtures/src/users/application/fixtures/models/UserV1Fixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/users/application/index.ts, turbo.json
- Added application fixtures `backend-app-game-fixtures`.
=> Update backend-app-game-fixtures with application fixtures

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-json-schemas/CHANGELOG.md, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-json-schemas/schemas/v1/users/user-me-update-query.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml
- Updated user update endpoint to be a `/me` one.
=> Update user update endpoint docs

packages/backend/apps/user/backend-app-user/src/user/adapter/nest/modules/UserModule.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserCreateQueryConverterFromUserCreateQueryV1Builder.spec.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserCreateQueryConverterFromUserCreateQueryV1Builder.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserV1FromUserBuilder.spec.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserV1FromUserBuilder.ts, packages/backend/apps/user/backend-app-user/src/user/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-app-user/src/user/application/ports/input/UserManagementInputPort.ts
- Removed `converters` in favor `builders`.
=> [backend-app-user] Remove converters in favor of builders

packages/backend/apps/user/backend-app-user/src/user/adapter/nest/modules/UserModule.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserCreateQueryFromUserCreateQueryV1Builder.spec.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserCreateQueryFromUserCreateQueryV1Builder.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserUpdateQueryFromUserMeUpdateQueryV1Builder.spec.ts, packages/backend/apps/user/backend-app-user/src/user/application/converters/UserUpdateQueryFromUserMeUpdateQueryV1Builder.ts, packages/backend/apps/user/backend-app-user/src/user/application/fixtures/UserMeUpdateQueryV1Fixtures.ts, packages/backend/apps/user/backend-app-user/src/user/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-app-user/src/user/application/ports/input/UserManagementInputPort.ts
- Added `UserUpdateQueryFromUserUpdateQueryV1Builder`.
- Updated `UserManagementInputPort` with `updateMe`.
=> Update user management input port

packages/backend/apps/user/backend-app-user-db/src/user/adapter/typeorm/converters/UserUpdateQueryToUserFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/controllers/PatchUserV1MeHttpRequestNestController.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts
- Added `PatchUserV1MeHttpRequestNestController`.
- Updated `UserUpdateQueryToUserFindQueryTypeOrmConverter` with missing injection.
=> Add patch user me endpoint

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml
- Updated `PATCH /users/me` endpoint docs to return a 204 response code.
=> Update patch user me with right response code

packages/backend/apps/game/backend-app-game-db/src/games/adapter/typeorm/converters/GameCreateQueryToGameCreateQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-app-game-db/src/games/adapter/typeorm/converters/GameCreateQueryToGameCreateQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-app-game-db/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/apps/game/backend-app-game-db/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/domain/fixtures/GameCreateQueryFixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/domain/fixtures/NonStartedGameFixtures.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/ActiveGame.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/ActiveGameState.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/BaseGame.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/GameSpec.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/GameState.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/NonStartedGame.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/NonStartedGameState.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/query/GameCreateQuery.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameSlotCreateQueryFromGameSlotCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameSlotCreateQueryFromGameSlotCreateQueryV1Builder.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/apps/game/backend-app-game/src/games/application/ports/input/GameSlotManagementInputPort.spec.ts, packages/backend/apps/game/backend-app-game/src/games/application/ports/input/GameSlotManagementInputPort.ts, packages/backend/apps/game/backend-app-game/src/games/domain/specs/GameCanHoldMoreGameSlotsSpec.ts, packages/backend/apps/game/backend-app-game/src/games/domain/specs/GameCanHoldOnlyOneMoreGameSlotSpec.ts
- Added `GameState`.
- Added `GameSpec`.
- Updated `BaseGame` with state and spec.
=> Update game data structure

package.json, packages/backend/apps/game/backend-app-game-db/package.json, packages/backend/apps/game/backend-app-game/package.json, packages/backend/apps/user/backend-app-user-db/package.json, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-user/package.json
- Updated fixtures packages dependencies.
=> Update fixtures packages depedencies

packages/backend/apps/game/backend-app-game-db/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/apps/game/backend-app-game-db/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-app-game-fixtures/src/games/domain/fixtures/NonStartedGameFixtures.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/ActiveGameState.ts, packages/backend/apps/game/backend-app-game-models/src/games/domain/models/BaseGame.ts, packages/backend/apps/game/backend-app-game/src/games/application/handlers/NonStartedGameFilledEventHandler.spec.ts, packages/backend/apps/game/backend-app-game/src/games/application/handlers/NonStartedGameFilledEventHandler.ts, packages/backend/apps/game/backend-app-game/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-app-game/src/games/domain/services/GameService.ts, packages/backend/services/backend-service-game/src/games/application/controllers/PostGameIdSlotV1HttpRequestController.ts, packages/backend/services/backend-service-game/src/games/application/handlers/PostGameIdSlotV1RequestParamHandler.spec.ts, packages/backend/services/backend-service-game/src/games/application/handlers/PostGameIdSlotV1RequestParamHandler.ts
- Updated `PostGameIdSlotV1HttpRequestController` to avoid users impersonating other ones.
- Updated `BaseGame` without deck in favor of active game state decks.
=> Update non started game with no deck

packages/api/libraries/api-json-schemas/schemas/v1/games/game-create-query.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-app-game-fixtures/src/cards/application/fixtures/GameCreateQueryV1Fixtures.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-app-game/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/apps/game/backend-app-game/src/games/domain/services/GameService.ts
- Updated `GameCreateQueryV1` without `gameSpec`.
=> Update GameCreateQueryV1 without gameSpec

packages/backend/tools/backend-test-e2e/features/games/createGameSlot.feature, packages/backend/tools/backend-test-e2e/src/app/adapter/cucumber/hooks/before.ts, packages/backend/tools/backend-test-e2e/src/auth/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/auth/step-definitions/thenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/auth/step-definitions/whenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/thenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/whenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/http/models/OneGameApiWorld.ts, packages/backend/tools/backend-test-e2e/src/http/utils/actions/initializeWorld.ts, packages/backend/tools/backend-test-e2e/src/http/utils/actions/sendRequest.ts, packages/backend/tools/backend-test-e2e/src/http/utils/actions/setPendingResponse.ts, packages/backend/tools/backend-test-e2e/src/http/utils/actions/setRequestParameters.ts, packages/backend/tools/backend-test-e2e/src/http/utils/calculations/getResponseOrFail.ts, packages/backend/tools/backend-test-e2e/src/user/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/user/step-definitions/thenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/user/step-definitions/whenDefinitions.ts
- Updated create game slot feature with additional case.
- Updated request related e2e steps to wait for responses.
=> Update e2e request steps to wait for response

packages/api/libraries/api-json-schemas/schemas/v1/games/game-options.json, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts
=> Add GameOptionsV1

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameOptionsCreateQueryFromGameOptionsV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameOptionsCreateQueryFromGameOptionsV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSlotCreateQueryFromGameSlotCreateQueryV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSlotV1FromGameSlotBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameOptionsCreateQueryContextFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameOptionsV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameOptionsCreateQueryContext.ts
- Added `GameOptionsCreateQueryFromGameOptionsV1Builder`.
=> Add GameOptionsCreateQueryFromGameOptionsV1Builder

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameOptionsV1FromGameOptionsBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameOptionsV1FromGameOptionsBuilder.ts
- Added `GameOptionsV1FromGameOptionsBuilder`.
=> Add GameOptionsV1FromGameOptionsBuilder

packages/api/libraries/api-json-schemas/schemas/v1/games/game-create-query.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/nest/modules/GameDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GameOptionsPersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameOptionsCreateQueryFromGameOptionsV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameOptionsCreateQueryFromGameOptionsV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameCreateQueryContextFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameCreateQueryV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameCreatedEventFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameOptionsCreateQueryContextFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameCreatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameCreatedEventHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameCreateQueryContext.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameCreatedEvent.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameOptionsCreateQueryContext.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameSpecCreateQuery.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/givenDefinitions.ts
- Added `GameCreatedEventHandler`.
- Added `GameCreatedEvent`.
- Added `GameCreateQueryContext`.
- Updated `GameCreateQuery` with spec options.
- Updated `GameManagementInputPort` to trigger a `GameCreatedEvent`.
=> Update game creation flow with game options creation

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameOptionsManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameOptionsManagementInputPort.ts
- Added `GameOptionsManagementInputPort`.
=> Add GameOptionsManagementInputPort

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameV1GameIdGameOptionsHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameOptionsManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameOptionsManagementInputPort.ts
- Added `GetGameV1GameIdGameOptionsHttpRequestController`.
=> Add GetGameV1GameIdGameOptionsHttpRequestController

packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGameV1GameIdGameOptionsHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GetGameV1GameIdGameOptionsHttpRequestNestController`.
=> Add GetGameV1GameIdGameOptionsHttpRequestNestController

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml
- Added `GET /games/:gameId/options` endpoint.
=> Add get game game id options endpoint

packages/backend/apps/game/backend-game-domain/src/cards/domain/fixtures/CardFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameOptionsFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/IsCardPlayableSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/IsCardPlayableSpec.ts
=> Add IsCardPlayableSpec

.husky/commit-msg, config/commitlint/commitlint.config.js, package.json
- Added commitlint dependencies.
- Added commitlint config
- Added `pre-commit` git hook.
=> Add commitlint integration

packages/backend/tools/backend-test-e2e/config/cucumber.js.config.mjs, packages/backend/tools/backend-test-e2e/config/cucumber.ts.config.mjs, packages/backend/tools/backend-test-e2e/features/games/updateGame.feature, packages/backend/tools/backend-test-e2e/src/foundation/adapter/cucumberJs/parameters/stringList.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/thenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/whenDefinitions.ts
- Added `stringList` parameter.
- Added PATCH game game id e2e test for pass turn queries.
=> Add patch game e2e tests

packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameV1GameIdHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.ts
- Updated `GameManagementInputPort.findOne` to receive a `GameFindQuery`.
=> Update GameManagementInputPort.findOne to receive a GameFindQuery

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GamePersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GamePersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-application/src/games/application/middlewares/GameMiddleware.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GamePersistenceOutputPort.ts
- Updated `GamePersistenceTypeOrmAdapter`with `find`.
- Updated `GamePersistenceOutputPort`with `find`.
- Updated `GamePersistenceInputPort`with `find`.
=> Update game management input port with find

packages/backend/services/backend-service-game/src/app/adapter/nest/scripts/runPendingMigrations.ts
- Update `runPendingMigrations` with retry policy.
=> Update runPendingMigrations with retry policy

packages/api/libraries/api-http-client/src/httpClient/axios/AxiosHttpClient.ts, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-http-client/src/typescript/builders/HttpClientMethodsBuilder.ts, packages/api/libraries/api-json-schemas/schemas/v1/games/game-array.json, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/tools/backend-test-e2e/src/http/utils/actions/setPendingResponse.ts
- Added `GET /v1/games/mine` endpoint models.
- Updated http client generation flow to correctly generate query parameters.
=> Add get games mine endpoint models

packages/backend/apps/game/backend-game-application/src/foundation/http/adapter/nest/modules/HttpModule.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdSlotSlotIdCardsV1RequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameV1GameIdGameOptionsHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameV1GameIdHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameV1MineHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/PatchGameV1GameIdHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/PostGameIdSlotV1HttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/PostGameV1HttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameV1MineRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameV1MineRequestParamHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/libraries/backend-http/src/http/application/builders/MultipleEntitiesGetResponseBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/builders/MultipleEntitiesGetResponseBuilder.ts, packages/backend/libraries/backend-http/src/http/application/controllers/HttpRequestController.spec.ts, packages/backend/libraries/backend-http/src/http/application/controllers/HttpRequestController.ts, packages/backend/libraries/backend-http/src/index.ts, packages/backend/services/backend-service-user/src/auth/application/controllers/PostAuthV1HttpRequestController.ts, packages/backend/services/backend-service-user/src/user/application/controllers/GetUserV1MeHttpRequestController.ts, packages/backend/services/backend-service-user/src/user/application/controllers/GetUserV1UserIdHttpRequestController.ts, packages/backend/services/backend-service-user/src/user/application/controllers/PatchUserV1MeHttpRequestController.ts, packages/backend/services/backend-service-user/src/user/application/controllers/PostUserV1HttpRequestController.ts
- Added `MultipleEntitiesGetResponseBuilder`.
- Added `GetGameV1MineHttpRequestController`.
- Added `GetGameV1MineRequestParamHandler`.
- Updated `SingleEntityHttpRequestController` to be a general purpose http controller.
=> Add get game v1 mine request controller

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGameV1MineHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GetGameV1MineHttpRequestNestController`.
- Updated `GameFindQueryToGameFindQueryTypeOrmConverter` with missing injection and right subquery.
=> Add get games mine nest controller

packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/DeleteUserTypeOrmService.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/output/UserPersistenceOutputPort.ts
- Added `DeleteUserTypeOrmService`.
- Updated `UserPersistenceOutputPort` with `delete`.
- Updated `UserPersistenceTypeOrmAdapter` with `delete`.
=> Update user persistence output port with delete

packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/nest/UserDbModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.ts
- Updated `UserManagementInputPort` with `delete`.
=> Update UserManagementInputPort with delete

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/user/backend-user-application/src/users/application/index.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/controllers/DeleteUserV1MeHttpRequestNestController.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts
- Added `DeleteUserV1MeHttpRequestNestController`.
- Updated docs with `DELETE /v1/users/me`.
=> Add delete user me endpoint

packages/backend/tools/backend-maildev/docker-compose.yml, packages/backend/tools/backend-maildev/docker/maildev.Dockerfile, packages/backend/tools/backend-maildev/package.json
- Added `backend-maildev-package`.
=> Add backend maildev package

packages/backend/apps/user/backend-user-adapter-typeorm/src/app/adapter/typeorm/migrations/1678229103157-AddUserModel.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/entities.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/nest/models/entities.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/fixtures/UserCodeDbFixtures.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/models/UserCodeDb.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserCodeFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/models/UserCode.ts
- Added `UserCode`.
- Added `UserCodeDb`.
=> Add UserCode

packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/nest/UserDbModule.ts, packages/backend/apps/user/backend-user-application/src/foundation/string/adapter/nest/StringModule.ts, packages/backend/apps/user/backend-user-application/src/foundation/string/application/builders/RandomHexStringBuilder.int.spec.ts, packages/backend/apps/user/backend-user-application/src/foundation/string/application/builders/RandomHexStringBuilder.ts, packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.ts, packages/backend/apps/user/backend-user-domain/src/users/adapter/nest/UserDomainModule.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/specs/UserCanCreateCodeSpec.spec.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/specs/UserCanCreateCodeSpec.ts
- Added `UserCodeManagementInputPort`.
- Added `RandomHexStringBuilder`.
- Added `UserCanCreateCodeSpec`.
=> Add user code management input port

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserHttpApiModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/DeleteUserV1EmailCodeRequestController.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/PostUserV1EmailCodeRequestController.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/BaseUserV1EmailCodeRequestParamHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/DeleteUserV1EmailCodeRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/DeleteUserV1EmailCodeRequestParamHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PostUserV1EmailCodeRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PostUserV1EmailCodeRequestParamHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/index.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/controllers/DeleteUserV1EmailCodeRequestNestController.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/controllers/PostUserV1EmailCodeRequestNestController.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts
- Added `PostUserV1EmailCodeRequestNestController`.
- Added `DeleteUserV1EmailCodeRequestNestController`.
- Added `PostUserV1EmailCodeRequestController`.
- Added `DeleteUserV1EmailCodeRequestController`.
- Added `PostUserV1EmailCodeRequestParamHandler`.
- Added `DeleteUserV1EmailCodeRequestParamHandler`.
- Added `BaseUserV1EmailCodeRequestParamHandler`.
Updated `UserHttpApiModule` with user code controllers.
=> Add user code endpoints

packages/backend/apps/user/backend-app-user-env/src/index.ts, packages/backend/apps/user/backend-user-application/package.json, packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/builders/UserActivationMailDeliveryOptionsFromUserBuilder.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/builders/UserActivationMailDeliveryOptionsFromUserBuilder.ts
- Added `UserActivationMailDeliveryOptionsFromUserBuilder`.
=> Add UserActivationMailDeliveryOptionsFromUserBuilder

packages/backend/apps/common/backend-adapter-nodemailer/src/index.ts, packages/backend/apps/common/backend-adapter-nodemailer/src/mail/adapter/nest/models/MailModuleOptions.ts, packages/backend/apps/common/backend-adapter-nodemailer/src/mail/adapter/nest/modules/MailModule.ts, packages/backend/apps/common/backend-adapter-nodemailer/src/mail/adapter/nodemailer/models/mailClientOptionsSymbol.ts, packages/backend/services/backend-service-user/package.json, packages/backend/services/backend-service-user/src/foundation/mail/adapter/nest/calculations/buildMailClientOptions.ts
- Added `MailModuleOptions`.
- Added `buildMailClientOptions`.
- Updated `MailModule` to receive `MailModuleOptions`.
=> Update backend service user with backend mail dependencies

packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/fixtures/UserCreatedEventFixtures.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UserCreatedEventHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UserCreatedEventHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/models/UserCreatedEvent.ts, packages/backend/services/backend-service-user/src/auth/adapters/nest/modules/AuthHttpApiModule.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts
- Added `UserCreatedEventHandler`.
- Added `UserCreatedEvent`.
=> Add UserCreatedEventHandler

packages/api/libraries/api-json-schemas/schemas/v1/users/user-me-update-query.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserUpdateQueryToUserSetQueryTypeOrmConverter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserUpdateQueryToUserSetQueryTypeOrmConverter.ts, packages/backend/apps/user/backend-user-application/src/users/application/converters/UserUpdateQueryFromUserMeUpdateQueryV1Builder.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/converters/UserUpdateQueryFromUserMeUpdateQueryV1Builder.ts, packages/backend/apps/user/backend-user-application/src/users/application/fixtures/UserMeUpdateQueryV1Fixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserUpdateQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/query/UserUpdateQuery.ts
- Updated `UserMeUpdateQueryV1` with `active` field.
- Updated `UseeUpdateQuery` with `active` field.
=> Update patch users me with active field

packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameOptionsFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/CardCanBePlayedSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/CardCanBePlayedSpec.ts
- Updated `CardCanBePlayedSpec` to verify `playWildDraw4IfNoOtherAlternative` rule.
=> Update CardCanBePlayedSpec to verify playWildDraw4IfNoOtherAlternative rule

packages/api/libraries/api-json-schemas/schemas/v1/games/game-id-play-cards-query.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameIdPlayCardsQueryV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/user/backend-user-application/src/users/application/data/userCodeLength.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UserCreatedEventHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.ts
- Updated `GameService.buildPlayCardsGameUpdateQuery` to correctly handle current color and direction.
- Moved user code length to be in a data module.
- Updated `GameIdPlayCardsQueryV1` with `colorChoice`.
=> Fix GameService to handle color and direction

packages/backend/apps/user/backend-user-domain/src/users/adapter/nest/UserDomainModule.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserUpdateQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/specs/IsValidUserCreateQuerySpec.spec.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/specs/IsValidUserUpdateQuerySpec.spec.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/specs/IsValidUserUpdateQuerySpec.ts
- Added `IsValidUserUpdateQuerySpec`.
=> Add IsValidUserUpdateQuerySpec

packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/CreateUserUseCaseHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UpdateUserUseCaseHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UpdateUserUseCaseHandler.ts
- Added `UpdateUserUseCaseHandler`.
=> Added UpdateUserUseCaseHandler

packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.ts
- Updated `UserManagementInputPort` to rely on use case handler.
=> Update UserManagementInputPort to rely on use case handler

docs/backend/architecture/application/introduction.md, docs/backend/architecture/application/patterns/controller.md, docs/backend/architecture/application/patterns/port.md, docs/backend/architecture/application/patterns/use-case-handler.md
- Add application layer docs overview.
=> Add backend architecture docs

docs/backend/architecture/introduction.md, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameStatusToGameStatusDbConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameStatusToGameStatusDbConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameStatusDb.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/GameStatus.ts
- Updated `GameStatus` with `finished`.
- Updated `GameStatusDb` with `finished`.
=> Update game status with finished

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotDbToGameSlotConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotDbToGameSlotConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/fixtures/GameDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/fixtures/GameSlotDbFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/NonStartedGameFilledEventHandler.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/entities/FinishedGame.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/entities/Game.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/FinishedGameSlotFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/FinishedGameSlot.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/FinishedGameState.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/GameState.ts, packages/backend/tools/eslint-config-backend/index.js
- Updated `Game` with `FinishedGame`.
=> Add finished game

packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameSlotFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/IsGameFinishedSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/IsGameFinishedSpec.ts
- Added `IsGameFinishedSpec`.
- Updated `GameService` to finish won games.
=> Update game service to finish won games

packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameCardSpecFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameDrawMutationFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameDrawService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameDrawService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/GameDrawMutation.ts
- Added `GameDrawMutation`.
- Added `GameDrawService`.
- Updated `GameService` to rely on `GameDrawService`.
=> Extract GameDrawService

packages/backend/tools/backend-dev-redis-pub-sub/LICENSE, packages/backend/tools/backend-dev-redis-pub-sub/docker-compose.yml, packages/backend/tools/backend-dev-redis-pub-sub/package.json
- Added dev redis Pub / Sub service.
=> Add dev redis pub sub service

docs/backend/setup.md, packages/backend/tools/backend-dev-proxy/.gitignore, packages/backend/tools/backend-dev-proxy/config/conf.d/locations.conf, packages/backend/tools/backend-dev-proxy/config/nginx.conf, packages/backend/tools/backend-dev-proxy/docker-compose.yml
- Updated dev proxy config with HTTP2 server.
- Updated backend docs to set up dev proxy certificate.
=> Update dev proxy with https 2 server

packages/backend/libraries/backend-http/src/http/application/builders/ErrorV1ResponseFromErrorBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/JsonResponseBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/MultipleEntitiesGetResponseBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/ResponseBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityDeleteResponseBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityDeleteResponseBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityGetResponseBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityGetResponseBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityPatchResponseBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityPatchResponseBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityPostResponseBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/builders/SingleEntityPostResponseBuilder.ts, packages/backend/tools/backend-dev-proxy/templates/http-game-service-game-redirection.conf.template, packages/backend/tools/backend-dev-proxy/templates/http-user-service-auth-redirection.conf.template, packages/backend/tools/backend-dev-proxy/templates/http-user-service-user-redirection.conf.template
- Updated dev proxy to proxy pass HTTP 1.1 requests.
- Extracted `JsonResponseBuilder` from `ResponseBuilder`.
=> Update dev proxy with proxy http version 1 1

docs/backend/setup.md, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdEventsV1SseController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameGameIdEventsV1RequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameGameIdEventsV1RequestParamHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.ts
- Added `GetGameGameIdEventsV1SseController`.
- Added `GetGameGameIdEventsV1RequestParamHandler`.
- Added `GameEventsManagementInputPort`.
=> Update backend game application with get game game id events v1 controller

packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/subscribers/GameEventsIoredisSubscriber.ts, packages/backend/libraries/backend-http/src/http/adapter/fastify/builders/FastifyReplySseConsumerFromFastifyReplyBuilder.ts, packages/backend/libraries/backend-http/src/http/application/modules/DelayedSseConsumer.spec.ts, packages/backend/libraries/backend-http/src/http/application/modules/DelayedSseConsumer.ts, packages/backend/libraries/backend-http/src/http/application/modules/SseConsumer.ts, packages/backend/libraries/backend-http/src/http/application/modules/SsePublisher.ts, packages/backend/libraries/backend-http/src/index.ts
- Updated `SseConsumer` to consume `EventMessage` objects.
- Updated `SsePublisher` to publish `EventMessage` objects.
=> Update SSE modules to publish and consume EventMessage objects

packages/backend/libraries/backend-pub-sub/src/index.ts, packages/backend/libraries/backend-pub-sub/src/modules/adapter/ioredis/IoredisPublisher.spec.ts, packages/backend/libraries/backend-pub-sub/src/modules/adapter/ioredis/IoredisPublisher.ts
=> Add IoredisPublisher

.github/workflows/run-e2e.yaml
=> Fix run e2e gh action

packages/backend/apps/game/backend-game-adapter-ioredis/src/foundation/redis/adapter/nest/models/ioredisClientSymbol.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/foundation/redis/adapter/nest/modules/PubSubIoredisModule.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/foundation/redis/adapter/nest/services/IoredisShutDownService.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/foundation/redis/adapter/nest/services/IoredisShutdownService.spec.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/subscribers/GameEventsIoredisSubscriber.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameMessageEventV1FromGameMessageEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameMessageEventV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameUpdatedEventFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameUpdatedEvent.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GameUpdatedEvent`.
- Added `GameUpdatedEventHandler`.
- Updated ioredis adapter with an additional consumer to allow subscribe and non subscribe operations.
- Updated game update flow to publish `GameUpdatedMessageEvent` data.
=> Update game update flow to sendgame updated message event

packages/backend/services/backend-service-game/src/foundation/http/adapter/nest/modules/HttpModule.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetEventsGamesGameIdV1RequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/tools/backend-dev-proxy/config/conf.d/locations.conf, packages/backend/tools/backend-dev-proxy/templates/http-game-service-game-events-redirection.conf.template
- Added `GetEventsGamesGameIdV1RequestNestController`.
- Updated `HttpModule` with additional sse modules.
- Updated proxy with additional redirection.
=> Add game sse endpoint

packages/backend/apps/game/backend-game-adapter-ioredis/src/index.ts, packages/backend/services/backend-service-game/src/foundation/redis/adapter/ioredis/calculations/buildIoredisModuleOptions.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `buildIoredisModuleOptions`.
=> Add build ioredis module options

packages/frontend/web-ui/src/common/helpers/validateFormConfirmPassword.js
- Updated `validateFormConfirmPassword` with proper validation.
=> Update validateFormConfirmPassword with proper validation

packages/frontend/web-ui/package.json
- Added `test:unit:js` npm script so CI can run unit tests.
=> Update web ui to launch tests on CI

packages/frontend/web-ui/jest.config.cjs, packages/frontend/web-ui/src/common/layout/CornieLayout.jsx, packages/frontend/web-ui/src/home/pages/CornieHome.jsx, packages/frontend/web-ui/src/scss/base/_globals.scss
- Updated `jest` config to pass with no affected tests.
- Updated `CornieLayout` with navbar and footer config.
=> Update cornie layout with navbar and footer config

packages/frontend/web-ui/jest.config.cjs, packages/frontend/web-ui/src/auth/hooks/useRegisterForm.spec.js, packages/frontend/web-ui/src/auth/pages/Register.jsx, packages/frontend/web-ui/src/auth/pages/Register.spec.jsx
1. Added _aria-label_ on inputs, button and alerts.
2. Added component AlertTitle on Alerts.
3. Created Unit test Register.
4. Added extension in jest.config.cjs to execute JSX test.
5. Changed test hook useRegisterForm, deleted waitForNextUpdate.
=> Testing Register component

.gitignore, packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/api/libraries/api-graphql-schemas/schemas/users/CreateUserMutation.graphql, packages/api/libraries/api-graphql-schemas/schemas/users/User.graphql, packages/api/libraries/api-graphql-schemas/schemas/users/UserCreateInput.graphql, packages/backend/apps/gateway/backend-gateway-application/src/app/adapter/nest/modules/ApplicationModule.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/adapter/nest/modules/AuthModule.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/CreateAuthMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/adapter/nest/modules/UsersModule.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/CreateUserMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/CreateUserMutationResolver.ts
- Added `CreateUserMutation`.
- Added `CreateUserMutationResolver`
- Updated `RootMutation` to implement `CreateUserMutation`.
=> Add CreateUserMutation

packages/backend/apps/game/backend-game-application/src/foundation/http/adapter/nest/modules/HttpModule.ts, packages/backend/apps/user/backend-user-application/src/foundation/http/adapter/nest/modules/HttpModule.ts, packages/backend/libraries/backend-http/src/http/application/builders/ErrorV1ResponseFromErrorBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/builders/ErrorV1ResponseFromErrorBuilder.ts, packages/backend/libraries/backend-http/src/http/application/builders/HttpStatusCodeFromErrorBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/builders/HttpStatusCodeFromErrorBuilder.ts, packages/backend/libraries/backend-http/src/index.ts
- Added `HttpStatusCodeFromErrorBuilder`.
- Updated `ErrorV1ResponseFromErrorBuilder` to rely on `HttpStatusCodeFromErrorBuilder`.
- Updated http application modules to provide `HttpStatusCodeFromErrorBuilder`.
=> Add HttpStatusCodeFromErrorBuilder

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-models/src/scripts/generateTsModels.ts, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/api/libraries/api-graphql-schemas/schemas/users/FindUsersQuery.graphql, packages/backend/apps/gateway/backend-gateway-application/package.json, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/FindUsersQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/FindUsersQueryResolver.ts
- Added `FindUsersQueryResolver`.
- Added `FindUsersQuery` schema.
- Updated model generation script to format output.
=> Add find users query resolver

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/users/FindUsersQuery.graphql, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/ApplicationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/FindUsersQueryResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts
- Updated `ApplicationResolver` with `RootQuery`.
=> Update ApplicationResolver with RootQuery

packages/frontend/web-ui/src/app/dom/main.jsx, packages/frontend/web-ui/src/app/routes/index.js, packages/frontend/web-ui/src/app/store/thunk/createAuthByToken.js, packages/frontend/web-ui/src/app/store/thunk/createAuthByToken.spec.js, packages/frontend/web-ui/src/app/theme/CornieAppTheme.jsx, packages/frontend/web-ui/src/app/theme/index.js, packages/frontend/web-ui/src/auth/hooks/index.js, packages/frontend/web-ui/src/auth/hooks/useLoginForm.js, packages/frontend/web-ui/src/auth/hooks/useRegisterConfirm.spec.js, packages/frontend/web-ui/src/auth/hooks/useRegisterForm.js, packages/frontend/web-ui/src/auth/hooks/useRegisterForm.spec.js, packages/frontend/web-ui/src/auth/pages/Login.jsx, packages/frontend/web-ui/src/auth/pages/Register.jsx, packages/frontend/web-ui/src/auth/pages/Register.spec.js, packages/frontend/web-ui/src/auth/pages/index.js, packages/frontend/web-ui/src/auth/routes/AuthRoutes.jsx, packages/frontend/web-ui/src/common/components/index.js, packages/frontend/web-ui/src/common/helpers/index.js, packages/frontend/web-ui/src/common/hooks/index.js, packages/frontend/web-ui/src/common/http/helpers/index.js, packages/frontend/web-ui/src/common/layout/CornieLayout.jsx
1. Deleted barrel files index.js from different folders.
2. Deleted from components, hooks and unit tests.
=> Deleted index barrel files

packages/backend/tools/backend-dev-grafana/.gitignore, packages/backend/tools/backend-dev-grafana/LICENSE, packages/backend/tools/backend-dev-grafana/config/grafana-datasources.yaml, packages/backend/tools/backend-dev-grafana/config/prometheus.yaml, packages/backend/tools/backend-dev-grafana/config/tempo.yaml, packages/backend/tools/backend-dev-grafana/docker-compose.yml, packages/backend/tools/backend-dev-grafana/package.json
- Added `backend-dev-grafana` package.
=> Add backend-dev-grafana package

packages/api/libraries/api-json-schemas/schemas/v1/games/active-game.json, packages/api/libraries/api-json-schemas/schemas/v1/games/finished-game.json, packages/api/libraries/api-json-schemas/schemas/v1/games/non-started-game.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1698775390967-UpdateGameWithName.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/entities/BaseGame.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/FinishedGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/NonStartedGameFixtures.ts
- Added `1698775390967-UpdateGameWithName` migration.
- Updated `GameDb` with `name`.
- Updated `GameDbToGameConverter` to handle `name`.
- Updated `Game` with `name`.
- Updated `GameV1FromGameBuilder` to handle `name`.
- Updated `GameV1` with optional name.
=> Update game with name

packages/backend/libraries/backend-monitoring/package.json, packages/backend/libraries/backend-monitoring/src/index.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/modules/ContinuousProfiler.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/modules/ProfileExporter.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/modules/Profiler.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/profilers/CpuProfiler.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/profilers/MemoryProfiler.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/utils/processProfile.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/grafana-pyroscope/models/PyroscopeConfig.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/grafana-pyroscope/services/PyroscopeApiExporter.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/grafana-pyroscope/services/PyroscopeProfiler.ts, packages/backend/services/backend-service-game/src/app/adapter/nest/scripts/trace.mts, packages/backend/services/backend-service-user/src/app/adapter/nest/scripts/trace.mts, packages/backend/tools/backend-dev-grafana/config/grafana-dashboards/games-service.json, packages/backend/tools/backend-dev-grafana/config/grafana-dashboards/users-service.json, packages/backend/tools/backend-dev-grafana/config/pyroscope.yaml, packages/backend/tools/backend-dev-grafana/docker-compose.yml
- Added `CpuProfiler`.
- Added `MemoryProfiler`.
- Added `PyroscopeConfig`.
- Added `PyroscopeProfiler`.
- Added `Profiler`.
- Updated `pyroscope` docker service with custom config.
- Updated backend services trace script to invoke a `PyroscopeProfiler`.
=> Pprof profiling

packages/api/libraries/api-json-schemas/schemas/v1/games/game-create-query.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameCreateQuery.ts
- Updated `GameCreateQueryV1` with `name`.
- Updated `GameCreateQuery` with `name`.
=> Update game create query v1 with name

docs/backend/openapi-docs.md, package.json, packages/backend/tools/backend-dev-swagger-ui/.gitignore, packages/backend/tools/backend-dev-swagger-ui/Dockerfile, packages/backend/tools/backend-dev-swagger-ui/LICENSE, packages/backend/tools/backend-dev-swagger-ui/docker-compose.yaml, packages/backend/tools/backend-dev-swagger-ui/package.json
- Added `backend-dev-swagger-ui` package.
=> Add backend dev Swagger UI

packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/profilers/HeapProfiler.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/datadog-pprof/profilers/WallProfiler.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/grafana-pyroscope/models/PyroscopeConfig.ts, packages/backend/libraries/backend-monitoring/src/profiling/adapter/grafana-pyroscope/services/PyroscopeProfiler.ts, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-game/src/app/adapter/nest/scripts/trace.mts, packages/backend/services/backend-service-user/package.json, packages/backend/services/backend-service-user/src/app/adapter/nest/scripts/trace.mts, packages/backend/tools/backend-dev-grafana/config/grafana-dashboards/games-service.json, packages/backend/tools/backend-dev-grafana/config/grafana-dashboards/users-service.json
- Updated `PyroscopeConfig` with `PyroscopeSourceMapConfig`.
- Updated Profilers to send source mapper.
- Updated `PyroscopeProfiler` to initialize source mapper.
- Updated trace scripts with source map directories.
=> Update profiler with sourcemap feature

packages/api/libraries/api-json-schemas/schemas/v1/games/game-spec.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSpecV1FromGameSpecBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSpecV1FromGameSpecBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameSpecV1Fixtures.ts, packages/backend/tools/backend-test-e2e/features/games/getGameSpec.feature, packages/backend/tools/backend-test-e2e/src/game/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/thenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/whenDefinitions.ts
- Updated `GameSpecV1` with `options`.
=> Update game spec v1 with options

packages/backend/tools/backend-test-e2e/features/games/getGameSpec.feature
=> Update test style

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/nest/modules/GameDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCardSpecArrayFromGameCardSpecArrayDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCardSpecArrayFromGameCardSpecArrayDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFromGameSpecDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFromGameSpecDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts
- Added `GameCardSpecArrayFromGameCardSpecArrayDbBuilder`.
- Updated `GameSpecFromGameSpecDb` to rely on `GameCardSpecArrayFromGameCardSpecArrayDbBuilder`.
- Updated `GameDbToGameConverter` to rely `GameCardSpecArrayFromGameCardSpecArrayDbBuilder`.
=> Add GameCardSpecArrayFromGameCardSpecArrayDbBuilder

packages/frontend/web-ui/src/app/store/data/authSliceStatus.js, packages/frontend/web-ui/src/app/store/features/authSlice.js, packages/frontend/web-ui/src/app/store/helpers/createInitialState.js, packages/frontend/web-ui/src/app/store/helpers/createInitialState.spec.js, packages/frontend/web-ui/src/auth/pages/Login.jsx, packages/frontend/web-ui/src/auth/pages/Login.spec.js
1. Added save token in Local Storage.
2. Fixed a bug to Login component.
3. Added new test to check than token is saved in Local Storage.
4. Added new function _createInitialState_ to initialize _authSlice_ from **Redux**.
=> Persist info about token in redux

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GameSpecPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GameSpecPersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GameSpecPersistenceOutputPort.ts
- Update `GameSpecPersistenceOutputPort` with `find`.
=> Update GameSpecPersistenceOutputPort with find

packages/backend/libraries/backend-http/src/http/application/services/RequestService.spec.ts, packages/backend/libraries/backend-http/src/http/application/services/RequestService.ts, packages/backend/libraries/backend-http/src/index.ts
=> Add RequestService

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFindQueryTypeormFromGameSpecFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFindQueryTypeormFromGameSpecFindQueryBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameSpecFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameSpecFindQuery.ts
- Updated `GameSpecFindQuery` with `limit` and `offset` optional fields.
=> Update GameSpecFindQuery with limit and offset

packages/backend/apps/game/backend-game-application/src/foundation/http/adapter/nest/modules/HttpModule.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGamesV1SpecsHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1SpecsRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1SpecsRequestParamHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts
- Added `GetGamesV1SpecsHttpRequestController`.
- Added `GetGamesV1SpecsRequestParamHandler`.
=> Add GetGamesV1SpecsHttpRequestController

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameV1GameIdHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGamesV1GameIdSpecHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1GameIdRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1GameIdRequestParamHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGameV1GameIdHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGamesV1GameIdSpecHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Rename `GetGameV1GameIdGameSpecHttpRequestController` to `GetGamesV1GameIdSpecHttpRequestController`.
=> Update get games v1 game id path

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-json-schemas/schemas/v1/games/game-spec-array.json, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGamesV1SpecsHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GetGamesV1SpecsHttpRequestNestController`.
=> Add GetGamesV1SpecsHttpRequestNestController

packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml
=> Update API docs with tags

packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/tools/backend-dev-swagger-ui/docker-compose.yaml
- Updated API with pagination constraints.
=> Update API docs with pagination constraints

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-json-schemas/schemas/v1/games/game-spec-array.json, packages/api/libraries/api-json-schemas/schemas/v1/games/game-spec.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFromGameSpecDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFromGameSpecDbBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSpecV1FromGameSpecBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSpecV1FromGameSpecBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameSpecV1Fixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameSpecFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameDrawService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/GameSpec.ts
- Updated `GameSpecV1` with `gameId`.
- Update `GameSpecArrayV1` with right items.
=> Update game spec with game

packages/api/libraries/api-json-schemas/schemas/v1/games/game-spec-sort-option.json, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSpecFindQuerySortOptionFromGameSpecSortOptionV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameSpecFindQuerySortOptionFromGameSpecSortOptionV1Builder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameSpecFindQuerySortOption.ts
- Added `GameSpecSortOptionV1`.
=> Add GameSpecSortOptionV1

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFindQueryTypeormFromGameSpecFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFindQueryTypeormFromGameSpecFindQueryBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameSpecFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameSpecFindQuery.ts
- Updated `GameSpecFindQuery` with sort.
=> Update GameSpecFindQuery with sort

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1SpecsRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1SpecsRequestParamHandler.ts, turbo.json
- Updated `GET v1/games/specs` with `sort` query.
=> Update GET v1/games/specs with sort query

packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.spec.ts
- Updated tests to rely on partial contexts.
=> Update test to rely on partial contexts

packages/api/libraries/api-json-schemas/schemas/v1/games/game-spec-array.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts
- Update `GameSpecArrayV1` with right items.
- Updated `GameApplicationModule` with missing provider.
=> Fix game spec array type

packages/backend/apps/gateway/backend-gateway-application/package.json, packages/backend/apps/gateway/backend-gateway-application/src/foundation/graphql/adapter/dataloader/handlers/BatchedGetByIdHandler.int.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/foundation/graphql/adapter/dataloader/handlers/BatchedGetByIdHandler.ts
- Added `BatchedGetByIdHandler`.
=> Add BatchedGetByIdHandler

.vscode/settings.json, packages/api/libraries/api-http-client/package.json, packages/api/libraries/api-http-client/src/httpClient/axios/AxiosHttpClient.ts, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/gateway/backend-gateway-application/src/games/adapter/dataloader/handlers/BatchedGetSpecByGameIdHandler.ts
- Updated `AxiosHttpClient` to properly stringify query params.
- Updated `GET /v1/games/specs` with 403 code.
=> Update get games specs with 403 http response code

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-models/src/scripts/generateTsModels.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameQueryResolver.ts
- Updated `ResolverTypeWrapper` to be Partial.
=> Update ResolverTypeWrapper to be Partial

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/common/Void.graphql, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/api/libraries/api-graphql-schemas/schemas/users/UserMutation.graphql, packages/backend/apps/gateway/backend-gateway-application/package.json, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/ApplicationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserMutationResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts
- Updated user GraphQL mutation with `deleteUserMe`.
=> Update user mutation with deleteUserMe

packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.ts
- Updated `UserManagementInputPort` to remove user codes.
=> Update delete user me flow

packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameV1MineRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameV1MineRequestParamHandler.ts, packages/backend/libraries/backend-http/src/index.ts
- Updated `Get /v1/games/mine` to properly parse pagination query.
=> Fix Get /v1/games/mine pagination

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/games/GameMutation.graphql, packages/api/libraries/api-graphql-schemas/schemas/games/GameSlotCreateInput.graphql, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/builders/GameGraphQlFromGameV1Builder.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts
- Added `createGameSlot` mutation.
- Updated `POST /v1/games/{gameId}/slots ` docs with 400 response.
- Updated `createGame` mutation to return `NonStartedGame`.
=> Add create game slot graph

.github/actions/setup/action.yaml, .github/workflows/build.yaml, .github/workflows/run-e2e.yaml, docs/backend/setup.md
- Added setup composite action.
- Updated ci workflow to rely on setup action.
- Updated e2e workflow to rely on setup action.
- Updated backend setup docs to require NodeJS 20.
=> Update gh workflows to rely on reusable actions

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/nest/modules/GameDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCardSpecArrayDbFromGameCardSpecArrayBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCardSpecArrayDbFromGameCardSpecArrayBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameDirectionDbFromGameDirectionBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameDirectionDbFromGameDirectionBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameDirectionFromGameDirectionDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameDirectionFromGameDirectionDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecCreateQueryTypeormFromGameGameSpecCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecCreateQueryTypeormFromGameGameSpecCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameStatusDbFromGameStatusBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameStatusDbFromGameStatusBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameDbToGameConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameUpdateQueryToGameSetQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameUpdateQueryToGameSetQueryTypeOrmConverter.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/adapter/dataloader/builders/BatchedGetSpecByGameIdHandlerBuilder.spec.ts
- Updated converters to be builders.
=> Update game converters to be builders

.dockerignore, Dockerfile, docs/backend/docker-images.md, packages/backend/services/backend-service-game/.dockerignore, packages/backend/services/backend-service-gateway/.dockerignore, packages/backend/services/backend-service-user/.dockerignore
- Added `Dockerfile`.
- Added `.dockerignore` files.
=> chore: add docker images builder

packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/models/DbModuleOptions.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/modules/DbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/nest/models/DbModuleOptions.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/nest/modules/DbModule.ts, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-game/src/foundation/db/adapter/nest/calculations/buildDbModuleOptions.ts, packages/backend/services/backend-service-user/package.json, packages/backend/services/backend-service-user/src/foundation/db/adapter/nest/calculations/buildDbModuleOptions.ts
- Updated `DbModuleOptions` with `builder`.
=> Update db module options with builder

packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/models/DbModuleOptions.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/modules/DbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/nest/modules/GameDbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/nest/models/DbModuleOptions.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/nest/modules/DbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/nest/UserDbModule.ts, packages/backend/services/backend-service-game/src/foundation/db/adapter/nest/calculations/buildDbModuleOptions.ts, packages/backend/services/backend-service-user/src/foundation/db/adapter/nest/calculations/buildDbModuleOptions.ts
- Updated `DbModuleOptions`with `builders`.
=> Update db options with delegated module builders

packages/backend/services/backend-service-user/src/app/adapter/nest/modules/AppModule.ts, packages/backend/services/backend-service-user/src/status/adapter/nest/controllers/GetReadyV1HttpRequestNestController.ts, packages/backend/services/backend-service-user/src/status/adapter/nest/modules/StatusHttpApiModule.ts
- Added `GET /v1/ready` endpoint.
=> Add GET /v1/ready

docs/backend/deployment.md, k8s/deploy, k8s/destroy, k8s/namespace.yaml
- Added k8s namespace.
- Added deploy script.
- Added destroy scropt.
- Added deployment docs.
=> K8s foundation

k8s/deploy, k8s/destroy, k8s/grafana/grafana-dashboards-config.yaml, k8s/grafana/grafana-dashboards.yaml, k8s/grafana/grafana-datasources-config.yaml, k8s/grafana/grafana.yaml, k8s/prometheus/prometheus-config.yaml, k8s/prometheus/prometheus.yaml, k8s/tempo/tempo-config.yaml, k8s/tempo/tempo.yaml
- Added `grafana` service.
- Added `prometheus` service.
- Added `tempo` service.
=> Add monitoring infrastructure

docs/backend/deployment.md, docs/backend/docker-images.md, k8s/.gitignore, k8s/deploy, k8s/destroy, k8s/one-game-services/rest/common/rest-api-config.yaml, k8s/one-game-services/rest/common/rest-api.secret.example.yaml, k8s/one-game-services/rest/user-service/db/db-cluster-auth.secret.yaml.example, k8s/one-game-services/rest/user-service/db/db-cluster.yaml, k8s/one-game-services/rest/user-service/user-service-config.yaml, k8s/one-game-services/rest/user-service/user-service.secret.example.yaml, k8s/one-game-services/rest/user-service/user-service.yaml
- Added user db cluster.
- Added user rest service.
- Updated `deploy` script.
- Updated `destroy` script.
- Updated deployment docs.
=> Add k8s user service

k8s/deploy, k8s/destroy, k8s/one-game-services/rest/game-service/redis-cluster.yaml
- Added game service redis cluster.
=> Add game service redis cluster

packages/backend/libraries/backend-common/src/error/application/models/AppError.ts
- Updated `AppError.isAppError` with missing check.
=> Update AppError.isAppError with missing check

.github/renovate.json
- Updated renovate with k8s dependency updates.
=> Update renovate to update k8s dependencies

docs/backend/deployment.md, k8s/deploy, k8s/destroy, k8s/one-game-services/rest/game-service/game-service-autoscaling.yaml, k8s/one-game-services/rest/user-service/user-service-autoscaling.yaml
- Added REST user service hpa.
- Added REST game service hpa.
- Updated deployment docs with required minikube addons.
=> Add k8s rest services hpa

docs/backend/deployment.md, k8s/deploy, k8s/destroy, k8s/ingress.yaml, k8s/one-game-services/frontend/web-ui/web-ui-autoscaling.yaml, k8s/one-game-services/frontend/web-ui/web-ui.yaml, k8s/one-game-services/rest/common/rest-api-config.yaml, k8s/one-game-services/rest/game-service/db/db-cluster.yaml, k8s/one-game-services/rest/user-service/db/db-cluster.yaml, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml
- Added k8s `web-ui` service.
- Updated api docs with production server.
=> Add k8s web UI service

packages/api/libraries/api-graphql-models/package.json, packages/api/libraries/api-graphql-models/src/scripts/generateTsModels.ts, packages/api/libraries/api-models/src/scripts/generateTsModels.ts
- Updated API model generator to rely on import statement.
- Updated graphql ts model generator to rely on graphql provider
=> Refactor ts model generators

packages/backend/libraries/backend-db/package.json, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/index.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/models/TypeOrmTransactionContext.ts, packages/backend/libraries/backend-db/src/persistence/application/index.ts, packages/backend/libraries/backend-db/src/persistence/application/models/TransactionContext.ts
- Added `TransactionContext`.
- Added `TypeOrmTransactionContext`.
=> Add application db transaction

packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/InsertTypeOrmService.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/InsertTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/postgres/InsertTypeOrmPostgresService.ts
- Updated `InsertTypeOrmService` with optional input `QueryRunner`.
=> Update InsertTypeOrmService with optional input queryRunner

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCardSpecArrayFromGameCardSpecArrayDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCardSpecArrayFromGameCardSpecArrayDbBuilder.ts, packages/backend/apps/game/backend-game-application/src/foundation/http/application/RequestBodyParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameGameIdSlotSlotIdCardsV1RequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1GameIdRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/NonStartedGameFilledEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/PostGameIdSlotV1RequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameSlotManagementInputPort.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/ActiveGameResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/FinishedGameResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/NonStartedGameResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserMutationResolver.spec.ts, packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/foundation/http/application/RequestBodyParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/DeleteUserV1EmailCodeRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/GetUserV1UserIdRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PostUserV1EmailCodeRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.spec.ts, packages/backend/libraries/backend-http/src/http/adapter/fastify/builders/RequestWithBodyFromFastifyRequestBuilder.spec.ts, packages/backend/libraries/backend-http/src/http/application/controllers/HttpRequestController.ts, packages/backend/libraries/backend-http/src/http/application/controllers/HttpSseRequestController.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.spec.ts
- Update catch blocks with error typings.
=> Update catch errors with proper typings

packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/utils/unwrapTypeOrmTransactionContext.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/utils/unwrapTypeOrmTransactionContext.ts
- Added `unwrapTypeOrmTransactionContext`.
=> Add unwrapTypeOrmTransactionContext

packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/nest/modules/DbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/typeorm/adapters/TransactionContextProvisionTypeOrmAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/typeorm/adapters/TransactionContextProvisionTypeOrmAdapter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/index.ts, packages/backend/apps/user/backend-user-application/package.json, packages/backend/apps/user/backend-user-application/src/foundation/db/application/index.ts, packages/backend/apps/user/backend-user-application/src/foundation/db/application/ports/output/TransactionContextProvisionOutputPort.ts
- Added `TransactionContextProvisionOutputPort`.
- Added `TransactionContextProvisionTypeOrmAdapter`.
- Updated `DbModule` with `forTransaction`.
=> Add TransactionContextProvisionOutputPort

packages/frontend/web-ui/src/common/helpers/passwordMinLength.js, packages/frontend/web-ui/src/common/helpers/passwordMinLength.ts
**Changed:**
- Transformed passwordMinLength data file from JavaScript to TypeScript file.
=> Convert passwordMinLength data from JS to TS

.github/actions/setup/action.yaml, package.json, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/UpdateTypeOrmQueryBuilderService.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/UpdateTypeOrmQueryBuilderService.ts
- Updated `UpdateTypeOrmQueryBuilderService` with transaction context.
=> Update UpdateTypeOrmQueryBuilderService with transaction context

package.json, packages/backend/libraries/backend-db/.gitignore, packages/backend/libraries/backend-db/jest.config.stryker.mjs, packages/backend/libraries/backend-db/package.json, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/models/TypeOrmTransactionWrapper.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/postgres/InsertTypeOrmPostgresService.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/postgres/InsertTypeOrmPostgresService.ts, packages/backend/libraries/backend-db/stryker.conf.json, turbo.json
- Added mutation tests for `backend-db` package.
- Added root `test:mutation` script.
=> Add backend db mutation testing

docs/backend/architecture/application/patterns/use-case-handler.md, packages/backend/libraries/backend-api-validators/.gitignore, packages/backend/libraries/backend-api-validators/jest.config.stryker.mjs, packages/backend/libraries/backend-api-validators/package.json, packages/backend/libraries/backend-api-validators/src/api/infrastructure/validatorProviders/ajv/AjvApiJsonSchemasValidationProvider.ts, packages/backend/libraries/backend-api-validators/src/validation/infrastructure/validatorProviders/ajv/AjvJsonSchemaValidatorProvider.ts, packages/backend/libraries/backend-api-validators/stryker.conf.json, packages/backend/libraries/backend-db/.gitignore
- Updated `backend-api-validators` packages with mutation tests.
=> Update backend api validators with mutations tests

package.json, packages/backend/apps/common/backend-adapter-nodemailer/.gitignore, packages/backend/apps/common/backend-adapter-nodemailer/jest.config.stryker.mjs, packages/backend/apps/common/backend-adapter-nodemailer/package.json, packages/backend/apps/common/backend-adapter-nodemailer/stryker.config.mjs, packages/backend/libraries/backend-pub-sub/.gitignore, packages/backend/libraries/backend-pub-sub/jest.config.stryker.mjs, packages/backend/libraries/backend-pub-sub/package.json, packages/backend/libraries/backend-pub-sub/src/modules/adapter/ioredis/IoredisSubscriber.spec.ts, packages/backend/libraries/backend-pub-sub/stryker.config.mjs, packages/backend/tools/backend-stryker-config/.gitignore, packages/backend/tools/backend-stryker-config/.lintstagedrc.json, packages/backend/tools/backend-stryker-config/LICENSE, packages/backend/tools/backend-stryker-config/lib/index.js, packages/backend/tools/backend-stryker-config/package.json, packages/backend/tools/backend-stryker-config/prettier.config.mjs
- Added stryker config package.
- Added mutation testing.
=> Add libraries mutation testing

packages/backend/apps/user/backend-user-adapter-typeorm/src/app/adapter/typeorm/migrations/1707511666604-AddRefreshTokenModel.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/nest/models/entities.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/nest/UserDbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/models/RefreshTokenDb.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/valueObjects/RefreshToken.ts
- Added `RefreshToken`.
- Added `RefreshTokenDb`.
=> Add user token models

packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/nest/modules/TokenDbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/adapters/RefreshTokenPersistenceTypeormAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/adapters/RefreshTokenPersistenceTypeormAdapter.ts, packages/backend/apps/user/backend-user-application/package.json, packages/backend/apps/user/backend-user-application/src/tokens/application/index.ts, packages/backend/apps/user/backend-user-application/src/tokens/application/ports/output/RefreshTokenPersistenceOutputPort.ts
- Added `RefreshTokenPersistenceOutputPort`.
- Added `RefreshTokenPersistenceTypeormAdapter`.
=> Add RefreshTokenPersistenceOutputPort

packages/backend/apps/user/backend-user-application/src/auth/adapter/nest/modules/AuthApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/auth/adapter/nest/modules/AuthHttpApiModule.ts, packages/backend/apps/user/backend-user-application/src/auth/application/controllers/PostAuthV2HttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/auth/application/handlers/PostAuthV2RequestBodyParamHandler.ts, packages/backend/apps/user/backend-user-application/src/auth/application/handlers/PostAuthV2RequestParamHandler.ts, packages/backend/apps/user/backend-user-application/src/auth/application/index.ts, packages/backend/services/backend-service-user/src/auth/adapters/nest/modules/AuthHttpApiModule.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts
- Added `PostAuthV2HttpRequestController`.
- Added `PostAuthV2HttpRequestParamHandler`.
=> Add PostAuthV2HttpRequestController

packages/backend/apps/user/backend-user-application/src/auth/application/controllers/PostAuthV2HttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.ts, packages/backend/apps/user/backend-user-application/src/tokens/application/models/RefreshTokenJwtPayload.ts
- Updated `PostAuthV2HttpRequestController` request type.
- Updated `RefreshTokenJwtPayload` with id.
=> Update RefreshTokenJwtPayload with id

packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/nest/modules/TokenDbModule.ts
- Updated `TokenDbModule` with missing provider.
=> Fix TokenDbModule

packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/user/backend-user-application/src/auth/adapter/nest/modules/AuthApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/auth/application/controllers/PostAuthV2HttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/auth/application/middlewares/AuthMiddleware.ts, packages/backend/apps/user/backend-user-application/src/auth/application/middlewares/RefreshTokenAuthMiddleware.ts
- Added `RefreshTokenAuthMiddleware`.
- Updated OpenAPI spec with refresh token security schema.
=> Add refresh token auth middleware

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/nest/modules/GameSnapshotDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/adapters/GameInitialSnapshotPersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/adapters/GameInitialSnapshotSlotPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/adapters/GameInitialSnapshotSlotPersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/builders/GameInitialSnapshotCreateQueryTypeOrmFromGameInitialSnapshotCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/builders/GameInitialSnapshotCreateQueryTypeOrmFromGameInitialSnapshotCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/builders/GameInitialSnapshotFromGameInitialSnapshotDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/builders/GameInitialSnapshotFromGameInitialSnapshotDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/fixtures/GameInitialSnapshotDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameSnapshots/adapter/typeorm/services/CreateGameInitialSnapshotTypeOrmService.ts, packages/backend/apps/game/backend-game-application/src/gameSnapshots/application/index.ts, packages/backend/apps/game/backend-game-application/src/gameSnapshots/application/ports/output/GameInitialSnapshotPersistenceOutputPort.ts, packages/backend/apps/game/backend-game-application/src/gameSnapshots/application/ports/output/GameInitialSnapshotSlotPersistenceOutputPort.ts, packages/backend/apps/game/backend-game-domain/src/gameSnapshots/domain/fixtures/GameInitialSnapshotCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameSnapshots/domain/fixtures/index.ts, packages/backend/apps/game/backend-game-domain/src/gameSnapshots/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/gameSnapshots/domain/query/GameInitialSnapshotCreateQuery.ts
- Added `GameInitialSnapshotPersistenceOutputPort`.
=> Add GameInitialSnapshotPersistenceOutputPort

packages/api/libraries/api-json-schemas/schemas/v1/games/game-id-draw-cards-query.json, packages/api/libraries/api-json-schemas/schemas/v1/games/game-id-update-query.json, packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/models/entities.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/GameActionDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/GameActionKindDb.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/DrawGameAction.ts
- Added `GameIdDrawCardsQueryV1`.
- Moved `GameActionDb` modules.
- Updated `DrawGameAction.draw` to be `Card[]`.
=> Add game game id draw cards query v1

packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/PlayerCanDrawCardsSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/PlayerCanDrawCardsSpec.ts
- Added `PlayerCanDrawCardsSpec`.
=> Add PlayerCanDrawCardsSpec

packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GameDrawCardsUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GameDrawCardsUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePlayCardsUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePlayCardsUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameDrawMutationFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts
- Add `GamePlayCardsUpdateQueryFromGameBuilder`.
- Add `GameDrawCardsUpdateQueryFromGameBuilder`.
- Add `GamePassTurnUpdateQueryFromGameBuilder`.
=> Add game update query builders

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameIdDrawCardsQueryV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts
- Added `GameIdDrawCardsQueryV1Handler`.
- Updated `GameIdUpdateQueryV1Handler` to no longer rely on a `GameService`.
=> Add GameIdDrawCardsQueryV1Handler

packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/FinishedGameSlotFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameOptionsFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameSpecFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/NonStartedGameSlotFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/PlayerCanPassTurnSpec.spec.ts
- `GameService.#getInitialDirection` to be `clockwise`.
=> Update game initial direction to be clockwise

packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GameCardsEffectUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GameCardsEffectUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts
- Added `GameCardsEffectUpdateQueryFromGameBuilder`.
=> Add GameCardsEffectUpdateQueryFromGameBuilder

packages/backend/apps/game/backend-game-application/src/games/application/handlers/NonStartedGameFilledEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/NonStartedGameFilledEventHandler.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/StartGameUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/StartGameUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts
- Added `StartGameUpdateQueryFromGameBuilder`.
=> Add StartGameUpdateQueryFromGameBuilder

packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameIdDrawCardsQueryV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.spec.ts
- Added `GameIdDrawCardsQueryV1Handler` tests.
=> Add GameIdDrawCardsQueryV1Handler tests

packages/backend/tools/backend-test-e2e/src/game/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/game/utils/actions/updateActiveGame.ts
- Updated given game definitions to ensure first player is the active one.
=> Update given game definitions to ensure first player is the active one

packages/api/libraries/api-json-schemas/schemas/v1/games/active-game-state.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/ActiveGameV1Fixtures.ts
- Updated `ActiveGameStateV1` with `currentTurnCardsDrawn`.
=> Update ActiveGameStateV1 with currentTurnCardsDrawn

packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePlayCardsUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePlayCardsUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameDrawService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameDrawService.ts
- Updated `GameDrawService` with `putCards`.
=> Update GameDrawService with putCards.

packages/backend/tools/backend-test-e2e/src/auth/models/AuthV1Parameter.ts, packages/backend/tools/backend-test-e2e/src/auth/models/AuthV2Parameter.ts, packages/backend/tools/backend-test-e2e/src/auth/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/auth/step-definitions/thenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/auth/step-definitions/whenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/auth/utils/actions/setAuth.ts, packages/backend/tools/backend-test-e2e/src/auth/utils/calculations/getAuthOrFail.ts, packages/backend/tools/backend-test-e2e/src/game/step-definitions/givenDefinitions.ts, packages/backend/tools/backend-test-e2e/src/http/models/OneGameApiWorld.ts, packages/backend/tools/backend-test-e2e/src/user/step-definitions/givenDefinitions.ts
- Updated `e2e` tests to rely on `AuthV2`.
=> Update e2e auth flows to rely on v2

packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1709925983470-UpdateGameActionWithCurrentPlayingSlotIndex.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/BaseGameActionDbPayload.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/GameActionDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/GameActionDbPayload.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/GameActionDbVersion.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/GameActionKindDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/BaseGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/DrawCardsGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/GameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/GameActionDbPayloadV1Kind.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/PassTurnGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/PlayCardsGameActionDbPayloadV1.ts
- Added `GameActionDbPayload`.
- Updated `GameActionDb` with `currentPlayingSlotIndex`.
=> Update GameActionDb with currentPlayingSlotIndex

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/nest/modules/GameActionsDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/fixtures/GameActionDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/fixtures/GameActionDbPayloadV1Fixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/DrawCardsGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/PassTurnGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-domain/package.json, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/index.ts
- Added `GameActionFromGameActionDbBuilder`
- Exposed `GameAction` domain modules.
=> Add GameActionFromGameActionDbBuilder

packages/backend/apps/game/backend-game-domain/src/gameActions/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/BaseGameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/DrawGameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/GameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/PassTurnGameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/PlayCardsGameActionCreateQuery.ts
- Added `GameActionCreateQuery`.
=> Add GameActionCreateQuery

packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1710008648314-UpdateGamePositionIndexWithUniqueConstraint.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/nest/modules/GameActionsDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/fixtures/GameActionDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/GameActionDb.ts, packages/backend/apps/game/backend-game-domain/package.json, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/index.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/BaseGameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/BaseGameAction.ts
- Added `GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder`.
- Updated `GameAction` with `gameId`.
- Updated `GameActionCreateQuery` without `position`.
=> Add GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/nest/modules/GameActionsDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/adapters/GameActionPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/adapters/GameActionPersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/services/CreateGameActionTypeOrmService.ts, packages/backend/apps/game/backend-game-application/package.json, packages/backend/apps/game/backend-game-application/src/gameActions/application/index.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/ports/output/GameActionPersistenceOutputPort.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/index.ts
- Added `CreateGameActionTypeOrmService`.
- Added `GameActionPersistenceOutputPort`.
- Added `GameActionPersistenceTypeOrmAdapter`.
=> Add GameActionPersistenceOutputPort

packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GameDrawCardsUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GameDrawCardsUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameDrawMutationFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts
- Exposed `GameDrawService`.
- Updated `GameIdUpdateQueryV1Handler` with `_handleUpdateGame`.
- Updated `GameDrawCardsUpdateQueryFromGameBuilder` to require a `GameDrawMutation`.
=> Update GameIdUpdateQueryV1Handler with more flexible handling

packages/backend/apps/game/backend-game-application/src/games/application/models/GameUpdatedEvent.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/CardsFromActiveGameSlotBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/CardsFromActiveGameSlotBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/CardsFromCurrentSlotOfActiveGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/CardsFromCurrentSlotOfActiveGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePlayCardsUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePlayCardsUpdateQueryFromGameBuilder.ts
- Added `CardsFromActiveGameSlotBuilder`.
- Added `CardsFromCurrentSlotOfActiveGameBuilder`.
- Updated `GamePlayCardsUpdateQueryFromGameBuilder` to rely on `CardsFromCurrentSlotOfActiveGameBuilder`.
=> Add CardsFromActiveGameSlotBuilder

packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/ActiveGameUpdatedCardsDrawEvent.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/ActiveGameUpdatedCardsPlayEvent.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/ActiveGameUpdatedEvent.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/ActiveGameUpdatedEventKind.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/ActiveGameUpdatedTurnPassEvent.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/BaseActiveGameUpdatedEvent.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts
- Updated `GameUpdatedEvent` with `kind`.
- Renamed `GameUpdatedEvent` to `ActiveGameUpdatedEvent`.
=> Update GameUpdatedEvent with kind

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/nest/modules/GameActionDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/index.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameActionCreateQueryFromGameUpdateEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameActionCreateQueryFromGameUpdateEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/ActiveGameUpdatedEventFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/tools/backend-test-e2e/src/app/adapter/nest/modules/AppModule.ts
- Updated `GameUpdatedEventHandler` to persist game actions.
=> Update GameUpdatedEventHandler to persist game actions

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/CreateGameUseCaseHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/CreateGameUseCaseHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameSlotManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameSlotManagementInputPort.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/CreateUserUseCaseHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/CreateUserUseCaseHandler.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/models/TypeOrmTransactionWrapper.ts, packages/backend/libraries/backend-db/src/persistence/application/models/TransactionWrapper.ts
- Updated transaction based flows to release them on uncaught errors.
=> Update transaction based flows to release them on uncaught errors

packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameMessageEventFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameUpdatedMessageEvent.ts
- Updated `GameUpdatedMessageEvent` with `gameAction`.
=> Update GameUpdatedMessageEvent with gameAction

packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.ts
- Renamed `MessageEventFromStringifiedGameMessageEventBuilder` to `MessageEventFromStringifiedGameMessageEventV1Builder`.
=> Rename message event builder

packages/api/libraries/api-json-schemas/schemas/v2/gameEvents/cards-drawn-game-event.json, packages/api/libraries/api-json-schemas/schemas/v2/gameEvents/cards-played-game-event.json, packages/api/libraries/api-json-schemas/schemas/v2/gameEvents/turn-passed-game-event.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts
- Updated `GameService` without `GameDrawService` dependency.
- Updated `GameEventV2` models.
=> Update game events api models

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV2Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV2Builder.ts
- Added `MessageEventFromStringifiedGameMessageEventV2Builder`.
=> Add MessageEventFromStringifiedGameMessageEventV2Builder

packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/adapters/GameEventsSubscriptionIoredisOutputAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/adapters/GameEventsSubscriptionIoredisOutputAdapter.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/subscribers/GameEventsIoredisSubscriber.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventsChannelFromGameIdBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventsChannelFromGameIdBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdEventsV1SseController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GameEventsSubscriptionOutputPort.ts
- Updated `GameEventsSubscriptionOutputPort` with `publishV2`.
=> Update GameEventsSubscriptionOutputPort with publishV2

packages/backend/apps/game/backend-game-application/src/games/application/builders/BaseMessageEventFromStringifiedGameMessageEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameMessageEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameMessageEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameMessageEventV1FromGameMessageEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameMessageEventV1FromGameMessageEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV2Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/MessageEventFromStringifiedGameMessageEventV2Builder.ts
- Updated message event builders to set ids if provided.
=> Update message event builders to set ids

packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/adapters/GameEventsSubscriptionIoredisOutputAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/adapters/GameEventsSubscriptionIoredisOutputAdapter.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GameEventsSubscriptionOutputPort.ts
- Updated `GameManagementInputPort` with `subscribeV2`.
=> Update GameManagementInputPort with subscribeV2

packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.ts
- Updated `GameUpdatedEventHandler` to publish game updated event in v2 channels.
=> Update GameUpdatedEventHandler to publish game updated event in v2 channels

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdEventsV2SseController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameGameIdEventsV2RequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameGameIdEventsV2RequestParamHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetEventsGamesGameIdV2RequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GetGameGameIdEventsV2SseController`.
- Added `GetGameGameIdEventsV2RequestParamHandler`.
=> Add GetGameGameIdEventsV2SseController

packages/backend/tools/backend-dev-proxy/config/conf.d/locations.conf, packages/backend/tools/backend-dev-proxy/templates/http-game-service-game-events-v2-redirection.conf.template
- Updated dev proxy with events v2 redirection.
=> Update dev proxy with events v2 redirection

packages/frontend/web-ui/index.html, packages/frontend/web-ui/src/about/routes/AboutUsRoutes.tsx, packages/frontend/web-ui/src/app/dom/main.tsx, packages/frontend/web-ui/src/app/routes/CornieAppRoutes.tsx, packages/frontend/web-ui/src/auth/routes/AuthRoutes.tsx, packages/frontend/web-ui/src/home/routes/HomeRoutes.tsx
- Transformed routes files `AboutUsRoutes`, `CornieAppRoutes`, `AuthRoutes`, `HomeRoutes` from JSX to TSX. 
- Transformed `main` page from JSX to TSX.
- Changed on `index.html `the extension of script module `main.tsx`
=> Convert routes and main page from JSX to TSX

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-http-client/src/typescript/builders/HttpClientMethodsBuilder.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/game/backend-game-application/src/games/application/builders/BaseMessageEventFromStringifiedGameMessageEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdEventsV1SseController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdEventsV2SseController.ts, packages/backend/libraries/backend-http/src/http/adapter/nest/controllers/HttpNestFastifySseController.spec.ts, packages/backend/libraries/backend-http/src/http/adapter/nest/controllers/HttpNestFastifySseController.ts, packages/backend/libraries/backend-http/src/http/application/controllers/HttpSseRequestController.spec.ts, packages/backend/libraries/backend-http/src/http/application/controllers/HttpSseRequestController.ts, packages/backend/libraries/backend-http/src/http/application/modules/DelayedSseConsumer.spec.ts, packages/backend/libraries/backend-http/src/http/application/modules/DelayedSseConsumer.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetEventsGamesGameIdV1RequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetEventsGamesGameIdV2RequestNestController.ts
- Updated `DelayedSseConsumer` with `setPreviousEvents`.
- Updated `HttpNestFastifySseController` to require controllers providing previous message events.
- Updated docs with game event SSE endpoints
=> Update DelayedSseConsumer with setPreviousEvents

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFindQueryTypeormFromGameSpecFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFindQueryTypeormFromGameSpecFindQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/FindGameSpecTypeOrmService.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/FindGameTypeOrmService.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/builders/RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/builders/RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/services/FindRefreshTokenTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.int.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.ts
- Updated `FindGameSpecTypeOrmService` with better generic types.
=> Update FindGameSpecTypeOrmService with better generic types

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFindQueryTypeOrmFromGameActionFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFindQueryTypeOrmFromGameActionFindQueryBuilder.ts, packages/backend/apps/game/backend-game-application/src/gameActions/adapter/nest/modules/GameActionApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/ports/input/GameActionManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/ports/input/GameActionManagementInputPort.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/GameActionFindQuery.ts
- Added `GameActionManagementInputPort`.
=> Add GameActionManagementInputPort

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameActionBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameActionBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameMessageEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameMessageEventBuilder.ts
- Added `GameEventV2FromGameActionBuilder`.
- Updated `GameEventV2FromGameMessageEventBuilder` to rely on `GameEventV2FromGameActionBuilder`.
=> Extract GameEventV2FromGameActionBuilder

packages/backend/apps/game/backend-game-application/src/gameActions/adapter/nest/modules/GameActionApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/builders/MessageEventFromGameActionBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/builders/MessageEventFromGameActionBuilder.ts
- Added `MessageEventFromGameActionBuilder`.
=> Add MessageEventFromGameActionBuilder

packages/backend/apps/game/backend-game-application/src/gameActions/application/ports/input/GameActionManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/ports/input/GameActionManagementInputPort.ts
- Updated `GameActionManagementInputPort` with `findNextMessageEventsByGameActionId`.
=> Update GameActionManagementInputPort with findNextMessageEventsByGameActionId

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFindQueryTypeOrmFromGameActionFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFindQueryTypeOrmFromGameActionFindQueryBuilder.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/GameActionFindQuery.ts
- Update `GameActionFindQuery` with `gameId`.
=> Update GameActionFindQuery with gameId property

packages/frontend/web-ui/vite.config.js, packages/frontend/web-ui/vite.config.ts
- Transformed file from JS to TS.
- Added new limit chunk size from 500Kb to 1000Kb.
=> Update limit chunk size in Vite

packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/adapters/GameEventsSubscriptionIoredisOutputAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/adapters/GameEventsSubscriptionIoredisOutputAdapter.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/subscribers/GameEventsIoredisSubscriber.spec.ts, packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/subscribers/GameEventsIoredisSubscriber.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GameEventsSubscriptionOutputPort.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/services/FindRefreshTokenTypeOrmService.ts, packages/backend/libraries/backend-common/src/common/application/modules/PublisherAsync.ts, packages/backend/libraries/backend-common/src/index.ts, packages/backend/libraries/backend-http/src/http/adapter/fastify/builders/FastifyReplySseConsumerFromFastifyReplyBuilder.ts, packages/backend/libraries/backend-http/src/http/adapter/nest/controllers/HttpNestFastifySseController.ts, packages/backend/libraries/backend-http/src/http/application/modules/DelayedSseConsumer.spec.ts, packages/backend/libraries/backend-http/src/http/application/modules/DelayedSseConsumer.ts, packages/backend/libraries/backend-http/src/http/application/modules/SseConsumer.ts, packages/backend/libraries/backend-http/src/http/application/modules/SsePublisher.ts
- Added `PublisherAsync` interface.
- Updated `GameEventsManagementInputPort` to close connection on finished game.
=> Update subcription flow with async publishers

.vscode/settings.json, package.json, packages/frontend/tools/frontend-prettier-config/.gitignore, packages/frontend/tools/frontend-prettier-config/LICENSE, packages/frontend/tools/frontend-prettier-config/cjs/index.d.ts, packages/frontend/tools/frontend-prettier-config/cjs/index.js, packages/frontend/tools/frontend-prettier-config/cjs/package.json, packages/frontend/tools/frontend-prettier-config/esm/index.d.ts, packages/frontend/tools/frontend-prettier-config/esm/index.js, packages/frontend/tools/frontend-prettier-config/package.json, pnpm-workspace.yaml
- Added `frontend-prettier-config` package.
=> Add frontend prettier config package

package.json, packages/frontend/tools/frontend-typescript-config/.gitignore, packages/frontend/tools/frontend-typescript-config/.lintstagedrc.json, packages/frontend/tools/frontend-typescript-config/package.json, packages/frontend/tools/frontend-typescript-config/prettier.config.mjs, packages/frontend/tools/frontend-typescript-config/tsconfig.base.cjs.json, packages/frontend/tools/frontend-typescript-config/tsconfig.base.esm.json, packages/frontend/tools/frontend-typescript-config/tsconfig.base.json
- Added `frontend-typescript-config` package.
=> Add frontend typescript config package

package.json, packages/frontend/tools/eslint-config-frontend/.gitignore, packages/frontend/tools/eslint-config-frontend/.lintstagedrc.json, packages/frontend/tools/eslint-config-frontend/LICENSE, packages/frontend/tools/eslint-config-frontend/index.js, packages/frontend/tools/eslint-config-frontend/package.json, packages/frontend/tools/eslint-config-frontend/prettier.config.mjs
- Added `eslint-config-frontend` package.
=> Add eslint-config-frontend package

package.json, packages/frontend/tools/frontend-jest-config/.gitignore, packages/frontend/tools/frontend-jest-config/.lintstagedrc.json, packages/frontend/tools/frontend-jest-config/LICENSE, packages/frontend/tools/frontend-jest-config/lib/config/getJestJsProjectConfig.js, packages/frontend/tools/frontend-jest-config/lib/config/getJestProjectConfig.js, packages/frontend/tools/frontend-jest-config/lib/config/getJestTsProjectConfig.js, packages/frontend/tools/frontend-jest-config/lib/config/getTestMatch.js, packages/frontend/tools/frontend-jest-config/lib/config/projectRoot.js, packages/frontend/tools/frontend-jest-config/lib/index.js, packages/frontend/tools/frontend-jest-config/package.json, packages/frontend/tools/frontend-jest-config/prettier.config.mjs
- Added `frontend-jest-config` package.
=> Add frontend-jest-config package

packages/frontend/web-ui/src/home/hooks/useGetGames/models/UseGetGamesContext.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/models/UseGetGamesParams.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildContext.spec.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildContext.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildErrorMessage.spec.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildErrorMessage.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildRequestParams.spec.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildRequestParams.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildResult.spec.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/buildResult.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/unexpectedErrorMesssage.ts
- Added use get games `buildResult`.
- Added use get games `buildRequestParams`.
- Added use get games `buildErrorMessage`.
- Added use get games `unexpectedErrorMessage`.
- Added use get games `buildContext`.
- Added use get games models.
=> Add use get games utils

packages/frontend/libraries/eventsource/README.md, packages/frontend/libraries/eventsource/src/events/modules/EventSource.ts, packages/frontend/libraries/eventsource/src/index.ts
- Updated `EventSource` with protected `_buildHeaders`.
=> Update eventsource with protected build headers

packages/backend/apps/game/backend-game-adapter-ioredis/src/games/adapter/ioredis/subscribers/GameEventsIoredisSubscriber.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdEventsV2SseController.ts, packages/backend/libraries/backend-http/src/http/adapter/fastify/builders/FastifySseReplyFromResponseBuilder.ts
- Updated `GetGameGameIdEventsV2SseController` with earlier event subscription.
- Updated `FastifySseReplyFromResponseBuilder` to not to send extra line feed.
- Updated `GameEventsIoredisSubscriber._handleMessageFromChannel` to be async.
=> Fix GetGameEvents v2 flow

packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1712868378201-UpdateGameWithLastEvent.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts
- Updated Game with `lastGameAction`.
=> Update Game with lastGameAction

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameUpdateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameUpdateQuery.ts
- Updated `GameUpdatedEventHandler` to update `lastGameActionId`.
- Updated `GameUpdateQuery` with `lastGameActionId`.
=> Update game updated event handler to set last game event

packages/api/libraries/api-http-client/src/httpClient/axios/AxiosHttpClient.ts, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-http-client/src/httpClient/models/Interceptor.ts, packages/api/libraries/api-http-client/src/httpClient/models/Request.ts, packages/api/libraries/api-http-client/src/httpClient/models/UseInterceptorOptions.ts, packages/api/libraries/api-http-client/src/index.ts, packages/api/libraries/api-http-client/src/typescript/builders/HttpClientMethodsBuilder.ts
- Added `Request`.
- Added `Interceptor`
- Updated `AxiosHttpClient.callEndpoint` to receive Request.
- Updated `AxiosHttpClient.callEndpoint` to invoke interceptors.
- Updated `AxiosHttpClient` with `useInterceptors`.
=> Update http axios client with interceptors

.github/actions/setup/action.yaml, .github/renovate.json, package.json, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-gateway/package.json, packages/backend/services/backend-service-user/package.json
=> Update pnpm to v9

packages/backend/apps/common/backend-adapter-nodemailer/src/mail/adapter/nest/modules/MailModule.ts, packages/backend/apps/common/backend-application-mail/src/index.ts, packages/backend/apps/game/backend-game-application/src/auth/application/middlewares/AuthMiddleware.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/PatchUserV1MeHttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UserCodeCreatedEventHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UserCreatedEventHandler.ts, packages/backend/libraries/backend-http/src/auth/application/models/UserAuth.ts, packages/frontend/web-ui/src/app/store/features/authSlice.spec.ts
=> Fix wrong imports

.github/actions/setup/action.yaml
=> Update pnpm setup action

.github/workflows/build.yaml, packages/backend/tools/backend-scripts/bin/getAffectedProjectsChunks.js, packages/backend/tools/backend-scripts/package.json
- Updated CI to group tests in chunks.
=> Update ci to group tests in chunks

package.json, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/typeorm/builders/BaseFindQueryToFindQueryTypeOrmBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/typeorm/builders/BaseFindQueryToFindQueryTypeOrmBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/builders/RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/builders/RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder.ts
- Updated `BaseFindQueryToFindQueryTypeOrmBuilder` with `_getSingleValueTransformer`.
- Updated `RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder` with proper query values.
=> Update user service

packages/api/libraries/api-http-client/src/httpClient/internal/InternalHttpClient.ts, packages/backend/tools/backend-dev-game-db/docker-compose.yml, packages/backend/tools/backend-dev-grafana/docker-compose.yml, packages/backend/tools/backend-dev-proxy/docker-compose.yml, packages/backend/tools/backend-dev-redis-pub-sub/docker-compose.yml, packages/backend/tools/backend-dev-swagger-ui/docker-compose.yaml, packages/backend/tools/backend-dev-user-db/docker-compose.yml, packages/backend/tools/backend-maildev/docker-compose.yml, packages/frontend/web-ui/src/auth/hooks/useRegisterConfirm.spec.ts, packages/frontend/web-ui/src/auth/hooks/useRegisterConfirm.ts
- Fixed `useRegisterConfirm` hook.
- Fixed `InternalHttpClient` to properly generate urls.
- Remove `docker-compose` deprecated version fields.
=> Fix Http client

packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.ts
- Updated refresh token automatic reuse detection flow to filter by the right date.
=> Fix AuthManagementInputPort

packages/frontend/web-ui/src/game/hooks/useJoinGame/index.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/models/UseJoinGameContext.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/models/UseJoinGameParams.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/buildErrorMessage.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/buildErrorMessage.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/buildRequestParams.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/buildRequestParams.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/buildResult.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/buildResult.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/unexpectedErrorMessage.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/useContext.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinGame/utils/useContext.ts
- Added new hook `useJoinGame` with their `models` and `utils`, and their tests.
=> Add new hook useJoinGame using useSingleAuthorizedApiCall

packages/frontend/tools/eslint-config-frontend/index.js, packages/frontend/web-ui/.eslintrc.cjs, packages/frontend/web-ui/package.json, packages/frontend/web-ui/src/app/store/features/authSlice.ts, packages/frontend/web-ui/src/app/store/features/userSlice.ts
- Added `eslint` react rules of hooks.
- Updated reducers to avoid unnecesary renderings.
=> Add eslint react rules of hooks

packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1717261608893-UpdateGameSlotWithUserIndex.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameSlotDb.ts
- Updated `GameSlotDb` with `userId` index.
- Updated `GameFindQueryTypeOrmFromGameFindQueryBuilder` with proper paginated query.
=> Fix Games find flow

packages/frontend/libraries/frontend-api-rtk-query/src/auth/actions/authorizedApiCall.spec.ts
- Added `authorizedApiCall` tests.
=> Add authorizedApiCall tests

packages/frontend/libraries/frontend-api-rtk-query/src/foundation/http/models/httpCodes.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/models/CreateGamesV1Args.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/mutations/createGamesV1.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/mutations/createGamesV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts
- Added `createGamesV1`.
- Added `CreateGamesV1Args`.
- Added `FORBIDDEN`.
=> Update rtk query with create games v1

packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1Mine.spec.ts
- Added `getGamesV1Mine` tests.
=> Add getGamesV1Mine tests

packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1Mine.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/models/GetUsersV1MeArgs.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1Me.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1Me.ts
- Added `GetUsersV1MeArgs`.
- Added `getUsersV1Me` query.
=> Update RTK query with get users v1 me

packages/frontend/libraries/frontend-api-rtk-query/src/foundation/http/models/httpCodes.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/models/CreateGamesV1SlotsArgs.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/mutations/createGamesV1Slots.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/mutations/createGamesV1Slots.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts
- Added `createGamesV1Slots` mutation.
=> Add createGamesV1Slots rRTK mutation

package.json, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.ts, packages/frontend/web-ui/src/game/models/CreateNewGameResult.ts, packages/frontend/web-ui/src/game/models/CreateNewGameStatus.ts, packages/frontend/web-ui/src/game/pages/CreateNewGame.spec.tsx, packages/frontend/web-ui/src/game/pages/CreateNewGame.tsx, turbo.json
- Updated `useCreateNewGame` to rely on `cornieApi`.
- Updated `turbo` config with `ui`.
=> Update use create game on top of cornie api

packages/frontend/libraries/frontend-api-rtk-query/src/common/models/ApiTag.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/models/UpdateUsersV1MeArgs.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/updateUsersV1Me.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/updateUsersV1Me.ts
- Added `ApiTags`
- Added `updateUsersV1Me` mutation.
- Updated `cornieApi` with `updateUsersV1Me` mutation.
=> Update cornieApi with updateUsersV1Me mutation

packages/frontend/web-ui/src/game/components/GameListItem.tsx, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.ts
- Updated `GameListItem` component to copy join game url.
- Updated hooks to avoid additional renders.
=> Update game list item share button to copy join game url

packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-json-schemas/schemas/v1/users/user-detail.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserHttpApiModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/builders/UserDetailV1FromUserBuilder.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/builders/UserDetailV1FromUserBuilder.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/GetUserV1MeDetailHttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/users/application/fixtures/UserDetailV1Fixtures.ts, packages/backend/apps/user/backend-user-application/src/users/application/index.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserDetailManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserDetailManagementInputPort.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/controllers/GetUserV1MeDetailHttpRequestNestController.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts
- Added `UserDetailV1`.
- Added `UserDetailV1FromUserBuilder`.
- Added `UserDetailManagementInputPort`.
- Added `GetUserV1MeDetailHttpRequestController`.
- Added `GetUserV1MeDetailHttpRequestNestController`.
=> Add GET /users/me/detail

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClientEndpoints.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/models/GetUsersV1MeDetailArgs.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1MeDetail.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1MeDetail.ts, packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResult.spec.ts, packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResult.ts, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts, packages/frontend/web-ui/src/user/hooks/useUserInfo.spec.ts, packages/frontend/web-ui/src/user/hooks/useUserInfo.ts, packages/frontend/web-ui/src/user/models/UseUserInfoResult.ts, packages/frontend/web-ui/src/user/pages/UserInfo.spec.tsx, packages/frontend/web-ui/src/user/pages/UserInfo.tsx
- Added `GET /v1/users/me/detail` docs.
- Added `getUsersV1MeDetail` query.
- Updated `UserInfo` page with user detail.
=> Update user info page with name

packages/frontend/web-ui/src/common/hooks/useRedirectUnauthorized.spec.ts, packages/frontend/web-ui/src/common/hooks/useRedirectUnauthorized.ts, packages/frontend/web-ui/src/user/pages/UserInfo.spec.tsx, packages/frontend/web-ui/src/user/pages/UserInfo.tsx
- Add `useRedirectUnauthorized` hook.
- Updated `UserInfo` page with home redirection.
=> Update UserInfo page with home redirection

packages/frontend/web-ui/src/game/components/BaseGameList.spec.tsx, packages/frontend/web-ui/src/game/components/BaseGameList.tsx, packages/frontend/web-ui/src/game/components/BaseGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/BaseGameListItem.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameList.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameList.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.tsx, packages/frontend/web-ui/src/game/hooks/useConsecutiveSnackbars.spec.ts, packages/frontend/web-ui/src/game/hooks/useConsecutiveSnackbars.ts, packages/frontend/web-ui/src/scss/common/_index.scss, packages/frontend/web-ui/src/scss/common/_snackbar.scss
- Added `NonStartedGameList` component.
- Added `useConsecutiveSnackbars` hook.
- Added `NonStartedGameListItem` component.
- Added `BaseGameList` component.
- Added `BaseGameListItem` component.
=> Add non started game list component

packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-json-schemas/schemas/v1/users/user-code-create-query.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts
- Added `UserCodeCreateQueryV1`.
=> Add UserCodeCreateQueryV1

packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/nest/modules/UserDbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeFromUserCodeDbBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeFromUserCodeDbBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeKindDbFromUserCodeKindBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeKindDbFromUserCodeKindBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeKindFromUserCodeKindDbBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeKindFromUserCodeKindDbBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/models/UserCodeKindDb.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserCodeFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/valueObjects/UserCode.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/valueObjects/UserCodeKind.ts
- Added `UserCodeKind`.
- Added `UserCodeKindDb`.
- Added `UserCodeKindDbFromUserCodeKindBuilder`.
- Added `UserCodeKindFromUserCodeKindDbBuilder`.
- Updated `UserCode` with `kind`.
=> Update user code with kind

packages/backend/apps/user/backend-user-adapter-typeorm/src/app/adapter/typeorm/migrations/1719761360228-UpdateUserCodeWithKind.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeFromUserCodeDbBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeFromUserCodeDbBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/fixtures/UserCodeDbFixtures.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/models/UserCodeDb.ts
- Updated `UserCodeDb` with `kind`.
=> Update UserCodeDb with kind

turbo.json
- Updated turbo config with env dependencies.
=> Update turbo config with env dependencies

packages/api/libraries/api-json-schemas/schemas/v1/types.json, packages/api/libraries/api-json-schemas/schemas/v1/users/user-code-create-query.json, packages/api/libraries/api-json-schemas/schemas/v1/users/user-code-kind.json, packages/api/libraries/api-models/src/models/ApiSchemaId.ts, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserHttpApiModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PostUserV1EmailCodeRequestBodyParamHandler.ts
- Added `PostUserV1EmailCodeRequestBodyParamHandler`.
- Added `UserCodeKindV1`.
=> Add PostUserV1EmailCodeRequestBodyParamHandler

packages/backend/apps/user/backend-user-application/src/users/application/fixtures/UserCodeCreatedEventFixtures.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UserCodeCreatedEventHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UserCodeCreatedEventHandler.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserCodeFixtures.ts
- Updated `UserCodeCreatedEventHandler` to rely on `UserCode.kind`.
=> Update UserCodeCreatedEventHandler to rely on user code kind

packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserCodeManagementInputPort.ts, packages/backend/apps/user/backend-user-domain/src/users/adapter/nest/UserDomainModule.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserCodeCreateQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/specs/UserCanCreateCodeSpec.spec.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/specs/UserCanCreateCodeSpec.ts
- Added `UserCanCreateCodeSpec`.
- Updated `UserCodeManagementInputPort` to rely on `UserCanCreateCodeSpec`.
=> Add UserCanCreateCodeSpec

packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/builders/UserCodeKindFromUserCodeKindV1Builder.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PostUserV1EmailCodeRequestParamHandler.ts
- Added `UserCodeKindFromUserCodeKindV1Builder`.
=> Add UserCodeKindFromUserCodeKindV1Builder

packages/backend/apps/common/backend-adapter-pulsar/src/index.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/nest/models/pulsarProducersMapSymbol.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/nest/modules/PulsarModule.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/adapters/MessageSendPulsarAdapter.spec.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/adapters/MessageSendPulsarAdapter.ts, packages/backend/apps/common/backend-application-messaging/src/mail/application/ports/output/MessageSendOutputPort.ts, packages/backend/apps/game/backend-game-adapter-pulsar/package.json, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/models/GamePulsarModuleRootOptions.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/models/gameTurnEndSignalProducerSymbol.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/modules/GamePulsarModule.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/pulsar/adapters/GameTurnEndSignalMessageSendPulsarAdapter.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/index.ts, packages/backend/apps/game/backend-game-application/package.json, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameTurnEndSignalMessage.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GameTurnEndSignalMessageSendOutputPort.ts
- Added `GameTurnEndSignalMessageSendOutputPort`.
- Added `GameTurnEndSignalMessageSendPulsarAdapter`.
- Updated `MessageSendPulsarAdapter` with generic type.
- Updated `PulsarModule` without producer providers.
=> Update game pulsar adapter package with adapter

package.json
- Updated `e2e` flow to create missing docker network.
=> Update e2e flow to create missing docker network

.github/workflows/build.yaml
- Updated build workflow to avoid caching pulsar data.
=> Update build workflow to avoid caching pulsar data

.github/workflows/run-e2e.yaml
- Updated e2e workflow with missing env
=> Update e2e workflow with missing env

packages/backend/apps/common/backend-adapter-pulsar/src/index.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/nest/models/PulsarModuleRootOptions.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/nest/models/pulsarConsumersMapSymbol.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/nest/modules/PulsarModule.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/models/PulsarClientOptions.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/models/GamePulsarModuleRootOptions.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/models/gameTurnEndSignalConsumerSymbol.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/models/gameTurnEndSignalProducerSymbol.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/modules/GamePulsarModule.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/pulsar/consumers/GameTurnEndSignalMessageConsumer.spec.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/pulsar/consumers/GameTurnEndSignalMessageConsumer.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/index.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/services/backend-service-game/src/foundation/pulsar/adapter/ioredis/calculations/buildGamePulsarModuleOptions.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GameTurnEndSignalMessageConsumer`.
- Updated pulsar modules with simplified design.
=> Add game turn end signal message consumer

packages/backend/apps/common/backend-adapter-pulsar/src/index.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/nest/modules/PulsarModule.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/services/PulsarConsumer.spec.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/services/PulsarConsumer.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/services/PulsarShutdownService.spec.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/services/PulsarShutdownService.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/modules/GamePulsarModule.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/services/services/PulsarConsumersShutdownService.spec.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/nest/services/services/PulsarConsumersShutdownService.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/games/adapter/pulsar/consumers/GameTurnEndSignalMessageConsumer.spec.ts, packages/backend/apps/game/backend-game-adapter-pulsar/src/index.ts
- Added `PulsarShutdownService`.
- Added `PulsarConsumersShutdownService`.
=> Update pulsar modules with shutdown services

.husky/commit-msg, docker/backend/Dockerfile, docker/frontend/Dockerfile, docs/backend/deployment.md, k8s/ingress.yaml, k8s/one-game-services/rest/game-service/db/db-cluster.yaml, k8s/one-game-services/rest/game-service/game-service-config.yaml, k8s/one-game-services/rest/game-service/game-service.yaml, k8s/one-game-services/rest/user-service/db/db-cluster.yaml, k8s/one-game-services/rest/user-service/user-service.yaml, k8s/setup-minikube/.gitignore, k8s/setup-minikube/config/values-minikube.yaml, k8s/setup-minikube/setup_minikube
- Added helm pulsar chart integration.
- Updated deployment docs with script reference.
- Updated ingress with missing forwarding.
- Updated dockerfiles with missing bash dependencies.
=> Fix k8s config

packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/services/PulsarConsumer.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts, packages/backend/libraries/backend-http/src/http/application/controllers/HttpRequestController.ts
- Updated `HttpRequestController` with `logger`.
- Updated GameIdUpdateQueryV1Handler with `logger`.
- Updated PulsarConsumer with `logger`.
=> Update modules with loggers

k8s/deploy, k8s/destroy, k8s/one-game-services/frontend/web-ui/web-ui.yaml, k8s/one-game-services/rest/game-service/game-consumer-autoscaling.yaml, k8s/one-game-services/rest/game-service/game-consumer.yaml, k8s/one-game-services/rest/game-service/game-service.yaml, k8s/one-game-services/rest/user-service/user-service.yaml, k8s/setup-minikube/config/values-minikube.yaml, k8s/setup-minikube/setup_minikube
- Added game consumer cluster.
=> Update k8s with pulsar consumer

packages/frontend/web-ui/src/auth/hooks/useLoginForm.ts
- Updated `useLoginForm` to update fields on backend error response.
=> Update useLoginForm to update fields on backend error response

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/auth/Auth.graphql, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.ts
- Updated AuthMutationResolver to rely on v2 auth
=> Update AuthMutationResolver to rely on v2 auth

packages/backend/services/backend-consumer-game/package.json
- Fixed `backend-consumer-game` `e2e` flow.
=> Update backend consumer game e2e flow

.github/workflows/publish.yaml
- Updated gh publish action with right commit message.
=> Fix gh publish action

.github/workflows/publish.yaml
- Updated `publish` workflow to rely on gh app.
=> Update publish workflow to rely on gh app

.github/workflows/publish.yaml
- Updated `publish` action to rely on gh app so pr related checks are triggered.
=> Fix publish gh action

.changeset/chilled-bikes-compare.md, .changeset/fifty-parrots-cover.md, .changeset/forty-meals-pretend.md, .changeset/giant-pumpkins-yawn.md, .changeset/nervous-news-deny.md, .changeset/young-fireants-applaud.md, packages/backend/services/backend-consumer-game/bin/bootstrap.mjs, packages/backend/services/backend-consumer-game/package.json, packages/backend/services/backend-service-game/bin/bootstrap.mjs, packages/backend/services/backend-service-game/bin/run-migrations.mjs, packages/backend/services/backend-service-game/package.json, packages/backend/services/backend-service-gateway/bin/bootstrap.mjs, packages/backend/services/backend-service-gateway/package.json, packages/backend/services/backend-service-user/bin/bootstrap.mjs, packages/backend/services/backend-service-user/bin/run-migrations.mjs, packages/backend/services/backend-service-user/package.json, packages/backend/tools/backend-test-e2e/package.json
- Updated packages with bin scripts.
=> Update service packages with bin scripts

.changeset/breezy-flowers-smoke.md, .changeset/chatty-doors-hope.md, .changeset/honest-melons-visit.md, packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/games/GameDrawCardsInput.graphql, packages/api/libraries/api-graphql-schemas/schemas/games/GameMutation.graphql, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts
- Added `drawGameCards` mutation.
=> Add drawGameCards mutation

.github/workflows/publish-docker-image.yaml
- Updated publish docker images gh action with right mapping.
=> Update docker image with right mapping

.changeset/silver-carpets-relate.md, packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1723287989401-UpdateGameWithIsPublic.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCreateQueryTypeOrmFromGameCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCreateQueryTypeOrmFromGameCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/fixtures/GameDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts
- Updated `GameDb` with `isPublic`.
=> Update GameDb with isPublic

.changeset/eleven-owls-hang.md, .changeset/happy-pens-smell.md, .changeset/metal-goats-hear.md, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCreateQueryTypeOrmFromGameCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameCreateQueryTypeOrmFromGameCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/entities/BaseGame.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/FinishedGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/NonStartedGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameCreateQuery.ts
- Updated `Game` and `GameCreateQuery` with `isPublic`.
- Updated modules to operate with updated domain game models.
=> Update Game and GameCreateQuery with isPublic

.changeset/metal-scissors-complain.md, .changeset/tender-mangos-yell.md, packages/api/libraries/api-json-schemas/schemas/v1/games/active-game.json, packages/api/libraries/api-json-schemas/schemas/v1/games/finished-game.json, packages/api/libraries/api-json-schemas/schemas/v1/games/game-create-query.json, packages/api/libraries/api-json-schemas/schemas/v1/games/non-started-game.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/ActiveGameV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameCreateQueryV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/NonStartedGameV1Fixtures.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/builders/GameGraphQlFromGameV1Builder.spec.ts, packages/frontend/web-ui/src/game/components/ActiveGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/BaseGameList.spec.tsx, packages/frontend/web-ui/src/game/components/BaseGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.spec.tsx, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.spec.ts
- Updated `GameV1` with `isPublic`.
- Updated `GameCreateQueryV1` with `isPublic`.
=> Update GameV1 and GameCreateQueryV1 with isPublic

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts
- Updated `GameDb` with missing transformer.
=> Update GameDb with missing transformer

.changeset/polite-beds-act.md, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameFindQuery.ts
- Updated `GameFindQuery` with `isPublic`.
- Updated `GameFindQueryTypeOrmFromGameFindQueryBuilder` to handle `isPublic`.
=> Update GameFindQuery with isPublic

packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameStatusFromGameV1StatusBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameStatusFromGameV1StatusBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameV1MineHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1MineRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1MineRequestParamHandler.ts
- Added `GameStatusFromGameV1StatusBuilder`.
=> Extract game status builder

.changeset/clean-feet-fail.md, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/modules/DbModule.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/GamesCanBeFoundByUserSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/GamesCanBeFoundByUserSpec.ts
- Added `GamesCanBeFoundByUserSpec`.
=> Add GamesCanBeFoundByUserSpec

.changeset/tasty-doors-clap.md, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1MineRequestParamHandler.spec.ts, packages/backend/libraries/backend-http/src/http/application/services/RequestService.spec.ts, packages/backend/libraries/backend-http/src/http/application/services/RequestService.ts
- Updated `RequestService` with `tryParseBooleanQuery`.
=> Update RequestService with tryParseBooleanQuery

.changeset/swift-birds-breathe.md, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGamesV1HttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGamesV1MineHttpRequestController.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1RequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1RequestParamHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGameV1MineHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGamesV1MineHttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GetGamesV1HttpRequestController`.
- Added `GetGamesV1RequestParamHandler`.
=> Add GetGamesV1HttpRequestController

.changeset/olive-schools-sing.md, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClientEndpoints.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameHttpApiModule.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/controllers/GetGamesV1HttpRequestNestController.ts, packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameHttpApiModule.ts
- Added `GET v1/games` endpoint.
=> Added GET v1/games

packages/frontend/web-ui/src/auth/helpers/validateConfirmPassword.ts, packages/frontend/web-ui/src/auth/helpers/validateEmail.ts, packages/frontend/web-ui/src/auth/helpers/validatePassword.ts, packages/frontend/web-ui/src/auth/hooks/useLoginForm.spec.ts, packages/frontend/web-ui/src/auth/hooks/useLoginForm.ts, packages/frontend/web-ui/src/auth/hooks/useRegister.spec.ts, packages/frontend/web-ui/src/auth/hooks/useRegister.ts, packages/frontend/web-ui/src/user/helpers/validateUsername.ts, packages/frontend/web-ui/src/user/hooks/useUserInfo.spec.ts, packages/frontend/web-ui/src/user/hooks/useUserInfo.ts
- Moved `validateUsername`.
- Moved `validatePassword`.
- Moved `validateConfirmPassword`.
=> Move web helpers

packages/frontend/web-ui/src/common/components/Navbar.tsx, packages/frontend/web-ui/src/common/components/NavbarOptions.tsx, packages/frontend/web-ui/src/common/components/NavbarUserMenu.tsx, packages/frontend/web-ui/src/common/helpers/getSlug.spec.ts, packages/frontend/web-ui/src/common/helpers/getSlug.ts, packages/frontend/web-ui/src/common/models/NavbarPageName.ts, packages/frontend/web-ui/src/scss/base/_globals.scss
- Added `getSlug`.
- Extracted components from `Navbar`.
=> Extract navbar components

packages/frontend/web-ui/src/common/components/Navbar.tsx, packages/frontend/web-ui/src/common/components/NavbarGamesMenu.tsx, packages/frontend/web-ui/src/common/components/NavbarOptions.tsx, packages/frontend/web-ui/src/common/components/NavbarUserMenu.tsx, packages/frontend/web-ui/src/common/helpers/getSlug.spec.ts, packages/frontend/web-ui/src/common/helpers/getSlug.ts, packages/frontend/web-ui/src/common/models/NavbarPageName.ts, packages/frontend/web-ui/src/home/components/HomeWithAuth.spec.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.tsx, packages/frontend/web-ui/src/scss/base/_globals.scss, packages/frontend/web-ui/src/scss/home/_page.scss, packages/frontend/web-ui/src/user/helpers/validateUsername.spec.ts, packages/frontend/web-ui/src/user/helpers/validateUsername.ts
- Added `NavbarGamesMenu`.
- Updated `HomeWithAuth` to no longer display a create game button.
- Updated navbar with games section.
=> Move create new game button to navbar

packages/frontend/web-ui/src/app/store/features/authSlice.ts, packages/frontend/web-ui/src/auth/pages/Login.spec.tsx, packages/frontend/web-ui/src/auth/pages/Login.tsx, packages/frontend/web-ui/src/common/components/Navbar.tsx, packages/frontend/web-ui/src/game/pages/CreateNewGame.spec.tsx, packages/frontend/web-ui/src/game/pages/CreateNewGame.tsx, packages/frontend/web-ui/src/home/pages/CornieHome.spec.tsx, packages/frontend/web-ui/src/home/pages/CornieHome.tsx
- Updated redirections to keep history.
- Updated `CornieHome` to rely on `selectAuthenticatedAuth`.
=> Update redirections to keep history

packages/frontend/web-ui/src/common/hooks/useRedirectUnauthorized.spec.ts, packages/frontend/web-ui/src/common/hooks/useRedirectUnauthorized.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.ts, packages/frontend/web-ui/src/game/pages/JoinExistingGame.spec.tsx, packages/frontend/web-ui/src/game/pages/JoinExistingGame.tsx
- Updated `JoinExisitngGame` component to rely on `useRedirectUnauthorized` hook.
- Updated `useRedirectUnauthorized` hook to properly extract url query.
=> Update join game page to rely on use redirect unauthorized hook

packages/frontend/web-ui/src/app/store/features/authSlice.spec.ts, packages/frontend/web-ui/src/app/store/features/authSlice.ts, packages/frontend/web-ui/src/auth/hooks/useLoginForm.spec.ts, packages/frontend/web-ui/src/auth/hooks/useLoginForm.ts, packages/frontend/web-ui/src/auth/pages/Login.spec.tsx, packages/frontend/web-ui/src/auth/pages/Login.tsx, packages/frontend/web-ui/src/auth/pages/Register.spec.tsx, packages/frontend/web-ui/src/auth/pages/Register.tsx, packages/frontend/web-ui/src/common/hooks/useRedirectAuthorized.spec.ts, packages/frontend/web-ui/src/common/hooks/useRedirectAuthorized.ts, packages/frontend/web-ui/src/game/pages/CreateNewGame.spec.tsx, packages/frontend/web-ui/src/game/pages/CreateNewGame.tsx
- Added `useRedirectAuthorized`.
- Updated Login page to rely on `useRedirectAuthorized`.
- Updated Register page to rely on `useRedirectAuthorized`.
- Updated CreateGamePage page to rely on `useRedirectUnauthorized`.
=> Update register and login to redirect if authorized

packages/frontend/web-ui/src/game/components/GameVisibilityTextField.tsx, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.ts, packages/frontend/web-ui/src/game/models/CreateNewGameResult.ts, packages/frontend/web-ui/src/game/models/FormFieldsNewGame.ts, packages/frontend/web-ui/src/game/pages/CreateNewGame.spec.tsx, packages/frontend/web-ui/src/game/pages/CreateNewGame.tsx, packages/frontend/web-ui/src/scss/game/pages/createGame/_index.scss
- Added `GameVisibilityTextField` component.
- Updated `FormFieldsNewGame` with `isPublic`.
- Updated `CreateNewGame` page with visibility field.
=> Update `CreateNewGame` with isPublic field

.changeset/thin-dolphins-relate.md, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/modules/DbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFindQueryTypeOrmFromGameFindQueryBuilder.ts
- Updated `GameFindQueryTypeOrmFromGameFindQueryBuilder` to properly set `isPublic` filter.
=> Fix builder to properly set `isPublic` filter

.changeset/lovely-lizards-suffer.md, packages/frontend/libraries/frontend-api-rtk-query/src/games/models/GetGamesV1Args.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts
- Added `getGamesV1` RTK query.
=> Add getGamesV1

packages/frontend/web-ui/src/common/helpers/getSlug.spec.ts, packages/frontend/web-ui/src/common/helpers/getSlug.ts, packages/frontend/web-ui/src/common/models/PageName.ts
- Updated `PageName` with `publicGames`.
=> Update PageName with publicGames

packages/frontend/web-ui/src/common/helpers/getSlug.spec.ts, packages/frontend/web-ui/src/common/helpers/getSlug.ts, packages/frontend/web-ui/src/common/models/PageName.ts
- Updated `PageName` with `joinGame`.
=> Update PageName with joinGame

.changeset/lovely-tigers-knock.md, packages/frontend/libraries/frontend-api-rtk-query/src/games/models/GetGamesSpecsV1Args.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesSpecsV1.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesSpecsV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts
- Updated RTK query with `getGamesSpecV1` query.
=> Update rtk query with get games specs

.changeset/fast-cooks-explode.md, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesWithSpecsV1.spec.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesWithSpecsV1.ts
- Added `useGetGamesWithSpecsV1`.
- Updated RTK query package entrypoint with missing types.
=> Add useGetGamesWithSpecsV1

packages/frontend/web-ui/src/game/components/ActiveGameList.spec.tsx, packages/frontend/web-ui/src/game/components/ActiveGameList.tsx, packages/frontend/web-ui/src/game/components/ActiveGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/ActiveGameListItem.tsx, packages/frontend/web-ui/src/game/components/BaseGameList.spec.tsx, packages/frontend/web-ui/src/game/components/BaseGameList.tsx, packages/frontend/web-ui/src/game/components/BaseGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/BaseGameListItem.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameList.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameList.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.tsx, packages/frontend/web-ui/src/game/pages/PublicGames.spec.tsx, packages/frontend/web-ui/src/game/pages/PublicGames.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.spec.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.tsx, packages/frontend/web-ui/src/scss/user/pages/userMe/_page.scss
- Updated `NonStartedGameList` component to render player slots data.
- Updated `BaseGameListItem` and `BaseGameList` components with a `TGameResources` generic type.
=> Update NonStartedGameList component to render player slots data

packages/frontend/web-ui/src/common/helpers/getSlug.spec.ts, packages/frontend/web-ui/src/common/helpers/getSlug.ts
- Updated `getSlug` with different create game value.
=> Update getSlug with different create game value

packages/frontend/web-ui/src/game/components/BaseCard.spec.tsx, packages/frontend/web-ui/src/game/components/BaseCard.tsx, packages/frontend/web-ui/src/game/components/DrawCard.spec.tsx, packages/frontend/web-ui/src/game/components/ImageCard.spec.tsx, packages/frontend/web-ui/src/game/components/ImageCard.tsx, packages/frontend/web-ui/src/game/components/NormalCard.spec.tsx, packages/frontend/web-ui/src/game/components/ReverseCard.spec.tsx, packages/frontend/web-ui/src/game/components/ReversedCard.tsx, packages/frontend/web-ui/src/game/components/SkipCard.spec.tsx, packages/frontend/web-ui/src/game/components/TextCard.spec.tsx, packages/frontend/web-ui/src/game/components/WildCard.spec.tsx, packages/frontend/web-ui/src/game/components/WildDraw4Card.spec.tsx, packages/frontend/web-ui/src/game/routes/GameRoutes.tsx, packages/frontend/web-ui/src/scss/base/_variables.scss, packages/frontend/web-ui/src/scss/game/components/_card.scss
- Updated `BaseCard` with differrent css classes.
=> Update BaseCard with differrent css classes

packages/frontend/web-ui/src/auth/hooks/useRegisterConfirm.spec.ts, packages/frontend/web-ui/src/auth/hooks/useRegisterConfirm.ts, packages/frontend/web-ui/src/common/hooks/useUrlLikeLocation.spec.ts, packages/frontend/web-ui/src/common/hooks/useUrlLikeLocation.ts, packages/frontend/web-ui/src/common/models/UrlLikeLocation.spec.ts, packages/frontend/web-ui/src/common/models/UrlLikeLocation.ts, packages/frontend/web-ui/src/common/models/Writable.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.ts
- Added `useUrlLikeLocation`.
- Updated `useRegisterConfirm` to rely on `useUrlLikeLocation`
- Updated `useJoinExistingGame` to rely on `useUrlLikeLocation`.
=> Add useUrlLikeLocation

packages/frontend/web-ui/src/game/pages/PublicGames.spec.tsx, packages/frontend/web-ui/src/game/pages/PublicGames.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.spec.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.tsx, packages/frontend/web-ui/src/user/hooks/useGetUserMe.spec.ts, packages/frontend/web-ui/src/user/hooks/useGetUserMe.ts
- Added `useGetUserMe`.
- Update `PublicGames` to rely on `useGetUserMe`.
- Update `HomeWithAuth` to rely on `useGetUserMe`.
=> Add useGetUserMe

.changeset/selfish-bears-teach.md, packages/frontend/libraries/frontend-api-rtk-query/src/games/models/GetGamesV1GameIdSlotsSlotIdCardsArgs.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1GameIdSlotsSlotIdCards.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1GameIdSlotsSlotIdCards.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts
- Added `getGamesV1GameIdSlotsSlotIdCards` query.
=> Add getGamesV1GameIdSlotsSlotIdCards query

packages/frontend/web-ui/src/game/components/TextCard.tsx, packages/frontend/web-ui/src/game/hooks/useGameCards.spec.ts, packages/frontend/web-ui/src/game/hooks/useGameCards.ts, packages/frontend/web-ui/src/scss/game/components/_card.scss
- Added `useGetGameCards`.
- Updated `TextCard` with right css class.
=> Add useGameCardsHook

packages/frontend/web-ui/src/game/pages/NonStartedGame.spec.tsx, packages/frontend/web-ui/src/game/pages/NonStartedGame.tsx, packages/frontend/web-ui/src/scss/game/pages/_index.scss, packages/frontend/web-ui/src/scss/game/pages/_nonStartedGame.scss
- Added `NonStartedGame` page.
=> Add NonStartedGame page

packages/backend/libraries/backend-monitoring/src/Tracer.ts, packages/backend/tools/backend-eslint-config/index.js, packages/frontend/web-ui/src/app/store/features/authSlice.ts, packages/frontend/web-ui/src/auth/hooks/useRegisterConfirm.spec.ts, packages/frontend/web-ui/src/auth/hooks/useRegisterConfirm.ts, packages/frontend/web-ui/src/auth/pages/Login.tsx, packages/frontend/web-ui/src/auth/pages/RegisterConfirm.spec.tsx, packages/frontend/web-ui/src/auth/pages/RegisterConfirm.tsx, packages/frontend/web-ui/src/common/components/CircularProgressModal.tsx, packages/frontend/web-ui/src/common/components/Footer.tsx, packages/frontend/web-ui/src/home/components/Home.tsx, packages/frontend/web-ui/src/scss/auth/pages/login/_index.scss, packages/frontend/web-ui/src/scss/common/components/_progress.scss, packages/frontend/web-ui/src/user/pages/UserInfo.tsx
- Added `selectAuth` selector.
- Updated `Login` page without deprecations.
- Updated `UserInfo` page without deprecations.
- Update `Home` page without deprecations.
- Updated `CircularProgressModal` component without deprecations.
- Updated `Footer` component without deprecations.
- Updated `RegisterConfirm` page without deprecations.
- Updated `useRegisterConfirm` with proper error handling.
=> Solve deprecations

packages/frontend/libraries/frontend-api-rtk-query/src/auth/mutations/createAuthV2.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/mutations/createGamesV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/mutations/createGamesV1Slots.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesSpecsV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1GameId.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1GameIdSlotsSlotIdCards.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1Mine.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/updateUsersV1Me.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1Me.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1MeDetail.ts, packages/frontend/web-ui/src/auth/pages/Register.tsx, packages/frontend/web-ui/src/game/pages/JoinExistingGame.spec.tsx, packages/frontend/web-ui/src/game/pages/JoinExistingGame.tsx, packages/frontend/web-ui/src/scss/auth/pages/register/_page.scss
- Updated `JoinExistingGame` page with `Grid2`.
- Updated RTK query default errors with serializable ones.
- Updated `Register` page without Grid2 deprecations.
=> Solve frontend deprecations

packages/frontend/web-ui/src/scss/auth/pages/register/_page.scss, packages/frontend/web-ui/src/scss/auth/pages/registerConfirm/_index.scss
- Updated register confirm page styles.
=> Fix register confirm page styles

packages/frontend/web-ui/src/game/pages/CreateNewGame.tsx, packages/frontend/web-ui/src/game/pages/JoinExistingGame.tsx
- Updated `CreateNewGame` page to rely on `Grid2`.
=> Migrate create game page to grid2

packages/frontend/tools/frontend-eslint-config/index.js, packages/frontend/web-ui/src/common/helpers/getSlug.spec.ts, packages/frontend/web-ui/src/common/helpers/getSlug.ts, packages/frontend/web-ui/src/common/layout/CornieLayout.tsx, packages/frontend/web-ui/src/common/layout/__mocks__/CornieLayout.tsx, packages/frontend/web-ui/src/common/models/PageName.ts, packages/frontend/web-ui/src/game/components/ActiveGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/ActiveGameListItem.tsx, packages/frontend/web-ui/src/game/pages/Game.spec.tsx, packages/frontend/web-ui/src/game/pages/Game.tsx, packages/frontend/web-ui/src/game/routes/GameRoutes.tsx, packages/frontend/web-ui/src/scss/game/pages/_game.scss, packages/frontend/web-ui/src/scss/game/pages/_index.scss
- Added `Game` page.
- Updated `ActiveGameListItem` with game redirection.
- Updated `PageName` with `game` slug.
=> Add game page

packages/frontend/libraries/eventsource/README.md, packages/frontend/libraries/eventsource/src/events/handlers/EventHandler.ts, packages/frontend/libraries/eventsource/src/events/modules/EventEmitter.spec.ts, packages/frontend/libraries/eventsource/src/events/modules/EventEmitter.ts, packages/frontend/libraries/eventsource/src/events/modules/EventSource.int.spec.ts, packages/frontend/libraries/eventsource/src/events/modules/EventSource.ts, packages/frontend/libraries/eventsource/src/events/modules/EventSourceEmitter.ts
- Updated `EventSource` to implement Web API `EventSource` event handling.
=> Update EventSource to implement web API EventSource

.changeset/curvy-trains-return.md, .changeset/cyan-balloons-build.md, .changeset/early-countries-visit.md, .changeset/fair-years-warn.md, packages/frontend/libraries/eventsource/src/events/modules/EventSource.ts
- Updated `EventSource` to create potential CORS request with the right mode.
=> Fix EventSource CORS

packages/frontend/web-ui/src/game/helpers/isFinishedGame.spec.ts, packages/frontend/web-ui/src/game/helpers/isFinishedGame.ts
=> Add isFinishedGame

packages/frontend/web-ui/package.json, packages/frontend/web-ui/src/common/env/services/EnvironmentService.ts, packages/frontend/web-ui/src/common/env/services/__mocks__/EnvironmentService.ts, packages/frontend/web-ui/src/common/http/services/CornieEventSource.ts, packages/frontend/web-ui/src/common/http/services/__mocks__/CornieEventSource.ts, packages/frontend/web-ui/src/game/helpers/buildEventSource.spec.ts, packages/frontend/web-ui/src/game/helpers/buildEventSource.ts, packages/frontend/web-ui/src/game/helpers/handleGameMessageEvents.spec.ts, packages/frontend/web-ui/src/game/helpers/handleGameMessageEvents.ts
- Added `handleGameMessageEvents`.
- Added `buildEventSource`.
- Added `CornieEventSource`.
- Updated `EnvironmentService` with mock module.
- Updated `web-ui` dependencies with `@cornie-js/eventsource`.
=> Extract use game utils

.changeset/early-countries-visit.md, .changeset/tame-windows-obey.md, packages/frontend/libraries/frontend-api-rtk-query/src/games/models/GetGamesGameIdSpecsV1Args.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesGameIdSpecsV1.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesGameIdSpecsV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts
- Added `GetGamesGameIdSpecsV1Args`.
- Added `getGamesGameIdSpecsV1` RTK query.
=> Add get games game id specs v1 rtk query

packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts, packages/frontend/web-ui/src/game/hooks/useGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useGame.ts, packages/frontend/web-ui/src/game/hooks/useGetGameSpecV1.spec.ts, packages/frontend/web-ui/src/game/hooks/useGetGameSpecV1.ts, packages/frontend/web-ui/src/game/pages/Game.spec.tsx, packages/frontend/web-ui/src/game/pages/Game.tsx
- Added `useGetGameSpecV1`.
- Updated `Game` page with deck cards amount.
=> Update game page with deck cards amount

packages/frontend/web-ui/src/game/hooks/useGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useGame.ts
- Fixed `countDeckCards` to deduce the current card from the count.
=> Update useGame with proper countDeckCards

.changeset/tiny-clouds-melt.md, packages/api/libraries/api-json-schemas/schemas/v1/games/active-game-state.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameV1FromGameBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/ActiveGameV1Fixtures.ts, packages/frontend/web-ui/src/game/helpers/buildEventSource.spec.ts, packages/frontend/web-ui/src/game/helpers/cloneGame.spec.ts, packages/frontend/web-ui/src/game/helpers/handleGameMessageEvents.spec.ts, packages/frontend/web-ui/src/game/helpers/isActiveGame.spec.ts, packages/frontend/web-ui/src/game/helpers/isNonStartedGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useGame.spec.ts
- Updated `ActiveGameStateV1` with `turnExpiresAt`.
=> Update ActiveGameStateV1 with turnExpiresAt

packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResult.spec.ts, packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResult.ts, packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResultV2.spec.ts, packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResultV2.ts
- Updated `mapUseQueryHookResult` on refetch edge case.
- Updated `mapUseQueryHookResultV2` on refetch edge case.
=> Fix mapUseQueryHookResult on refetch edge case

packages/api/libraries/api-graphql-schemas-provider/package.json, packages/api/libraries/api-http-client/package.json, packages/api/libraries/api-json-schemas-provider/package.json, packages/api/libraries/api-models/package.json, packages/api/libraries/api-models/src/jsonSchema/application/useCases/ResolveApiSchemaHttpReferenceUseCase.spec.ts, packages/api/libraries/api-openapi-schema/package.json, packages/backend/libraries/backend-api-validators/package.json, packages/backend/tools/process-manager/package.json, packages/frontend/libraries/eventsource/package.json, packages/frontend/libraries/frontend-api-rtk-query/package.json, packages/tools/json-schema-utils/package.json, packages/tools/openapi-utils/package.json
- Removed unused `jest-mock` dependency.
=> Remove unused jest-mock dependency

.github/renovate.json, .github/workflows/publish.yaml, turbo.json
- Improved `turbo` config.
- Updated `publish` workflow with pull request event.
- Updated `renovate` config without unused dependency.
=> Improve turbo config

.github/actions/publish-docker-image/action.yaml, .github/actions/setup/action.yaml, .github/renovate.json, docker/backend/Dockerfile, docker/frontend/Dockerfile, docs/backend/setup.md
- Updated docker node images to rely on node 22.
=> Update docker node images

packages/frontend/web-ui/src/game/components/Card.spec.tsx, packages/frontend/web-ui/src/game/components/Card.tsx, packages/frontend/web-ui/src/game/components/NormalCard.spec.tsx, packages/frontend/web-ui/src/game/components/NormalCard.tsx, packages/frontend/web-ui/src/game/components/WildDraw4Card.spec.tsx, packages/frontend/web-ui/src/game/components/WildDraw4Card.tsx
- Modify Card.tsx and his test to add new onDoubleClick function.
- Modify NormalCard.tsx and his test to add new onDoubleClick function.
- Modify WildDraw4Card.tsx and his test to add new onDoubleClick function.
=> Update remaining cards module to add double click function

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClientEndpoints.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.ts, turbo.json
- Updated `PATCH /v1/games/{gameId}` with missing response codes.
- Updated `turbo` consig with proper web outputs.
Fixes #1812.
=> Update patch game with missing error codes

packages/frontend/web-ui/src/game/hooks/useGame.ts
- Updated `useGame` to avoid duplicated game state update.
=> Update useGame to avoid duplicated game state update

.changeset/empty-donuts-sell.md
=> Add missing changeset

.changeset/five-dodos-wash.md, .changeset/tiny-snakes-warn.md, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.ts, packages/frontend/web-ui/src/game/components/ColorChoiceDialog.spec.tsx, packages/frontend/web-ui/src/game/components/ColorChoiceDialog.tsx, packages/frontend/web-ui/src/game/hooks/useGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useGame.ts, packages/frontend/web-ui/src/game/hooks/useGameCards.spec.ts, packages/frontend/web-ui/src/game/hooks/useGameCards.ts, packages/frontend/web-ui/src/game/pages/Game.spec.tsx, packages/frontend/web-ui/src/game/pages/Game.tsx, packages/frontend/web-ui/src/scss/game/components/_colorChoiceDialog.scss, packages/frontend/web-ui/src/scss/game/components/_index.scss
- Added new style file `_colorChoiceDialog.scss` with the styles of component `ColorChoiceDialog`. 
- Added new component `ColorChoiceDialog.tsx` and his test.
- Updated file `_index.scss` from game folder in scss files.
- Updated page file `Game.tsx` and his test to add new component ColorChoiceDialog.
- Updated hook file `useGame.ts` and his test to add new functionality to choice a color with wild and wildDraw4 cards.
- Updated hook file `useGameCards.ts` and his test to change selectedCards from array of numbers to array of cards.
=> Update game page with wild and wildDraw4 choose color

.github/actions/setup/action.yaml
=> Update pnpm version

.changeset/sour-panthers-leave.md, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserFindQueryTypeOrmFromUserFindQueryBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserFindQueryTypeOrmFromUserFindQueryBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserFindQueryTypeOrmFromUserUpdateQueryBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserFindQueryTypeOrmFromUserUpdateQueryBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/DeleteUserTypeOrmService.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/FindUserTypeOrmService.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/UpdateUserTypeOrmService.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserFindQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/query/UserFindQuery.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/query/UserFindQuerySortOption.ts
- Added `UserFindQuerySortOption`.
- Updated `UserFindQuery` with `limit`, `offset`, `ids` and `sort` filters.
- Updated user find db flow to support `UserFindQuery` new filters.
=> Update user find query with additional filters

.changeset/large-dogs-jump.md, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/CreateUserUseCaseHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/UpdateUserUseCaseHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/output/UserPersistenceOutputPort.ts
- Updated `UserManagementInputPort` with `find`.
- Updated `UserPersistenceOutputPort` with `find`.
=> Update user management input port with find

packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/models/GetUsersV1Args.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/queries/getUsersV1.ts, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts
- Added new query `getUsersV1.ts` and its test.
- Added new file `GetUsersV1Args.ts` of parameters to getUsersV1 query.
- Updated file `index.ts` to add new query `getUsers`.
- Updated file `cornieApi.ts` from folder `__mocks__` to add new query `getUsers`.
=> Add new query getUsers to cornieApi
