notaphplover/one-game

packages/backend-api-models/schemas/src/api/types.json, packages/backend-api-models/schemas/src/api/v1/cards/card.json, packages/json-schema-utils/CHANGELOG.md, packages/json-schema-utils/src/index.ts, packages/json-schema-utils/src/json-schema/fixtures/JsonRootSchema202012Fixtures.ts, packages/json-schema-utils/src/json-schema/functions/jsonSchemaRefToResourceLocation.spec.ts, packages/json-schema-utils/src/json-schema/functions/jsonSchemaRefToResourceLocation.ts, packages/json-schema-utils/src/json-schema/models/JsonSchema202012.ts, packages/json-schema-utils/src/resource/models/ResourceLocation.ts, packages/json-schema-utils/src/resource/models/ResourceLocationType.ts
- Added `jsonSchemaRefToResourceLocation`.
- Added `ResourceLocation`.
- Updated `card` schemas to use `anyOf` instead of `oneOf` structures.
- Updated `JsonSchema202012` with better types and missing optional properties.
=> Add json schema ref to resource location

packages/backend-http/CHANGELOG.md, packages/backend-http/src/http/controllers/application/SingleEntityHttpRequestController.ts, packages/backend-http/src/http/controllers/application/SingleEntityHttpRequestController.ts.spec.ts, packages/backend-http/src/index.ts, packages/backend-service-user/src/app/adapter/nest/modules/AppModule.ts, packages/backend-service-user/src/foundation/http/adapter/nest/modules/HttpModule.ts, packages/backend-service-user/src/user/adapter/nest/modules/UserHttpApiModule.ts, packages/backend-service-user/src/user/application/controllers/PostUserV1HttpRequestController.ts
- Added `PostUserV1HttpRequestController`.
- Added `HttpModule`.
- Exposed `SingleEntityHttpRequestController`.
- Updated `SingleEntityHttpRequestController` to no longer rely on TApiModel and rely on protected use case handler.
=> Add PostUserV1HttpRequestController  @notaphplover

packages/backend/libraries/backend-db/src/persistence/services/typeorm/FindTypeOrmService.spec.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/FindTypeOrmService.ts, packages/backend/services/backend-service-user/src/user/adapter/nest/modules/UserModule.ts, packages/backend/services/backend-service-user/src/user/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.spec.ts, packages/backend/services/backend-service-user/src/user/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.ts, packages/backend/services/backend-service-user/src/user/adapter/typeorm/converters/UserFindQueryToUserFindQueryTypeOrmConverter.spec.ts, packages/backend/services/backend-service-user/src/user/adapter/typeorm/converters/UserFindQueryToUserFindQueryTypeOrmConverter.ts, packages/backend/services/backend-service-user/src/user/adapter/typeorm/services/FindUserTypeOrmService.ts, packages/backend/services/backend-service-user/src/user/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/services/backend-service-user/src/user/application/ports/input/UserManagementInputPort.ts, packages/backend/services/backend-service-user/src/user/application/ports/output/UserPersistenceOutputPort.ts, packages/backend/services/backend-service-user/src/user/domain/fixtures/UserFindQueryFixtures.ts, packages/backend/services/backend-service-user/src/user/domain/models/UserFindQuery.ts
- Added `UserFindQuery`.
- Added `UserFindQueryToUserFindQueryTypeOrmConverter`.
- Added `FindUserTypeOrmService`.
- Updated `FindTypeOrmService` with more flexible contracts.
- Updated `UserPersistenceOutputPort` with `findOne` method.
- Updated `UserManagementInputPort` with `findOne` method.
=> Update user persistence output port with find one method

.github/workflows/build.yml, package.json, packages/backend/libraries/backend-scripts/bin/getAffectedProjects.js
- Updated `getAffectedProjects` script to return the right project ids.
- Renamed `build:all` script to `build`. 
- Renamed `lint:all` script to `lint`.
=> Fix get affected projects script

packages/backend/services/backend-service-game/src/games/adapter/nest/modules/GameModule.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.spec.ts, packages/backend/services/backend-service-game/src/games/application/ports/input/GameSlotManagementInputPort.ts, packages/backend/services/backend-service-game/src/games/domain/specs/GameCanHoldOnlyOneMoreGameSlotSpec.spec.ts, packages/backend/services/backend-service-game/src/games/domain/specs/GameCanHoldOnlyOneMoreGameSlotSpec.ts
- Added `GameCanHoldOnlyOneMoreGameSlotSpec`.
- Updated `GameSlotManagementInputPort.create` to trigger events.
=> Update GameSlotManagementInputPort to trigger event

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/apps/game/backend-game-application/src/games/adapter/nest/modules/GameApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameIdPassTurnQueryV1Fixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/NonStartedGameFilledEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/NonStartedGameFilledEventHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameSlotFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts
- Exposed `PlayerCanPassTurnSpec`.
- Updated `GameManagementInputPort` with `updateOne`.
- Updated `GameService` with `buildPassTurnGameUpdateQuery` and `buildStartGameUpdateQuery`.
=> Update GameManagementInputPort with updateOne

packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/typeorm/converters/BaseFindQueryToFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameUpdateQueryToGameFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameUpdateQueryToGameFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/FindGameTypeOrmService.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/UpdateGameSlotTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/UpdateTypeOrmService.ts
- Added `BaseFindQueryToFindQueryTypeOrmConverter`.
- Updated game db converters to rely on query builder API.
=> Update game find flows to rely on query builder api

turbo.json
- Updated turbo `build` task output to exclude test files.
=> Update turbo build task output to exclude test files

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotFindQueryToGameSlotFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameSlotUpdateQueryToGameSlotFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameUpdateQueryToGameFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameUpdateQueryToGameFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/FindGameTypeOrmService.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/UpdateGameSlotTypeOrmService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameFindQuery.ts, packages/backend/libraries/backend-db/src/persistence/converters/typeorm/QueryToFindQueryTypeOrmConverter.ts
- Updated `GameFindQuery` with `gameSlotFindQuery` property.
- Updated `GameFindQueryToGameFindQueryTypeOrmConverter` to handle `gameSlotFindQuery` property.
- Updated Query builder based converters to rely on an `ObjectLiteral` based query builder.
=> Update GameFindQuery with gameSlotFindQuery property

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/converters/GameFindQueryToGameFindQueryTypeOrmConverter.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameFindQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameFindQuery.ts
- Updated `GameFindQuery` with additional filters.
- Updated `GameFindQueryToGameFindQueryTypeOrmConverter` to handle game filtering on top of game slots filters in such a way no game slots are lost in the way.
- Updated `GameFindQueryToGameFindQueryTypeOrmConverter` to handle `GameFindQuery` new filters.
=> Update GameFindQuery with additional filters

packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/nest/UserDbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserCodePersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserCodePersistenceTypeOrmAdapter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserCodeCreateQueryToUserCodeCreateQueryTypeOrmConverter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserCodeCreateQueryToUserCodeCreateQueryTypeOrmConverter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserCodeDbToUserCodeConverter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserCodeDbToUserCodeConverter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserCodeFindQueryToUserCodeFindQueryTypeOrmConverter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/converters/UserCodeFindQueryToUserCodeFindQueryTypeOrmConverter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/CreateUserCodeTypeOrmService.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/DeleteUserCodeTypeOrmService.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/FindUserCodeTypeOrmService.ts, packages/backend/apps/user/backend-user-application/src/auth/adapter/nest/modules/AuthApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/index.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/output/UserCodePersistenceOutputPort.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserCodeCreateQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserCodeFindQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/query/UserCodeCreateQuery.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/query/UserCodeFindQuery.ts
- Added `UserCodePersistenceTypeOrmAdapter`.
- Added `DeleteUserCodeTypeOrmService`.
- Added `FindUserCodeTypeOrmService`.
- Added `CreateUserCodeTypeOrmService`.
- Added `UserCodeCreateQueryToUserCodeCreateQueryTypeOrmConverter`.
- Added `UserCodeFindQueryToUserCodeFindQueryTypeOrmConverter`.
- Added `UserCodeDbToUserCodeConverter`.
- Added `UserCodePersistenceOutputPort`.
- Added `UserCodeCreateQuery`.
- Added `UserCodeFindQuery`.
- Updated wrong module imports
=> Add UserCodePersistenceTypeOrmAdapter

packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/CurrentPlayerCanPlayCardsSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/CurrentPlayerCanPlayCardsSpec.ts
- Renamed `PlayerCanPlayCardsSpec` to `CurrentPlayerCanPlayCardsSpec`.
- Updated `PlayerCanPlayCardsSpec` to rely on `CardCanBePlayedSpec`.
=> Update PlayerCanPlayCardsSpec to rely on CardCanBePlayedSpec

packages/backend/apps/user/backend-user-application/src/users/adapter/nest/modules/UserApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/users/application/builders/UserActivationMailDeliveryOptionsFromUserBuilder.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/CreateUserUseCaseHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/CreateUserUseCaseHandler.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.ts
- Added `CreateUserUseCaseHandler`.
- Updated `UserManagementInputPort` to use `CreateUserUseCaseHandler`.
- Updated `UserActivationMailDeliveryOptionsFromUserBuilder.build` with right frontend url.
=> Extract user create logic into use case handler

packages/backend/apps/common/backend-adapter-nodemailer/.gitignore, packages/backend/apps/common/backend-app-jwt/.gitignore, packages/backend/apps/common/backend-app-uuid/.gitignore, packages/backend/apps/game/backend-app-game-env/.gitignore, packages/backend/apps/game/backend-game-adapter-typeorm/.gitignore, packages/backend/apps/game/backend-game-application/.gitignore, packages/backend/apps/game/backend-game-domain/.gitignore, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/user/backend-app-user-env/.gitignore, packages/backend/apps/user/backend-user-adapter-typeorm/.gitignore, packages/backend/apps/user/backend-user-application/.gitignore, packages/backend/apps/user/backend-user-domain/.gitignore, packages/backend/libraries/backend-common/src/error/application/models/AppError.ts, packages/backend/libraries/backend-db/.gitignore, packages/backend/libraries/backend-env/.gitignore, packages/backend/libraries/backend-http/.gitignore, packages/backend/libraries/backend-jwt/.gitignore, packages/backend/services/backend-service-game/.gitignore, packages/backend/services/backend-service-user/.gitignore, packages/backend/tools/backend-jest-config/lib/config/getJestProjectConfig.js
- Update `GameService.buildPassTurnGameUpdateQuery` to handle card deck refill.
- Updated `AppError` with `isAppErrorOfKind`.
- Updated jest base config to avoid covering fixtures.
- Update `gitignore` files with coverage folder.
=> Update game service pass turn update query to handle deck refill

packages/backend/apps/user/backend-user-application/src/foundation/hash/application/models/HashContext.ts, packages/backend/apps/user/backend-user-application/src/users/application/converters/UserCreateQueryFromUserCreateQueryV1Builder.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/converters/UserCreateQueryFromUserCreateQueryV1Builder.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/input/UserManagementInputPort.ts
- Updated `UserCreateQueryFromUserCreateQueryV1Builder` with `bcryptHashProviderOutputPort` instead of relying on a hash context.
=> Update UserCreateQueryFromUserCreateQueryV1Builder with port

packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameInitialDrawsMutationFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameDrawService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameDrawService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/GameInitialDrawsMutation.ts
- Updated `GameDrawService` with `calculateInitialCardsDrawMutation`.
- Updated `GameService` to rely on `GameDrawService.calculateInitialCardsDrawMutation`.
=> Extract draw initial cards logic to GameDrawService

packages/backend/libraries/backend-db/src/persistence/services/typeorm/DeleteTypeOrmService.spec.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/DeleteTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/FindTypeOrmService.spec.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/FindTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/InsertTypeOrmService.spec.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/UpdateTypeOrmService.spec.ts, packages/backend/libraries/backend-db/src/persistence/services/typeorm/UpdateTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/utils/typeorm/isQueryBuilder.spec.ts, packages/backend/libraries/backend-db/src/persistence/utils/typeorm/isQueryBuilder.ts
- Fixed `typeorm` services to correctly detect query builders through `InstanceChecker`.
=> Update typeorm services to rely on InstanceChecker

packages/backend/libraries/backend-pub-sub/src/index.ts, packages/backend/libraries/backend-pub-sub/src/modules/adapter/ioredis/IoredisSubscriber.spec.ts, packages/backend/libraries/backend-pub-sub/src/modules/adapter/ioredis/IoredisSubscriber.ts
- Updated `IoredisSubscriber` without `channelToContextMap` in order to delegate child implementations the responsibility of managing channel contexts.
=> Expose IoredisSubscriber

packages/backend/apps/game/backend-game-application/src/auth/application/middlewares/AuthMiddleware.ts, packages/backend/apps/user/backend-user-application/src/auth/application/middlewares/AuthMiddleware.ts, packages/backend/libraries/backend-http/src/index.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.spec.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.ts, packages/backend/libraries/backend-http/src/user/application/ports/input/UserManagementInputPort.ts
- Updated `AuthMiddleware` with an abstract `_findUser` method instead of relying on a `userManagementInputPort`.
=> Update AuthMiddleware with abstraction over composition

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/api/libraries/api-graphql-schemas/schemas/users/UserQuery.graphql, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/adapter/nest/modules/UsersModule.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.ts, packages/backend/libraries/backend-http/src/http/application/modules/DelayedSseConsumer.ts
- Renamed `FindUsersQuery` to `UserQuery`.
- Updated `POST /v1/auth` with right HTTP response codes.
=> Update user query resolver types

.github/renovate.json, packages/backend/tools/backend-maildev/docker/maildev.Dockerfile
- Updated renovate config with docker node policy.
- Updated maildev docker image to be on top node 20.
=> Docker node renovatebot constraints

package.json, packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/ApplicationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/adapter/nest/modules/GamesModule.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts
- Added `GameResolver`.
- Added `serve:api:graphql` script.
- Updated `ApplicationResolver` to use `GameResolver`.
- Updated `RootMutation` to implement `GameMutation`.
=> Update graphql service with create game mutation

packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/api/libraries/api-graphql-schemas/schemas/users/UserQuery.graphql, packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/GetUserV1MeHttpRequestController.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts
- Added `userMe` query.
- Updated `QueryResolver` with `userMe`.
- Updated `RootQueryResolver` with `userMe`.
- Updated `GetUserV1MeHttpRequestController` with better types.
- Updated `v1/users/me` docs with right response codes.
=> Add get user me graphql query

package.json, packages/api/libraries/api-graphql-models/src/models/types.ts, packages/api/libraries/api-graphql-schemas/schemas/games/GameMutation.graphql, packages/api/libraries/api-graphql-schemas/schemas/games/GamePassTurnInput.graphql, packages/api/libraries/api-graphql-schemas/schemas/games/GamePlayCardsInput.graphql, packages/api/libraries/api-graphql-schemas/schemas/root.graphql, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/foundation/graphql/application/models/CanonicalResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts, packages/frontend/web-ui/package.json
- Added `passGameTurn` mutation.
- Added `playGameCards` mutation.
- Added `CanonicalResolver` type.
- Updated `RootQuery` to rely on `CanonicalResolver`.
- Updated `RootMutation` to rely on `CanonicalResolver`.
=> Add update game graphql mutations

packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1700842833047-AddGameSpec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/models/entities.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/nest/modules/GameDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GameSpecPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GameSpecPersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecCreateQueryTypeormFromGameGameSpecCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecCreateQueryTypeormFromGameGameSpecCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFromGameSpecDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSpecFromGameSpecDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/fixtures/GameSpecDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameSpecDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/CreateGameSpecTypeOrmService.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameCreateQueryFromGameCreateQueryV1Builder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameCreateQueryContextFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameCreatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameCreatedEventHandler.ts, packages/backend/apps/game/backend-game-application/src/games/application/index.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/GameCreateQueryContext.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameManagementInputPort.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GameSpecPersistenceOutputPort.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameSpecCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameSpecCreateQuery.ts
- Added `Add GameSpecDb`.
- Added `CreateGameSpecTypeOrmService`.
- Added `GameSpecPersistenceOutputPort`.
- Added `GameSpecPersistenceTypeOrmAdapter`.
- Updated `GameCreatedEventHandler` to persist game spec as `GameSpecDb`.
=> Add GameSpecDb

packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/ApplicationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/app/application/resolvers/RootQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/auth/application/resolvers/AuthMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/foundation/graphql/application/models/Context.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameQueryResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/games/application/resolvers/GameResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/index.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserMutationResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserMutationResolver.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.spec.ts, packages/backend/apps/gateway/backend-gateway-application/src/users/application/resolvers/UserQueryResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/apollo/calculations/buildApolloApplicationResolver.ts, packages/backend/services/backend-service-gateway/src/app/adapter/nest/actions/registerFastifyApolloHandler.ts, packages/backend/services/backend-service-gateway/src/app/adapter/nest/actions/registerSignalHandlers.ts, packages/backend/services/backend-service-gateway/src/app/adapter/nest/calculations/buildApolloServer.ts, packages/backend/services/backend-service-gateway/src/app/adapter/nest/scripts/bootstrap.ts
- Updated server to rely on `Context`.
- Update resolvers to rely on `Context`.
=> Update apollo server to rely on Context

packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserCodePersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserCodePersistenceTypeOrmAdapter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/adapters/UserPersistenceTypeOrmAdapter.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/output/UserCodePersistenceOutputPort.ts, packages/backend/apps/user/backend-user-application/src/users/application/ports/output/UserPersistenceOutputPort.ts
- Updated `UserPersistenceOutputPort.create` with optional `TransactionContext`.
- Updated `UserCodePersistenceOutputPort.create` with optional `TransactionContext`.
=> Update user port create contracts with optional transaction context

.github/actions/setup/action.yaml, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/models/TypeOrmTransactionContext.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/models/TypeOrmTransactionContext.ts
- Updated `TypeOrmTransactionContext` to propagate errors.
=> Update TypeOrmTransactionContext to propagate errors

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GamePersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GamePersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GameSpecPersistenceTypeOrmAdapter.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/adapters/GameSpecPersistenceTypeOrmAdapter.ts, packages/backend/apps/game/backend-game-application/package.json, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GamePersistenceOutputPort.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/output/GameSpecPersistenceOutputPort.ts
- Updated `GamePersistenceOutputPort.create` with optional TransactionContext.
- Updated `GameSpecPersistenceOutputPort.create` with optional TransactionContext.
=> Update GameSpecPersistenceOutputPort.create with optional TransactionContext

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClient.ts, packages/api/libraries/api-http-client/src/typescript/builders/HttpClientMethodsBuilder.ts
- Updated `HttpClientMethodsBuilder.#buildParameters` to handle request body required property.
=> Update HttpClientMethodsBuilder to handle request body required property

packages/backend/apps/user/backend-user-adapter-typeorm/src/foundation/db/adapter/typeorm/builders/BaseFindQueryToFindQueryTypeOrmBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/nest/modules/TokenDbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/adapters/RefreshTokenPersistenceTypeormAdapter.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/adapters/RefreshTokenPersistenceTypeormAdapter.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/builders/RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/builders/RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/tokens/adapter/typeorm/services/FindRefreshTokenTypeOrmService.ts, packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/tokens/application/ports/output/RefreshTokenPersistenceOutputPort.ts, packages/backend/apps/user/backend-user-domain/src/tokens/domain/fixtures/RefreshTokenFindQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/tokens/domain/fixtures/index.ts, packages/backend/apps/user/backend-user-domain/src/tokens/domain/index.ts, packages/backend/apps/user/backend-user-domain/src/tokens/domain/queries/RefreshTokenFindQuery.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.ts, packages/backend/services/backend-service-user/src/auth/adapters/nest/controllers/PostAuthV2HttpRequestNestController.ts
- Added `RefreshTokenFindQuery`.
- Added `RefreshTokenFindQueryTypeOrmFromRefreshTokenFindQueryBuilder`.
- Added `FindRefreshTokenTypeOrmService`.
- Updated `FindTypeOrmQueryBuilderService` to accept optional transaction wrapper.
- Updated `RefreshTokenPersistenceOutputPort` with `findOne`.
=> Add refresh token find persistence flow

packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/FindGameSpecTypeOrmService.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/services/FindGameTypeOrmService.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameGameIdEventsV1RequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameGameIdSlotSlotIdCardsV1RequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGameV1MineRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GetGamesV1SpecsRequestParamHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/PatchGameGameIdV1RequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/DeleteUserV1MeRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/GetUserV1MeRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PatchUserV1MeRequestParamHandler.spec.ts, packages/backend/libraries/backend-http/src/auth/application/models/Auth.ts, packages/backend/libraries/backend-http/src/auth/application/models/UserAuth.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.spec.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.ts
- Updated typeorm services to extend `FindTypeOrmQueryBuilderService`.
- Updated `Auth` and `UserAuth` with `TPayload` generic.
- Updated `UserAuth` with `jwtPayload` property.
- Updated `AuthMiddleware` to provide jwt payload.
=> Update Auth Middleware to provide jwt payload

packages/backend/apps/game/backend-game-application/src/users/application/models/AccessTokenJwtPayload.ts, packages/backend/apps/game/backend-game-application/src/users/application/models/UserJwtPayload.ts, packages/backend/apps/user/backend-user-application/src/auth/adapter/nest/modules/AuthApplicationModule.ts, packages/backend/apps/user/backend-user-application/src/auth/application/controllers/PostAuthV2HttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/auth/application/handlers/PostAuthV2RequestParamHandler.ts, packages/backend/apps/user/backend-user-application/src/auth/application/index.ts, packages/backend/apps/user/backend-user-application/src/auth/application/middlewares/AccessTokenAuthMiddleware.ts, packages/backend/apps/user/backend-user-application/src/auth/application/middlewares/AuthMiddleware.ts, packages/backend/apps/user/backend-user-application/src/auth/application/middlewares/RefreshTokenAuthMiddleware.ts, packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.spec.ts, packages/backend/apps/user/backend-user-application/src/auth/application/ports/input/AuthManagementInputPort.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/DeleteUserV1MeHttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/GetUserV1MeHttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/GetUserV1UserIdHttpRequestController.ts, packages/backend/apps/user/backend-user-application/src/users/application/controllers/PatchUserV1MeHttpRequestController.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.spec.ts, packages/backend/libraries/backend-http/src/user/application/middleware/AuthMiddleware.ts
- Updated `PostAuthV2HttpRequestController` to provide auth by refresh token if provided.
- Updated `AuthMiddleware` with `_verifyJwtPayload`.
- Updated `AuthManagementInputPort` with `createByRefreshTokenV2`.
=> Update PostAuthV2HttpRequestController to provide auth by refresh token if provided

packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1708646400000-AddGameHistory.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/foundation/db/adapter/nest/models/entities.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/fixtures/GameDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameActionDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameActionKindDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameInitialSnapshotDb.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameInitialSnapshotSlotDb.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/BaseGameAction.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/DrawGameAction.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/GameAction.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/GameActionKind.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/PassTurnGameAction.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/PlayCardsGameAction.ts, packages/backend/apps/game/backend-game-domain/src/gameSnapshots/domain/entities/GameInitialSnapshot.ts, packages/backend/apps/game/backend-game-domain/src/gameSnapshots/domain/entities/GameInitialSnapshotSlot.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameUpdateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameUpdateQuery.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/ActiveGameState.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/BaseGameSlot.ts
- Added `GameAction`.
- Added `GameInitialSnapshot`.
- Added `GameActionDb`.
- Added `GameInitialSnapshotDb`.
- Updated `Game` with `turn`.
- Updated builders to handle Game turn.
- Updated `GameService` to properly set game turns.
=> Update game db entities with game history ones

packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1709405917920-UpdateGameWithSkipCount.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/fixtures/GameDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameUpdateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameUpdateQuery.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/ActiveGameState.ts, packages/backend/tools/backend-test-e2e/src/game/utils/actions/setActiveGameCards.ts
- Added `GameDb` migration.
- Updated `ActiveGameState` with `skipCount`.
- Updated `GameDb` with `skipCount`.
This allow us to fix in further PR #1011.
=> Update ActiveGameState with skipCount

packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/services/GameService.ts
- Updated `GameService.buildPassTurnGameUpdateQuery` to skip turns if game skip cards were played.
- Updated `GameService.buildPlayCardsGameUpdateQuery` to update `game.drawCount` when draw cards are played.
- Updated `GameService.buildPlayCardsGameUpdateQuery` to update `game.skipCount` when skip cards are played.
- Fixes #1011.
=> Update GameService to skip players if skip cards were played

packages/backend/apps/game/backend-game-adapter-typeorm/src/app/adapter/typeorm/migrations/1709670322300-UpdateGameWithCardsDrawnFlag.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameFromGameDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/builders/GameSetQueryTypeOrmFromGameUpdateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/fixtures/GameDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/games/adapter/typeorm/models/GameDb.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameUpdateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/query/GameUpdateQuery.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/valueObjects/ActiveGameState.ts
- Updated `GameDb` with `currentTurnCardsDrawn` and `currentTurnSingleCardDraw`.
- Updated `ActiveGameState` with `currentTurnCardsDrawn` and `currentTurnSingleCardDraw`.
- Updated `GameUpdateQuery` with `currentTurnCardsDrawn` and `currentTurnSingleCardDraw`.
=> Update game with draw flag

packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/ActiveGameSlotFixtures.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameSpecFixtures.ts, turbo.json
- Updated `GamePassTurnUpdateQueryFromGameBuilder` to properly set `currentPlayingSlotIndex`.
=> Fix GamePassTurnUpdateQueryFromGameBuilder

packages/backend/apps/game/backend-game-domain/src/cards/adapter/nest/CardDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/cards/domain/specs/IsValidInitialCardSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/cards/domain/specs/IsValidInitialCardSpec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/StartGameUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/StartGameUpdateQueryFromGameBuilder.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/fixtures/GameDrawMutationFixtures.ts
- Added `IsValidInitialCardSpec`.
- Updated `StartGameUpdateQueryFromGameBuilder` to draw cards until a valid initial one is the current one.
- Fixes #1012.
=> Update start game flow to never start game with wild draw 4 current card

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/services/CreateGameActionTypeOrmService.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/index.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/InsertTypeOrmQueryBuilderService.int.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/InsertTypeOrmQueryBuilderService.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/InsertTypeOrmQueryBuilderService.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/postgres/InsertTypeOrmQueryBuilderPostgresService.ts
- Added `InsertTypeOrmQueryBuilderService`.
- Added `InsertTypeOrmQueryBuilderPostgresService`.
- Updated `CreateGameActionTypeOrmService` to be on top of `InsertTypeOrmQueryBuilderPostgresService`.
=> Add insert typeorm query builder service

packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.int.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.spec.ts, packages/backend/libraries/backend-db/src/persistence/adapter/typeorm/services/FindTypeOrmQueryBuilderService.ts
- Updated `FindTypeOrmQueryBuilderService`tests with `count` ones.
=> Add FindTypeOrmQueryBuilderService count tests

packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/fixtures/GameActionDbPayloadV1Fixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/PassTurnGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/PlayCardsGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameActionCreateQueryFromGameUpdateEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameActionCreateQueryFromGameUpdateEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameMessageEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameEventV2FromGameMessageEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/ActiveGameUpdatedEventFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameUpdatedMessageEventFixtures.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameUpdatedEventHandler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/models/BaseActiveGameUpdatedEvent.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/PassTurnGameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/PlayCardsGameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/PassTurnGameAction.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/PlayCardsGameAction.ts
- Updated GameAction with additional fields.
- Updated `PlayCardsGameActionCreateQuery` with `currentCard`.
- Updated `PassTurnGameActionCreateQuery` with `nextPlayingSlotIndex`.
- Updated `BaseActiveGameUpdatedEvent` with game.
=> Update GameAction with additional fields

packages/backend/apps/game/backend-game-application/src/games/application/controllers/GetGameGameIdEventsV2SseController.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/ports/input/GameEventsManagementInputPort.ts, packages/backend/apps/game/backend-game-domain/src/games/adapter/nest/GameDomainModule.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/GameEventsCanBeObservedSpec.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/specs/GameEventsCanBeObservedSpec.ts
- Added `GameEventsCanBeObservedSpec`.
- Updated `GameEventsManagementInputPort.subscribeV2` with `Game` argument.
- Updated `GameEventsManagementInputPort.subscribeV2` to rely on `GameEventsCanBeObservedSpec`.
=> Update events games endpoint to refure request if game is not active

packages/backend/tools/backend-jest-config/lib/config/getJestJsProjectConfig.js, packages/backend/tools/backend-jest-config/lib/config/getJestTsProjectConfig.js, packages/backend/tools/backend-jest-config/lib/config/getTestMatch.js
- Updated `getTestMatch()` to return an array ignoring esm js files.
=> Update getTestMatch() to return an array

packages/frontend/web-ui/src/app/store/features/authSlice.ts, packages/frontend/web-ui/src/common/helpers/useSingleApiCall.int.spec.ts, packages/frontend/web-ui/src/common/helpers/useSingleApiCall.ts, packages/frontend/web-ui/src/game/hooks/useCreateGame/index.ts, packages/frontend/web-ui/src/game/hooks/useCreateGame/utils/useContext.spec.ts, packages/frontend/web-ui/src/game/hooks/useCreateGame/utils/useContext.ts, packages/frontend/web-ui/src/game/hooks/useCreateNewGame.spec.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/index.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/useContext.spec.ts, packages/frontend/web-ui/src/home/hooks/useGetGames/utils/useContext.ts, packages/frontend/web-ui/src/home/pages/CornieHome.spec.tsx, packages/frontend/web-ui/src/home/pages/CornieHome.tsx
- Update `CornieHome` to rely on auth state status.
- Rename `buildSingleApiHook` and related interfaces and modules to adopt react conventions.
=> Adopt react hook conventions

packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResult.spec.ts, packages/frontend/web-ui/src/common/helpers/mapUseQueryHookResult.ts, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts, packages/frontend/web-ui/src/user/hooks/useUserInfo.spec.ts, packages/frontend/web-ui/src/user/hooks/useUserInfo.ts, packages/frontend/web-ui/src/user/models/UserInfoStatus.ts
- Added `useUserInfo` hook.
- Added `UserInfoStatus`.
- Added `mapUseQueryHookResult`.
- Updated `cornieApi` mock with `useUpdateUsersV1MeMutation` mock.
=> Add use user info hook

packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/nest/modules/UserDbModule.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserSetQueryTypeOrmFromUserUpdateQueryBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserSetQueryTypeOrmFromUserUpdateQueryBuilder.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/services/UpdateUserTypeOrmService.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/fixtures/UserUpdateQueryFixtures.ts, packages/backend/apps/user/backend-user-domain/src/users/domain/query/UserUpdateQuery.ts
- Updated `UserUpdateQuery` with `passwordHash`.
- Updated `UserSetQueryTypeOrmFromUserUpdateQueryBuilder` to handle `passwordHash`.
=> Update UserUpdateQuery with passwordHash

packages/api/libraries/api-http-client/src/httpClient/generated/HttpClientEndpoints.ts, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PostUserV1EmailCodeRequestParamHandler.spec.ts, packages/backend/apps/user/backend-user-application/src/users/application/handlers/PostUserV1EmailCodeRequestParamHandler.ts, packages/frontend/libraries/frontend-api-rtk-query/src/foundation/http/models/httpCodes.ts, packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/models/CreateUsersV1Args.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/models/CreateUsersV1EmailCodeArgs.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/createUsersV1.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/createUsersV1.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/createUsersV1EmailCode.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/createUsersV1EmailCode.ts
- Added `createUsersV1` mutation.
- Added `createUsersV1EmailCode` mutation.
- Updated `CreateUserCodeRequestParamHandler` to thrown an `unprocessableOperation` error.
- Updated API docs.
=> Update rtk query with user and user code mutations

.github/workflows/publish-docker-image.yaml
- Updated gh action concurrency to rely on docker image.
=> Update concurrency to rely on docker image

packages/frontend/web-ui/src/auth/pages/Login.spec.tsx, packages/frontend/web-ui/src/auth/pages/Login.tsx, packages/frontend/web-ui/src/common/components/Navbar.tsx, packages/frontend/web-ui/src/common/components/NavbarGamesMenu.tsx, packages/frontend/web-ui/src/common/components/NavbarUserMenu.tsx, packages/frontend/web-ui/src/common/helpers/getSlug.spec.ts, packages/frontend/web-ui/src/common/helpers/getSlug.ts, packages/frontend/web-ui/src/common/hooks/useRedirectUnauthorized.spec.ts, packages/frontend/web-ui/src/common/hooks/useRedirectUnauthorized.ts, packages/frontend/web-ui/src/common/models/NavbarPageName.ts, packages/frontend/web-ui/src/common/models/PageName.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useJoinExistingGame.ts, packages/frontend/web-ui/src/game/pages/CreateNewGame.spec.tsx, packages/frontend/web-ui/src/game/pages/CreateNewGame.tsx
- Updated `getSlug` to be used to get the slug of any page, not only navbar related pages.
=> Update getSlug to be generic

packages/frontend/web-ui/src/game/components/NonStartedGameList.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.spec.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.tsx, packages/frontend/web-ui/src/scss/home/_gameList.scss, packages/frontend/web-ui/src/scss/home/pages/home/_page.scss
- Updated `NonStartedGameListItem` with button options.
=> Update NonStartedGameListItem with ButtonOptions

packages/frontend/web-ui/src/common/components/NavbarGamesMenu.tsx, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts, packages/frontend/web-ui/src/game/components/NonStartedGameList.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameList.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.spec.tsx, packages/frontend/web-ui/src/game/components/NonStartedGameListItem.tsx, packages/frontend/web-ui/src/game/helpers/userCanJoinGame.spec.ts, packages/frontend/web-ui/src/game/helpers/userCanJoinGame.ts, packages/frontend/web-ui/src/game/pages/PublicGames.spec.tsx, packages/frontend/web-ui/src/game/pages/PublicGames.tsx, packages/frontend/web-ui/src/game/routes/GameRoutes.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.spec.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.tsx, packages/frontend/web-ui/src/scss/game/pages/_index.scss, packages/frontend/web-ui/src/scss/game/pages/_publicGames.scss, packages/frontend/web-ui/src/scss/home/_gameList.scss
- Added `PublicGames` page component.
- Added `userCanJoinGame` helper.
- Updated navbar with public games link.
- Updated game routes with public games one.
- Updated `cornieApi` mock with `useGetGamesV1Query`.
- Updated `NonStartedGameListItem` join button to be disabled if user cannot join the game.
=> Add public games page

packages/frontend/web-ui/src/game/helpers/buildGameWithSpecPairArrayResult.spec.ts, packages/frontend/web-ui/src/game/helpers/buildGameWithSpecPairArrayResult.ts, packages/frontend/web-ui/src/game/hooks/useGetGameSpecsV1ForGames.spec.ts, packages/frontend/web-ui/src/game/hooks/useGetGameSpecsV1ForGames.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesMineWithSpecsV1.spec.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesMineWithSpecsV1.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesWithSpecsV1.spec.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesWithSpecsV1.ts, packages/frontend/web-ui/src/game/models/GameWithSpecPair.ts
- Added `useGetGamesV1Mine`.
- Added `useGetGameSpecsV1ForGames`.
- Added `buildGameWithSpecPairArrayResult`.
- Updated `useGetGamesWithSpecsV1`. to rely on extracted modules.
=> Extract useGetGamesMineWithSpecsV1

packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1GameId.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/games/queries/getGamesV1GameId.ts, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts, packages/frontend/web-ui/src/common/pages/PageNotFound.tsx, packages/frontend/web-ui/src/game/hooks/useGetGamesV1GameId.spec.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesV1GameId.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesV1GameIdSlotsSlotIdCards.spec.ts, packages/frontend/web-ui/src/game/hooks/useGetGamesV1GameIdSlotsSlotIdCards.ts
- Added `useGetGamesV1GameIdSlotsSlotIdCards`.
- Added `useGetGamesV1GameId`.
- Updated `getGamesV1GameId` to return `undefined` on entity not found.
- Updated `PageNotFound` page without deprecations.
=> Add game hooks

packages/frontend/web-ui/src/game/helpers/getGameSlotIndex.spec.ts, packages/frontend/web-ui/src/game/helpers/getGameSlotIndex.ts, packages/frontend/web-ui/src/game/hooks/useGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useGame.ts
- Added `useGame` hook.
- Added `getGameSlotIndex` helper.
=> Add useGame hook

packages/api/libraries/api-json-schemas/schemas/v2/gameEvents/cards-played-game-event.json, packages/api/libraries/api-models/src/models/types.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/nest/modules/GameActionDbModule.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionCreateQueryTypeOrmFromGameActionCreateQueryBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.spec.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/builders/GameActionFromGameActionDbBuilder.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/fixtures/GameActionDbFixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/fixtures/GameActionDbPayloadV1Fixtures.ts, packages/backend/apps/game/backend-game-adapter-typeorm/src/gameActions/adapter/typeorm/models/v1/PlayCardsGameActionDbPayloadV1.ts, packages/backend/apps/game/backend-game-application/src/gameActions/adapter/nest/modules/GameActionApplicationModule.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/builders/GameEventV2FromGameActionBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/gameActions/application/builders/GameEventV2FromGameActionBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameActionCreateQueryFromGameUpdateEventBuilder.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/builders/GameActionCreateQueryFromGameUpdateEventBuilder.ts, packages/backend/apps/game/backend-game-application/src/games/application/fixtures/GameUpdatedMessageEventFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionCreateQueryFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/fixtures/GameActionFixtures.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/index.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/query/PlayCardsGameActionCreateQuery.ts, packages/backend/apps/game/backend-game-domain/src/gameActions/domain/valueObjects/PlayCardsGameAction.ts
- Updated `CardsPlayedGameEventV2` with additional fields.
- Updated `GameAction` play cards payload with additional fields.
`currentColor`, `currentDirection` and `drawCount` are required to compute game state updates on the client side. For such a reason these fields are provided in the events and stored in the corresponding game action payloads.
=> Update play card game event

.changeset/long-tigers-brake.md, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdDrawCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPassTurnQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.spec.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdPlayCardsQueryV1Handler.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/GameIdUpdateQueryV1Handler.ts
- Update `GameIdUpdateQueryV1Handler._getUpdatedGame` to rely on a `TransactionWrapper`.
=> Fix GameIdUpdateQueryV1Handler

packages/frontend/web-ui/src/auth/helpers/createUserCodeErrorMessage.ts, packages/frontend/web-ui/src/auth/helpers/getCreateUserCodeErrorMessage.spec.ts, packages/frontend/web-ui/src/auth/helpers/getCreateUserCodeErrorMessage.ts, packages/frontend/web-ui/src/auth/hooks/useRegister.spec.ts, packages/frontend/web-ui/src/auth/hooks/useRegister.ts
- Added new file `createUserCodeErrorMessage.ts` with error message to **User code created**.
- Added new function getCreateUserCodeErrorMessage.ts` and his test, to extract the specific error message.
- Modify `useRegister.ts` and his test to switch use on `mapUseQueryHookResult` to V2 version.
=> Update use register to relay rtk query v2

.changeset/eleven-geese-stare.md, .changeset/silent-pigs-worry.md, packages/api/libraries/api-openapi-schema/schemas/src/one-game.yaml, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeCreateQueryTypeOrmFromUserCodeCreateQueryBuilder.spec.ts, packages/backend/apps/user/backend-user-adapter-typeorm/src/users/adapter/typeorm/builders/UserCodeCreateQueryTypeOrmFromUserCodeCreateQueryBuilder.ts
- Updated `UserCodeCreateQueryTypeOrmFromUserCodeCreateQueryBuilder` to persist user code create query kinds.
This fixes POST `/v1/users/email/{email}/code` to trigger proper reset password mail messages.
=> Fix UserCodeCreateQueryTypeOrmFromUserCodeCreateQueryBuilder

.changeset/four-beans-laugh.md, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/adapters/MessageSendPulsarAdapter.spec.ts, packages/backend/apps/common/backend-adapter-pulsar/src/persistence/adapter/pulsar/adapters/MessageSendPulsarAdapter.ts, packages/backend/apps/common/backend-application-messaging/src/index.ts, packages/backend/apps/common/backend-application-messaging/src/mail/application/models/MessageDeliveryOptions.ts, packages/backend/apps/game/backend-game-application/src/games/application/handlers/NonStartedGameFilledEventHandler.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/GamePassTurnUpdateQueryFromGameBuilder.ts
- Updated game update flow to set `turnExpiresAt`.
- Updated `MessageDeliverySchedule` with `MessageDeliveryTimeSchedule` variant.
=> Update game update flow to set turnExpiresAt

.changeset/purple-plants-tie.md, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/StartGameUpdateQueryFromGameBuilder.spec.ts, packages/backend/apps/game/backend-game-domain/src/games/domain/builders/StartGameUpdateQueryFromGameBuilder.ts, packages/backend/libraries/backend-api-validators/package.json, packages/backend/libraries/backend-api-validators/src/validation/infrastructure/validatorProviders/ajv/AjvJsonSchemaValidatorProvider.spec.ts, packages/backend/libraries/backend-api-validators/src/validation/infrastructure/validatorProviders/ajv/AjvJsonSchemaValidatorProvider.ts
- Update `StartGameUpdateQueryFromGameBuilder` to set `turnExpiresAt`.
- Update `AjvJsonSchemaValidatorProvider` to support json-schema formats.
=> Fix game service

packages/frontend/libraries/frontend-api-rtk-query/src/index.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/models/DeleteUsersV1EmailCodeArgs.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/deleteUsersV1EmailCode.spec.ts, packages/frontend/libraries/frontend-api-rtk-query/src/users/mutations/deleteUsersV1EmailCode.ts, packages/frontend/web-ui/src/auth/hooks/useAuthForgot.spec.ts, packages/frontend/web-ui/src/auth/hooks/useAuthForgot.ts, packages/frontend/web-ui/src/auth/models/UseAuthForgotStatus.ts, packages/frontend/web-ui/src/common/http/services/__mocks__/cornieApi.ts
- Added new file `DeleteUserV1EmailCodeArgs.ts`, params for new mutation `useDeleteUserV1EmailCodeMutation`.
- Added new file `deleteUserV1EmailCode.ts` and his test, to process the result of execution of the new mutation.
- Modified file `cornieApi.ts` on mocks' carpet to add new _jest function_ to test `useDeleteUserV1EmailCodeMutation`.
- Modified file `index.ts` to add new mutation `useDeleteUserV1EmailCodeMutation`.
- Modified file `UseAuthForgotStatus.ts` to add new status on enum.
- Modified files `useAuthForgot.ts` and his test, to add new functionality to delete user code before sending a recovery password email.
=> Delete conflict code when user use forgot password

packages/frontend/web-ui/src/common/hooks/useCountdown.ts, packages/frontend/web-ui/src/game/helpers/handleGameMessageEvents.spec.ts, packages/frontend/web-ui/src/game/helpers/handleGameMessageEvents.ts, packages/frontend/web-ui/src/game/hooks/useGame.spec.ts, packages/frontend/web-ui/src/game/hooks/useGame.ts, packages/frontend/web-ui/src/game/pages/PublicGames.spec.tsx, packages/frontend/web-ui/src/home/components/HomeWithAuth.spec.tsx, packages/frontend/web-ui/src/user/hooks/useGetUserMe.spec.ts, packages/frontend/web-ui/src/user/hooks/useGetUserMe.ts
- Updated `handleGameMessageEvents` to update `turnExpiresAt`.
- Updated `useGame` to set count down on edge cases.
- Updated `UseCountDownResult.start` to be called with seconds param.
- Updated `handleGameMessageEvents` with `onTurnChange`.
- Updated `UseGetUserMeResult` with queryResult.
=> Update use game to count down on edge cases

.husky/commit-msg
- Updated `commit-msg` hook to rely on `pwd`.
=> Update commit-msg hook to rely on pwd

packages/frontend/web-ui/src/game/components/BaseCard.spec.tsx, packages/frontend/web-ui/src/game/components/BaseCard.tsx, packages/frontend/web-ui/src/game/components/Card.spec.tsx, packages/frontend/web-ui/src/game/components/Card.tsx, packages/frontend/web-ui/src/game/components/DrawCard.spec.tsx, packages/frontend/web-ui/src/game/components/DrawCard.tsx, packages/frontend/web-ui/src/game/components/ImageCard.spec.tsx, packages/frontend/web-ui/src/game/components/ImageCard.tsx, packages/frontend/web-ui/src/game/components/NormalCard.spec.tsx, packages/frontend/web-ui/src/game/components/NormalCard.tsx, packages/frontend/web-ui/src/game/components/ReverseCard.spec.tsx, packages/frontend/web-ui/src/game/components/ReverseCard.tsx, packages/frontend/web-ui/src/game/components/SkipCard.spec.tsx, packages/frontend/web-ui/src/game/components/SkipCard.tsx, packages/frontend/web-ui/src/game/components/TextCard.spec.tsx, packages/frontend/web-ui/src/game/components/TextCard.tsx, packages/frontend/web-ui/src/game/components/WildCard.spec.tsx, packages/frontend/web-ui/src/game/components/WildCard.tsx, packages/frontend/web-ui/src/game/components/WildDraw4Card.spec.tsx, packages/frontend/web-ui/src/game/components/WildDraw4Card.tsx
- Modify `BaseCard.tsx` and his test to change to `onClick` function.
- Modify `DrawCard.tsx` and his test to change to `onClick` function.
- Modify `ImageCard.tsx` and his test to change to `onClick` function.
- Modify `ReverseCard.tsx` and his test to change to `onClick` function.
- Modify `SkipCard.tsx` and his test to change to `onClick` function.
- Modify `TextCard.tsx` and his test to change to `onClick` function.
- Modify `WildCard.tsx` and his test to change to `onClick` function.
- Modify `Card.tsx` and his test to change to `onClick` function.
- Modify `NormalCard.tsx` and his test to change to `onClick` function.
- Modify `WildDraw4Card.tsx` and his test to change to `onClick` function.
=> Update cards module to change onDoubleClick to onClick
